### ISSUE TITLE
Allow transform callback to return a promise

### ISSUE THREAD

**Issue by simonsmith** [postcss/postcss-import#117]
As part of the `async` API it'd be great to return a promise from the `transform` method. The reason is to allow usage of postcss plugins that are async, like 3.x of `stylelint`.

```js
transform(css, filename) {
  return processor.use(stylelint).process(css, {from: filename});
}
```
Unless there's a way to do something like this already?

**Comment by MoOx** [comment]
Don't think it's supported at the moment.
PR welcome.

**Comment by TrySound** [comment]
Seems like an interesting idea of integration.
/cc @davidtheclark @jeddy3

**Comment by jeddy3** [comment]
Oh, that's nice!

Do you mean adding it to the stylelint docs somewhere? Perhaps in the [complementary tools doc](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md#runnersloaders)?

**Comment by TrySound** [comment]
@jeddy3 Only after dev merge which will be after I'll create [this plugin](https://github.com/postcss/postcss-import/issues/145). Give me a few days.

**Comment by simonsmith** [comment]
Awesome, thanks for adding this @TrySound

**Comment by MoOx** [comment]
So this is good now @TrySound?
