### ISSUE TITLE
spec following

### ISSUE THREAD

**Issue by TrySound** [postcss/postcss-import#133]
Should we follow [spec](http://www.w3.org/TR/css3-cascade/#at-import) and skip and warn if import statement is not before all non-import rules?
This will let resolve media queries much faster and simpler. For now resolver do not follow expectations and it's very difficult to follow them without spec.

/cc @MoOx @ai @ben-eb

**Comment by ben-eb** [comment]
Sounds good to me. :+1:

**Comment by TrySound** [comment]
But we won't be able to do something like this
```
@import "normalize.css";
body {
 margin: 20px;
}
@import "module.css"
```

**Comment by TrySound** [comment]
For now the problem is nesting

```css
/* level-1.css */
@import "level-2.css" level-1;
@import "//level-1";
```
```css
/* level-2.css */
@import "level-3.css" level-2;
@import "//level-2";
```
```css
/* level-3.css */
@import "//level-3";
```
what expected
```css
@import "//level-3" level-1 and level-2;
@import "//level-2" level-1;
@import "//level-1";
```
reality
```css
@import "//level-3" level-2;
@import "//level-2" level-1;
@import "//level-1";
```
Also media rules are not resolved.

**Comment by MoOx** [comment]
Would be closed automatically when your pr/commit land into master.
