### ISSUE TITLE
Resolve base

### ISSUE THREAD

**Issue by emilbayes** [postcss/postcss-import#167]
I'm not sure if this is actually a bug or due to my specific setup, but here goes:

`postcss-import` fails to resolve `normalize.css` which is installed in `node_modules` via npm in the folder I run my `postcss` modules from, however it fails because the `base` that it uses is `/` due to the following `atRule`s:

```js
AtRule {
  raws: { before: '', between: '', afterName: ' ' },
  type: 'atrule',
  name: 'import',
  parent: 
   Root {
     raws: { semicolon: true, after: '\n' },
     type: 'root',
     nodes: [ [Circular], [Object] ],
     source: { input: [Object], start: [Object] } },
  source: 
   { start: { line: 1, column: 1 },
     input: 
      Input {
        css: '@import \'normalize.css\';\n@import \'@data/tooltip\';\n',
        file: '/index.css' },
     end: { line: 1, column: 24 } },
  params: '\'normalize.css\'',
  indexes: 
   { '2': 0,
     '5': 0,
     '8': 0,
     '11': 0,
     '14': 0,
     '17': 0,
     '20': 0,
     '23': 0 } }
AtRule {
  raws: { before: '\n', between: '', afterName: ' ' },
  type: 'atrule',
  name: 'import',
  parent: 
   Root {
     raws: { semicolon: true, after: '\n' },
     type: 'root',
     nodes: [ [Object], [Circular] ],
     source: { input: [Object], start: [Object] } },
  source: 
   { start: { line: 2, column: 1 },
     input: 
      Input {
        css: '@import \'normalize.css\';\n@import \'@data/tooltip\';\n',
        file: '/index.css' },
     end: { line: 2, column: 24 } },
  params: '\'@data/tooltip\'',
  indexes: 
   { '3': 0,
     '6': 0,
     '9': 0,
     '12': 0,
     '15': 0,
     '18': 0,
     '21': 0,
     '24': 0 } }
```

Given [`index.js#L219-L222`](https://github.com/postcss/postcss-import/blob/1d85e23cc6732c277cad89088a29c36da7a449a8/index.js#L219-L222), this clearly resolves to `/`. Anybody know why this is? It would all work if it used `opts.root` instead (which is `process.cwd()`).

So is this due to my setup setting `atRule.source.input.file` or a bug in `postcss-import` (as in, something it should handle)?

**Comment by MoOx** [comment]
Can you try with postcss-import@^7.0.0 please?
Importing a module should work from anywhere. If not, that's a regression from the huge refactoring made for 8.0.

**Comment by emilbayes** [comment]
That would work: [`index.js#L491-L493`](https://github.com/postcss/postcss-import/blob/7.1.3/index.js#L491-L493). The bug is that `root` is not prepended to the `dirname` of the file. Unless the parser uses absolute paths normally, we should prepend the `root` :)

**Comment by MoOx** [comment]
Can't really remember. Maybe @TrySound can help us with that since he is the author of recent changes.
Did you try v7.x ?

**Comment by TrySound** [comment]
@emilbayes Provide setup code please.

**Comment by emilbayes** [comment]
Yeah, v7.x just hangs, but I think it might be for unrelated reasons. However there's this bit in 7.x that's not in 8.x:

[`index.js#L519-L525`](https://github.com/postcss/postcss-import/blob/7.1.3/index.js#L519-L525)
```js
        // LAST HOPE
        if (!paths.some(function(dir2) {
          file = path.join(dir2, name)
          return fs.existsSync(file)
        })) {
          throw err
        }
```

It looks rather nasty, and I'd probably do this in 8.x, given that `source.input.file` is always relative to `process.cwd()`:

```js
  var base = atRule.source && atRule.source.input && atRule.source.input.file
    ? path.dirname(path.join(options.root, atRule.source.input.file))
    : options.root
```

This fixes my issue at least.

**Comment by MoOx** [comment]
Please provide your config, OS and node version.

**Comment by emilbayes** [comment]
I created a minimal test case here https://gist.github.com/emilbayes/3645f8e70d1a6a8e4f0a

```
~ $ node -v
v5.1.1
~ $ npm -v
3.5.3
~ $ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.2 (15C50)
      Kernel Version: Darwin 15.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name:
      User Name:
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot:
```

**Comment by MoOx** [comment]
This is a uncommon usage.
css-modules use postcss under the hood, so it's very likely probable that your way to load your things alter the input or sourcemap somewhere...

**Comment by TrySound** [comment]
The problem is that `source.input.file` shouldn't be `/index.css`. Maybe css-modules resolves this incorrectly?

**Comment by emilbayes** [comment]
Yeah, thought so too. I'll file an issue over there. It seems they set the base to be `/` here: https://github.com/css-modules/css-modulesify/blob/95727b4a189055ca398815050a2adbb235556c99/index.js#L166

**Comment by MoOx** [comment]
Assuming this is fixed
