### ISSUE TITLE
Implement silent flag

### ISSUE THREAD

**Issue by DavidWells** [postcss/postcss-import#174]
## Proposal:

Add `silent` option to ignore errors when @import statements aren't resolved ( the files don't exist )

Much like postcss-mixins and postcss-simple-vars does this https://github.com/postcss/postcss-mixins/blob/master/index.js#L37-L39

I wanted to take a stab at implementing this but I'm having trouble finding where I might ignore the unresolved files in https://github.com/postcss/postcss-import/blob/master/index.js

Any tips/pointers on where to get started?

**Comment by MoOx** [comment]
You will probably need to look for things in https://github.com/postcss/postcss-import/tree/master/lib

**Comment by TrySound** [comment]
@DavidWells Not found file is broken app. Broken app is not good. In this case silent option is bad pattern. Don't have ideas why you need this.

**Comment by RyanZim** [comment]
I agree with @TrySound. Closing for the time being.
