### ISSUE TITLE
All imports after some others CSS declaration should warn and be skipped.

### ISSUE THREAD

**Issue by cedriceberhardt** [postcss/postcss-import#176]
Everything worked on v7. Since v8 it doesn't work anymore.

```
@charset "utf-8";

:root {
    --fontFamily: 'Lato', sans-serif;
    --fontSize: 15px;
    /* ... */
}

@custom-media --medium-screen (width <= 1080px);
@custom-media --small-screen (width <= 580px);
@custom-media --tiny-screen (width <= 320px);

@import url(config/reset.css);
@import url(config/fonts.css);
@import url(config/default.css);
@import url(config/layout.css);
@import url(config/icons.css);
```

results to:

```
@charset "utf-8";
:root {}

@import url(config/reset.css);

/* ... */
/* the next files are all imported correctly */
```

Source files: https://github.com/Frontools/web-starter-kit/tree/master/source/styles
The `build.js` script is launched thanks to node scripts in https://github.com/Frontools/web-starter-kit/blob/master/package.json

**Comment by MoOx** [comment]
Per CSS specifications, import should be at top of a file.

Just move your definitions or root and custom media after import. You are in C(ascading)SS, not in a programming language. custom media and custom props can be defined after a usage, no problem.

All import should warn and be skipped, not just the first poke @TrySound.

**Comment by cedriceberhardt** [comment]
It's true for CSS specifications, but it is not the case here, before parsing.
It's written in the title: "PostCSS plugin to inline @import rules content", which means the resulting CSS will be completely valid as I won't have any imports after the parsing anymore.

Following the specifications is very good, but having a bit of flexibility, like here, too ;)

**Comment by MoOx** [comment]
You do not benefit of anything by defining some rules before. The opposite: if an import define it own value, you will not have yours defined.
You can still move that in another import.

**Comment by cedriceberhardt** [comment]
Yeah, you're right :)

**Comment by LPGhatguy** [comment]
What about imports nested inside rules, which is valid in cases like Sass, and with PostCSS (with `postcss-nested`)?

I don't see any reason to have this restriction in the plugin; we are not in CSS, we are in a superset of CSS.

**Comment by TrySound** [comment]
@LPGhatguy postcss-import never supports nested imports, and never will. We would like to follow spec in most cases.

**Comment by RyanZim** [comment]
@MoOx PR done: #240
