### ISSUE TITLE
Allow import to work within :global

### ISSUE THREAD

**Issue by lucasmotta** [postcss/postcss-import#179]
Hey there,

Recently me and my co-workers made the move to use [css-modules](https://github.com/css-modules/css-modules) and we are having our up and downs with it.

One of the things we came across is importing vendors, so we decided to use `postcss-import`, which works wonder.  
But our problem is that `css-loader` hashes the class name of everything (we kind of want that). And since `postcss-import` happens before the `css-loader`, there's no really way to exclude the vendor from the `css-loader` process.

We found a solution, which is to have a `globals.css` file and create two configs on our webpack config, but don't apply the `css-loader` modules only on the `globals.css`. It works, but it's not ideal.
We could as well request the creators of those vendors to wrap their css on  a `:global {}` ns, but that brings even more complications.

So our suggestion was to allow `@import` inside the `:global {}` ns, something like this:

```scss
// app.css
:global {
  @import "vendor-1";
  @import "vendor-2";
}
```
Which would compile to:
```
:global {
  .vendor1 {
    content: "hey I'm vendor 1";
  }
  .vendor2 {
    content: "and I'm vendor 2!";
  }
}
```

I don't see this creating any compatibility problems with current users, but that would help a lot of people who are adventuring on the `css-modules` world.

If this is something you guys are happy with it, I could help implement it too :)

**Comment by MicheleBertoli** [comment]
+1

**Comment by MoOx** [comment]
Am I right assuming you use webpack guys?

**Comment by lucasmotta** [comment]
@MoOx yes, that's correct! Currently we have two configs for the webpack loader for the time being:
```js
[
  {
    test: /\.css$/,
    loader: 'style!css?modules&importLoaders=1!postcss',
    exclude: /global/,
  },
  {
    test: /\.css$/,
    loader: 'style!css!postcss',
    include: /global/,
  }
]
```

**Comment by lucasmotta** [comment]
We even thought about creating another plugin that introduces another keyword, something like `@global` that would wrap the content of the vendor on `:global {}`:

```css
@global "vendor-1";
@global "vendor-2";
```

But we would rather try to implement this on `postcss-import` instead of introducing something new.

**Comment by TrySound** [comment]
@lucasmotta Try this https://github.com/jonathantneal/postcss-partial-import

**Comment by TrySound** [comment]
:global is not part of spec (Am I wrong?). In this case we can't introduce it.

**Comment by MoOx** [comment]
I have this "issue" with webpack so I use 2 config section, and as you said it works.

I don't see what is the issue having 2 different test entries in webpack module loaders definition.

And I don't think this kind of changes belong here as this will involve some changes.

Maybe you can have litter config by playing on the regex rather than using include/exclude.

**Comment by MoOx** [comment]
Since CSS modules are handled (and declared in) webpack, it make more sense to me to have the thing explicitly in the config itself.

**Comment by lucasmotta** [comment]
No worries guys, I understand, even thou there's no spec for importing files.

Thanks for the tip @TrySound - `postcss-partial-import` worked on my tests, but they don't resolve npm packages (as the name states, it's only for partials).

And unfortunately there's no way to solve this with regex, as `postcss-import` inlines the content of the file before `css-loader`. Meaning `css-loader` has no idea that the vendor I imported was an external file.

About the "involve some changes" is something that of course it would have to be done (as it's a feature request), but I don't see any potential problem on this thou. I'm even willing to contribute for that.

But as you mentioned @MoOx, you had to deal with this problem before. Meaning it's something that more people will face the same problem and if we can solve that with one "option" on `postcss-import` would be much better than everyone having to create their own duplicated config just to exclude vendors.

Any chances we could consider more discussion on this before closing the issue? I really wanted to avoid having to create another postcss import plugin – I think we have enough tbh.

**Comment by MoOx** [comment]
It's weird to have to handle css modules "proprietary" syntax here. This annoys me and will need to be maintained in the future if we offer that.

For my concern, I am currently having this non-issue on multiple projects, where I simply have a single global css that import all global (considered as legacy) css. Like I said, I think it's not a big deal.

When I create a project that need some global CSS, I know that some stuff won't be handled by my config that enable CSS modules. So it makes sense to create another config section for global CSS.

At the opposite, having to disable CSS modules in my postcss(-import) config seems really weird, and make even less sense imo.

[As you can see here](https://github.com/putaindecode/putaindecode.io/blob/fe2c64ecc55739a5b2c229c058a6d74b3277/scripts/webpack.config.babel.js#L37-L67) I am relying on regex, not include/exclude to handle this.

I don't see the point of creating another postcss plugin to handle something you can already do (and you are already doing it) with just a few lines of webpack config.

**Comment by lucasmotta** [comment]
Ideally I wouldn't tie this to css-modules or a specific scope (:global, :local, :root or whatever).
It would be more like "hey, I found this @import on my css, I shall replace it with its content", so it wouldn't be specific to where you import it.

It's similar to what the `postcss-partial-import` does actually – which in my opinion should be merged into  a single `postcss-import` plugin - but again, that's just my opinion.

**Comment by MoOx** [comment]
Currently this plugin aims to follow css specification, so won't parse any other import. But if we can very easily enable replacement of import statements anywhere (via an option, disabled by default) without a huge change. Why not. What do you think @TrySound ? Do you see any issue beside #168?

postcss-partial-import has been created "because" its creator was too impatient for a change in postcss-import if my memory is correct. Currently postcss-partial-import can be implemented with the logic postcss-import v8 brings. So maybe open an issue overthere to discuss about that.

**Comment by TrySound** [comment]
It's not easy because we do a lot more then just inlining. postcss-import also handles media queries in files and resolves them with "parent" files.

**Comment by TrySound** [comment]
This is possible only with spec following. That's why spec introduced those constraints.

**Comment by TrySound** [comment]
partial-import can be just inliner without media resolver (it has simplest realization). It's syntax prefering.

**Comment by MoOx** [comment]
Note for people that will say "it was working in pre v8", it was working, but was buggy.

**Comment by scherebedov** [comment]
Hi all. I had the same problem and I made for this plugin [postcss-global-import](https://github.com/scherebedov/postcss-global-import)

**Comment by karthikiyengar** [comment]
Took me a while, but a less painful way of importing external files globally would be something like this:

`import '!style!css!react-select/dist/react-select.css';`

This would come with the advantage of not having to have a separate webpack config for global imports.
