### ISSUE TITLE
Failing case with autoprefixer!

### ISSUE THREAD

**Issue by jasonkuhrt** [postcss/postcss-import#19]
I am working off this `cssnext` version https://github.com/littlebits/cssnext/tree/feature/add-postcss-url which is bleeding edge.

I am trying to use it in my project and am noticing some strange behaviour that I'm pretty sure represents a breaking deviation from before. Namely the package `normalize.css` (yes, `.css` is literally in the package name) is causing all sorts of trouble for `cssnext`. I assume its due to `postcss-import` though honestly I just don't know yet.

Here is a screenshot of the error in my *project dep* (I've opened an editor *into* my `littlebits-ui` dep:

![screen shot 2015-01-27 at 8 08 18 pm](https://cloud.githubusercontent.com/assets/284476/5930648/463cbfe4-a660-11e4-81c6-0f6ee06d61f6.png)

When I uncomment that line, everything works but when it is active then `cssnext` fails with almost no help:

```
ERROR in ./~/css-loader!./~/cssnext-loader!./lib/index.css
TypeError: Cannot call method 'indexOf' of undefined
```

Other `@import`s work just fine. For instance if I move *up* one dependency closer to my project there is this `index.css` file with:
```
/*@import 'suitcss-base';*/
@import 'suitcss-components-button';
@import 'suitcss-utils-text';
```

As you can see I can import other `suitcss` packages just fine.

@necolas @MoOx Let me know any ideas you have about this.

@sokra How can I get a more useful error message from the build, even a stack trace please!

**Comment by jasonkuhrt** [comment]
Oph, I've narrowed the problem space down further and I don't think it actually is an `@import` issue anymore.

If I comment out these lines from `normalize.css`:
- 213 https://github.com/necolas/normalize.css/blob/master/normalize.css#L213
- 336 https://github.com/necolas/normalize.css/blob/master/normalize.css#L336
- 359-360 https://github.com/necolas/normalize.css/blob/master/normalize.css#L359-360

Then `webpack` will compile fine.

The only pattern I see is that all lines point to a `box-sizing` rule *or* variant. @ai does this make any sense to you?

Once I understand better what's going on I will close and move to the appropriate repo.

**Comment by jasonkuhrt** [comment]
Just for my own sanity at the moment I'm going to keep posting my bug tracking results here even though now I'm certain they have nothing to do with `postcss-import`. I am able to force the original error at will be simply doing this:

```css
hr {
  -moz-box-sizing: content-box;
  box-sizing: content-box;
}
```
Note that NONE of these cause the error:
```css
hr {
  /*-moz-box-sizing: content-box;*/
  box-sizing: content-box;
}
```
```css
hr {
  box-sizing: content-box;
  -moz-box-sizing: content-box;
}
```
```css
hr {
  /* box-sizing: content-box; */
  -moz-box-sizing: content-box;
}
```

Based on this I've revisited the error-inducing lines in `normalize.css` and it turns out that actually `336` is OK so its just these two lines that cause the error:

- https://github.com/necolas/normalize.css/blob/master/normalize.css#L213
- https://github.com/necolas/normalize.css/blob/master/normalize.css#L359-360

**Comment by jasonkuhrt** [comment]
I have narrowed the bug down to this line:

```
https://github.com/postcss/autoprefixer-core/blob/master/lib/processor.coffee#L75
```

@ai `decl.before` is `undefined` causing this error at `webpack` compile time:

```
ERROR in ./~/css-loader!./~/cssnext-loader!./lib/index.css
TypeError: Cannot call method 'indexOf' of undefined
```

And once again the pattern that causes it is:

```css
hr {
  -moz-box-sizing: content-box;
  box-sizing: content-box;
}
```

I will try to create a failing test case soon.

**Comment by jasonkuhrt** [comment]
I've created a reproduction in isolation:

```js
var path = require('path')
var fs = require('fs')
var postcss = require('postcss')
var postcssImport = require('postcss-import')
var ap = require('autoprefixer-core')

var microlang = postcss()
                .use(postcssImport())
                .use(ap())

console.log(microlang.process(fs.readFileSync(path.join(__dirname, './a.css'))).css)
```

```
⧑ node index.js

/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/autoprefixer-core/lib/processor.coffee:125
              if (decl.before.indexOf("\n") > -1) {
                              ^
TypeError: Cannot call method 'indexOf' of undefined
  at /Users/jasonkuhrt/projects/find-indexof-bug/node_modules/autoprefixer-core/lib/processor.coffee:75:46
  at /Users/jasonkuhrt/projects/find-indexof-bug/node_modules/postcss/lib/container.js:190:28
  at /Users/jasonkuhrt/projects/find-indexof-bug/node_modules/postcss/lib/container.js:155:24
  at Rule.each (/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/postcss/lib/container.js:128:20)
  at Rule.eachInside (/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/postcss/lib/container.js:154:21)
  at /Users/jasonkuhrt/projects/find-indexof-bug/node_modules/postcss/lib/container.js:158:28
  at Root.each (/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/postcss/lib/container.js:128:20)
  at Root.eachInside (/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/postcss/lib/container.js:154:21)
  at Root.eachDecl (/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/postcss/lib/container.js:188:23)
  at Processor.remove (/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/autoprefixer-core/lib/processor.coffee:64:9)
  at Autoprefixer.postcss (/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/autoprefixer-core/lib/autoprefixer.coffee:51:24)
  at Array.1 (/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/autoprefixer-core/lib/autoprefixer.coffee:4:61)
  at PostCSS.process (/Users/jasonkuhrt/projects/find-indexof-bug/node_modules/postcss/lib/postcss.js:60:41)
  at Object.<anonymous> (/Users/jasonkuhrt/projects/find-indexof-bug/index.js:11:23)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```
`FS`:
```
b/index.css
a.css
```
***a.css***
```css
@import 'b'
```
***b.css***
```css
* {
  -moz-box-sizing: content-box;
  box-sizing: content-box;
}
```

Last thing I need to do is find out where the responsibility of the error lies. @ai @MoOx I think its going to fall down to one of you.

**Comment by MoOx** [comment]
Closing this, since your reported a fix to autoprefixer https://github.com/postcss/autoprefixer-core/pull/31
But I'm guessing the appropriate issue is this one https://github.com/postcss/postcss/issues/171

**Comment by lsdafjklsd** [comment]
I'm getting this error on a few of my CSS files when running `webpack -p`, something about uglifying the CSS. I followed this thread but don't quite understand the solution. Does this error look like it's the same thing? There are no errors when running `webpack-dev-server` only.

```
ERROR in ./~/css-loader!./~/cssnext-loader!./app/styles/index.css
TypeError: Cannot call method 'indexOf' of undefined
```

**Comment by MoOx** [comment]
So that's totally not a postcss-import issue. Probably a cssnano issue since css-loader compress with cssnano.

**Comment by lsdafjklsd** [comment]
Awesome, thanks for nudging me in the right direction! :)
