### ISSUE TITLE
issue using resolve.alias's (webpack)

### ISSUE THREAD

**Issue by cj** [postcss/postcss-import#190]
I original thought it might be something with `css-loader` https://github.com/webpack/css-loader/issues/49 (http://prntscr.com/afub2r) but it turns out if I remove `postcss-loader` I don't get the error, the resolve.alias works and finds the file.

**Comment by MoOx** [comment]
Please provide more information like some CSS (input and expected output), and your postcss configuration. And maybe your webpack config too (even if that's not our problem here).

**Comment by RyanZim** [comment]
Since there is no response, I am closing.

**Comment by FezVrasta** [comment]
Does someone have a solution to this problem?

The problem is easily reproducible:

```
/src/foo/bar.css
/src/fooz/faz.css
```

```
// foo/bar.css
@import 'src/fooz/faz.css'
```

```
// webpack config
[...]
resolve: {
  alias: {
    src: './src',
  },
},
[...]
```

```
Module build failed: Error: ENOENT: no such file or directory, open '~/project/src/fooz/faz.css'
 @ ./src/foo/bar.css
```

**Comment by RyanZim** [comment]
@FezVrasta I'm no expert on webpack, but postcss-import doesn't rely on webpack's settings for module resolution. (postcss-import doesn't even know if it's running in a webpack stack or not.)

If I understand the webpack docs for `resolve.alias` correctly, the postcss-import equivalent would be [`path`](https://github.com/postcss/postcss-import#path). Hope this helps!

**Comment by FezVrasta** [comment]
I hardly believe postcss-import does not know about webpack, because I can use the aliases I set in webpack. It would be kinda magic if it worked without reading the webpack config otherwise 🤔

**Comment by RyanZim** [comment]
@FezVrasta Weird; I'm not sure what all magic webpack might be doing under the hood. Here's the code that does the module resolving, if you care to read it: https://github.com/postcss/postcss-import/blob/master/lib/resolve-id.js. BTW, I assume you're using the latest version (v9.1.0) of postcss-import.

**Comment by pgmanutd** [comment]
May be [enhanced-resolve](https://www.npmjs.com/package/enhanced-resolve) can help.

Your ***postcss.config.js*** can be like this:
```
'use strict';

const path = require('path');
const ResolverFactory = require('enhanced-resolve/lib/ResolverFactory');
const NodeJsInputFileSystem = require('enhanced-resolve/lib/NodeJsInputFileSystem');
const CachedInputFileSystem = require('enhanced-resolve/lib/CachedInputFileSystem');

const CACHED_DURATION = 60000;
const fileSystem = new CachedInputFileSystem(new NodeJsInputFileSystem(), CACHED_DURATION);

const resolver = ResolverFactory.createResolver({
  alias: {
    '@blabla': path.resolve(__dirname, 'src')
  },
  extensions: ['.css'],
  modules: ['src', 'node_modules'],
  useSyncFileSystemCalls: true,
  fileSystem
});

module.exports = {
  plugins: {
    'postcss-import': {
      resolve(id, basedir) {
        return resolver.resolveSync({}, basedir, id);
      }
    }
  },
};
```

**Comment by aunz** [comment]
I had the same problem with alias as well. On top of the solution offered by @pgmanutd 🙏, below is my solution:
```js


const path = require('path')

/* version 1 */
module.exports = {
  plugins: {
    'postcss-import': {
      resolve(id, basedir) {
        // resolve alias @blabla, @import '@blahbla/style.css'
        if (/^@blabla/.test(id)) return path.resolve('./pathToBlah', id.slice(8)) // because @blabla/ has 8 chars

        // resolve node_modules, @import '~normalize.css/normalize.css', similar to how css-loader's handling of node_modules
        if (/^~/.test(id)) return path.resolve('./node_modules', id)

        // resolve relative path, @import './components/style.css'
        return path.resolve(basedir, id)
      }
    }
  }
}


/* version 2 */
module.exports = {
  plugins: {
    'postcss-import': {
      resolve(id, basedir) {
        // resolve alias @blabla, @import '@blahbla/style.css'; same as version 1
        if (/^@blabla/.test(id)) return path.resolve('./pathToBlah', id.slice(8))

        // resolve relative path, @import './components/style.css'; prefix with './' or '../'
        if (/^\./.test(id)) return path.resolve(basedir, id)

        // resolve node_modules, @import 'normalize.css/normalize.css'
        return path.resolve('./node_modules', id)
      }
    }
  },
};


```
