### ISSUE TITLE
Not all files are imported

### ISSUE THREAD

**Issue by koistya** [postcss/postcss-import#191]
Some files (one or many) are not being included into the output CSS, depending where in the code have you placed your `@import 'filename.css';` statements. For example:

```css
@import 'normalize.css'; // skipped
@import 'header.css';    // imported OK
@import 'footer.css';    // imported OK
```

```css
@import 'header.css';    // skipped
@import 'footer.css';    // imported OK
@import 'normalize.css'; // imported OK
```

Using `postcss v5.0.19`, `postcss-import v8.0.2`, `Windows OS`.

**Comment by MoOx** [comment]
Maybe related to #168.
Can you try with v7.x please?
@TrySound any idea?

**Comment by koistya** [comment]
Just figured out, if all `@import` statements located at the top of the file, they seem to be working.

**Comment by MoOx** [comment]
It's a breaking change to follow CSS specification of v8. You have probably a message in postcss message registry that you should read with postcss-reporter or similar.
I will add a note in the CHANGELOG.
