### ISSUE TITLE
import relative or absolute path error

### ISSUE THREAD

**Issue by yreenchan** [postcss/postcss-import#196]
I use the plugin today, and set the param of root or path like below, but it doesn't work.
```
atImport({root: './src/', path: './src/'})
```
I review the code in postcss-import/index.js, and I think the problem is because of "base". 
```
function resolveImportId(
  result,
  stmt,
  options,
  state
) {
  var atRule = stmt.node
  var base = atRule.source && atRule.source.input && atRule.source.input.file
    ? path.dirname(atRule.source.input.file)
    : options.root
}
```
so I add some code below the variable of the base defined;
```
if (!/^\./.test(stmt.uri) && options.root) { // when uri is not relative path, get the path with root
    base = options.root;
}
```
Now, that's work. I just set the root path and I can import css like the code below
config
```
atImport({root: './src/', path: './src/'})
```
index.css
```
@import "public/css/base.css";
@import "../../public/css/dialog.css";
@import "./article.css";
```

**Comment by MoOx** [comment]
The base is by default the current file path, because it's the default behavior in browser.
Please provide more info about your files tree.

**Comment by yreenchan** [comment]
@MoOx 
```
public
	css
		base.css
tpl
	hot
		css
			index.css
		index.html
```

**Comment by yreenchan** [comment]
@MoOx 
I know what I got error in my project;
I didn't add the property of from.
```
process(css, {from: cssPath})
```
so the plugin can't get the file path
