### ISSUE TITLE
Error: ENOENT: no such file or directory for imports Sugarss

### ISSUE THREAD

**Issue by codetony25** [postcss/postcss-import#197]
Hello, i've been getting this message that I cannot import "Error: ENOENT: no such file" when trying to import. I may have the order of my postcss plugins wrong but here is my configuration in webpack:

Importing:
```
import sugarss from 'sugarss'
```

For the loader:
```
webpackConfig.module.loaders.push(
  {
    test   : /\.sss$/,
    include: config.appPath,
    loaders: [
      'style',
      'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
      'postcss',
    ],
  }
)
```
For the postcss plugins:
```
webpackConfig.postcss = () => {
  return [
    atImport({
      addDependencyTo: webpack,
    }),
    sugarss,
    webpackPostcssTools.prependTildesToImports,
    customProperties({
      variables: map.vars,
    }),
    customMedia({
      extensions: map.media,
    }),
    customSelectors({
      extensions: map.selector,
    }),
    cssnext,
    normalize,
    mixin,
    rucksack,
    sorting,
    short,
  ]
}
```

How i'm importing in the css:
```
@import "./colors.sss"
@import "./fonts.sss"
```

It may be worth mentioning that I didn't have these errors before just using it without sugarss. I am trying to use it now.

**Comment by MoOx** [comment]
Are your file relative to the one that import those?

**Comment by MoOx** [comment]
Note that cssnext include customProperties, customMedia and customSelectors, so you should pass option over there http://cssnext.io/usage/#features

**Comment by MoOx** [comment]
Also, this seems useless `webpackPostcssTools.prependTildesToImports,` since postcss-import is supposed to handle those import statments.

**Comment by codetony25** [comment]
To answer your first question, yes it is located in the same folder. So right now my folder structure is like this:

```
- src
  - styles
    - base.sss
    - colors.sss
    - fonts.sss
- webpack
 - webpack.config.js
```

The "webpackPostcssTools.prependTildesToImports" was used to find my base.css. I should of mentioned this earlier. This is declared on top:

```
const map = webpackPostcssTools.makeVarMap(path.join(__dirname +  '../src/styles/base.sss')
```

That was used so that I can use the variables I had declared in fonts.sss and colors.sss globally. However I will look more into the CSSNext options. Before I was everything worked just fine with all my style file extensions being *.css files and the only thing that changed this time is that I just added the import for the sugarss and put sugarss as one of the plugins, and changed the loader to look for .sss instead of .css instead.

Then I experimented a little bit and removed the import statements to see if it would just work without them, and then this error would show in my terminal:

```
        if (this.error) throw this.error;
                        ^
CssSyntaxError: <css input>:8:3: Unknown word
```

So this could mean that the sugarss syntax is not even parsing the styles. I am also not sure if I have the postcss plugins in the correct order.

If you would like to see the full code I have a branch opened up here: https://github.com/codetony25/react-starter-boilerplate/tree/sssyntax/webpack

Thank you for your prompt response by the way! And sorry for the mouthful :o

**Comment by MoOx** [comment]
I think you will need to use sugarss plugin before postcss-import AND in postcss-import `plugins` option.
That said, I am not sure how you can send the syntax via postcss-loader poke @ai.

**Comment by eugene1g** [comment]
FYI I got a similar error, and the same breakage, after switching from 8.1.0 to 8.1.1 - but using plain CSS. Switching back to 8.1.0 resolves the problem.

I have not yet narrowed it down. I suspect pkg-resolve includes jspm which may be hijacking standard require() calls. Will test & report.

**Comment by MoOx** [comment]
8.1.1 has been released yesterday, after this issue was open in the first place.

**Comment by eugene1g** [comment]
I can't reproduce this by using postcss-import direclty in a minimal setup. So my problem lies somewhere higher in the build stack - babel/webpack paths and it's exactly as #207. The build still works with 8.1.0 but breaks with 8.1.1, so I'll have to stay behind until I dig deeper....

**Comment by Kovensky** [comment]
sugarss is not a plugin, it's a syntax (parser+stringifier).

Since you want to produce CSS, you should give it as the `parser` (`syntax` will output sugarss back, which cost me some 20min a few days ago...):

```js
webpackConfig.postcss = () => {
  return {
    plugins: [
      atImport(...),
      cssnext(...),
      ...
    ],
    parser: sugarss
  }
}
```

**Comment by MoOx** [comment]
@Kovensky thanks for the clarification.
