### ISSUE TITLE
Breaks indentation

### ISSUE THREAD

**Issue by iamvdo** [postcss/postcss-import#20]
Using `postcss@4.0.0` and `postcss-import@5.0.0`, indentation is no longer preserved. It used to work with  `postcss@3.0.0` and `postcss-import@4.0.0`.

It seems that `decl` no longer contains `before`, `after` and `between` properties.

**Comment by MoOx** [comment]
Postcss bug about insertBefore behavior. Already open.

**Comment by iamvdo** [comment]
I read about this bug (postcss/postcss#171 ?), but I thought you found a solution since you've released 5.0.0.

So, is this a bug or a feature in postcss 4 ?

**Comment by MoOx** [comment]
Whitespace is not a big deal. Rules are rules. That's why I've released 5.0.

To me it's just a bug. Or bad design. "insertBefore/After" should not do a clone but a move. That's why I opened the issue https://github.com/postcss/postcss/issues/171
