### ISSUE TITLE
@media in element problem

### ISSUE THREAD

**Issue by xowei** [postcss/postcss-import#201]
I type this:
```
ul {
  width: 100%;
  @media (--screen1200) {
    width: 12em;
  }
}
```
results to:
```
ul {width: 100%}
@media (min-width: 1200px){width:12em;}
```

I like to get this result:
```
ul {
  width: 100%;
}

@media (max-width: 50rem) {
  ul {
    width: 12em;
  }
}
```

**Comment by MoOx** [comment]
You probably need to use postcss-nesting
That said, this plugin should not be responsible of this change.
Can you send your entire postcss config?

**Comment by xowei** [comment]
@MoOx Did you mean this one?
This is my postcss plugins In my gulp file.
```
  var processors = [
    require('postcss-import'),
    require('css-mqpacker')({ sort: true }),
    require('lost'),
    require('postcss-cssnext')({
      browsers: ['IE 9', 'last 5 versions', 'Firefox 14', 'Opera 11.1']
    }),
    require('postcss-size'),
    require('precss'),
    require('rucksack-css')
  ];
```

I use **postcss-import** just want to get rid of node_modules path.

**Comment by MoOx** [comment]
Can you try to remove css-mqpacker to see if there is any difference?

**Comment by xowei** [comment]
It worked!
But i'm not sure that is css-mqpacker plugin bug or not.
I think i need to tell css-mqpacker developer.
Thank you!

**Comment by MoOx** [comment]
**postcss-import needs to be used before all others plugins**, otherwise, no transfo in those plugins...
css-mqpacker is not a good idea at all, because it can introduce bugs in your css (because you change the order of the original css)... GZIP handle the same thing pretty easily, mqpaker is a waste of time.

**Comment by xowei** [comment]
@MoOx  I see, i'll get rid of mqpacker, thank you.
