### ISSUE TITLE
Blank lines get removed

### ISSUE THREAD

**Issue by mehcode** [postcss/postcss-import#206]
Is there a way to stop blank lines from being removed in the output?

**Comment by MoOx** [comment]
That's more a PostCSS issue. In the past I was using ugly hack to preserve original user input but during recent refactor, we removed those artifacts.

**Comment by bb010g** [comment]
Are there plans to fix this in a better manner at the PostCSS level?

**Comment by MoOx** [comment]
poke the postcss core team. You should open an issue in postcss repo

**Comment by bb010g** [comment]
I would, but I don't know what your hack was or what they'd need to fix.

**Comment by RyanZim** [comment]
Revalent postcss issue: https://github.com/postcss/postcss/issues/364.

**Comment by RyanZim** [comment]
Going to close this since this is a postcss issue, follow https://github.com/postcss/postcss/issues/364 for updates on this getting fixed.

**Comment by bb010g** [comment]
Just got fixed on postcss's side (details in the issue).

**Comment by RyanZim** [comment]
Fixed in postcss-import v10
