### ISSUE TITLE
Resolving "like a module" using postcss-import

### ISSUE THREAD

**Issue by paulyoung** [postcss/postcss-import#209]
We're using the feature [css-loader](https://github.com/webpack/css-loader) feature described in https://github.com/webpack/css-loader/issues/12#issuecomment-41940311 to allow `@imports` to be resolved "like a module" by prefixing them with `~`.

For example:

```css
@import "../../node_modules/normalize.css/normalize.css";
```

is instead written as:

```css
@import "~normalize.css/normalize.css"
```

This stops working when using `postcss-import`. Is there a way to allow this to continue to work?

**Comment by MoOx** [comment]
postcss-import already handle node_modules.
You can do

```css
@import "normalize.css"
```

This will inline CSS so css-loader won't see any imports after you use this plugin.

**Comment by paulyoung** [comment]
Thanks! In our case we are importing specific files so all I needed to do was change:

```css
@import "~foo/bar.css";
```

to:

```css
@import "foo/bar.css";
```
