### ISSUE TITLE
🚨 ⚠️ Looking for a MAINTAINER ⚠️ 🚨

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-import#210]
Following https://github.com/postcss/postcss-import/pull/169#issuecomment-218397860

**Comment by marcustisater** [comment]
Are we still keeping the repository under org?

**Comment by MoOx** [comment]
It's (I think) a really important piece of the fragile PostCSS ecosystem, so I think it should stay here yes.

**Comment by wc-matteo** [comment]
Coud you elaborate on _fragile_?

**Comment by MoOx** [comment]
Not in this issue to avoid noise :)

**Comment by marcustisater** [comment]
That's not relevant, the repository is **not** transferring ownership. I was just confused of the collab settings, my fault for bringing that up 😞

**Comment by rajzshkr** [comment]
I can help!!

**Comment by zgreen** [comment]
Same.

**Comment by MoOx** [comment]
If people want to help, 2 solutions:

- Investigate a little bit on current opened issues, found dups etc
- Discuss if we should revert to v7 or keep v8

v8 brings some enhancement but since it has been out, the author of the refactor (@TrySound) is completely off the radar and never responded. I don't have much time and can help on v7 since the codebase was still simple.

But I am not alone to decide (I barely use postcss-import in 1 or 2 projects this days)...

Want v7 as a v9?

- git checkout 7.1.3
- git checkout -b 9.0.0
- update CHANGELOG (removed, added back etc)

Most opened issue are related to v8.x.

We will need to explain why this change: mostly because nobody is helping on current version.

If someone want to help on 8.x, start with #168 (and then #169 since there is a breaking test case).

**Comment by simonsmith** [comment]
Would be a shame to lose things like returning a promise from transform in 8.x.

Was 8 a total rewrite as well as new features? Perhaps a starting point might be to list the features to add back and start over from 7.x as the base. I certainly found the latest version difficult to pick though, including the tests.

**Comment by MoOx** [comment]
> Was 8 a total rewrite as well as new features?

yes

**Comment by MoOx** [comment]
@RyanZim fixed the long standing bug #168 so he is now the boss here :)
Hope some others will helps too!

**Comment by NekR** [comment]
Reverted to v7 for now.. Hope some people will find time to handle v8.

**Comment by RyanZim** [comment]
@NekR I am now the maintainer here, trying to fix bugs as fast as I can.

What issue are you encountering?

**Comment by vyorkin** [comment]
I'll try to provide a minimal example repo demonstrating the issue on the weekends (hope I won't forget and have time for this)
