### ISSUE TITLE
Duplicate imports are resolved in the wrong order

### ISSUE THREAD

**Issue by simonsmith** [postcss/postcss-import#211]
Not sure if this title is accurate, feel free to rename.

Given two files:

**componentA.css**

``` css
@import "suitcss-components-button";

.ComponentA {
  color: red;
}
```

**index.css**

``` css
@import "./componentA.css";
@import "suitcss-components-button";
```

I would expect that even though `components-button` is at the bottom in `index` it would see that `componentA` requires it as a dependency and would place the Button CSS above the ComponentA CSS in the final output. This does not happen:

**output

```
.ComponentA {
  color: red;
}
/** @define Button */
// etc
```

If I install `postcss-import@7.1.3` and run the test again the output is as expected, with `components-button` first and the component code after it.

Is this a regression perhaps?

Cheers

**Comment by MoOx** [comment]
Yeah it' s totally a regression. postcss-import v8 have a totally different algo implemented by @TrySound.
You are not the first to have some weird behavior. See #168.

See https://github.com/postcss/postcss-import/pull/169#issuecomment-218397860

**Comment by simonsmith** [comment]
I see. Sounds like resurrecting v7 might be a good idea.

**Comment by 0x80** [comment]
Ran into similar issues. Reverting to v7 solved things.

**Comment by RyanZim** [comment]
Should be fixed in https://github.com/postcss/postcss-import/pull/236. Let me know if otherwise.
