### ISSUE TITLE
Remove JSPM related dep, require it to be installed by the user

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-import#212]
Or more as a peerDep (and require() only if in a jspm context). We need to find a way to import that in a jspm context. Any jspm user can help us about that?
Is `pkg-resolve` really required?

**Comment by koistya** [comment]
This plugin doesn't work on Windows, see: https://github.com/babel/babel-loader/issues/251

**Comment by MoOx** [comment]
PR welcome. We can probably just use the problematic dep as an optional one, should not take that long.

**Comment by RyanZim** [comment]
@MoOx Any reason not to go ahead with making this an optional dep?

**Comment by MoOx** [comment]
No, just time I guess. Go ahead!

**Comment by RyanZim** [comment]
@MoOx Thinking about this more, I'm not sure what this will solve?

> If a dependency can be used, but you would like npm to proceed if it cannot be found or fails to install, then you may put it in the optionalDependencies object. This is a map of package name to version or url, just like the dependencies object. The difference is that build failures do not cause installation to fail.

https://docs.npmjs.com/files/package.json#optionaldependencies

pkg-resolve installs OK, just doesn't run OK with webpack in the mix.

I've got a notion to add a `jspm` option, `false` by default, that enables `require`ing pkg-resolve when it is true. This would be a breaking change, but how many people use jspm?

**Comment by MoOx** [comment]
Probably make sense. I never used jspm so can't really tell :)

**Comment by RyanZim** [comment]
> I never used jspm so can't really tell :)

Me neither!

What do you think of the `jspm` option? Perhaps we could add it, with the default of `true`, and change the default when make the next major.

@guybedford Any advice?

**Comment by RyanZim** [comment]
@MoOx @ai Thoughts on the `jspm` option? The more I think about it, the more I like it.

**Comment by wtgtybhertgeghgtwtg** [comment]
It might be a little extreme, but what if you spun off the `jspm` version into a separate package?  It seems like it's been the root of a lot of trouble.  Also, it would simplify the dependency graph.  Most of the dependencies in `postcss-import` are from 'pkg-resolve', and not by a small amount.
![screencapture-npm-anvaka-1478584478239 - copy](https://cloud.githubusercontent.com/assets/18507762/20088578/68f32aee-a53e-11e6-89f0-ab08b711cb78.png)

**Comment by MoOx** [comment]
What about removing it from dependencies list but keeping the try/catch thing? With proper doc in the README this will be enough to tell people that jspm will work when pkg-resolve is installed...

**Comment by RyanZim** [comment]
> What about removing it from dependencies list but keeping the try/catch thing? With proper doc in the README this will be enough to tell people that jspm will work when pkg-resolve is installed...

I like that idea; it is a breaking change, but sometimes that's needed.

@wtgtybhertgeghgtwtg Nice graph! Where did you get that?

FWIW, here are the sizes of the modules:
```
┌──────────────────────┬──────────────┬────────┐
│ name                 │ children     │ size   │
├──────────────────────┼──────────────┼────────┤
│ pkg-resolve          │ 257          │ 67.47M │ <= !!!
├──────────────────────┼──────────────┼────────┤
│ postcss              │ 11           │ 1.86M  │
├──────────────────────┼──────────────┼────────┤
│ resolve              │ 0            │ 0.46M  │
├──────────────────────┼──────────────┼────────┤
│ promise-each         │ 1            │ 0.05M  │
├──────────────────────┼──────────────┼────────┤
│ postcss-value-parser │ 0            │ 0.05M  │
├──────────────────────┼──────────────┼────────┤
│ read-cache           │ 1            │ 0.04M  │
├──────────────────────┼──────────────┼────────┤
│ object-assign        │ 0            │ 0.02M  │
├──────────────────────┼──────────────┼────────┤
│ 7 modules            │ 253 children │ 59.48M │
└──────────────────────┴──────────────┴────────┘
```

I think that settles it: We will be removing `pkg-resolve` from the deps list.

**Comment by wtgtybhertgeghgtwtg** [comment]
> Nice graph! Where did you get that?

http://npm.anvaka.com/#/view/2d/postcss-import

**Comment by RyanZim** [comment]
PR done: #243.

**Comment by RyanZim** [comment]
Closing as per https://github.com/postcss/postcss-import/pull/243
