### ISSUE TITLE
Angular Cli and Broccoli

### ISSUE THREAD

**Issue by cristianurbano** [postcss/postcss-import#213]
How to integrate with [angular2 cli](https://github.com/angular/angular-cli) (broccoli) ?

**UPDATE:**
[This](https://github.com/angular/angular-cli/issues/634#issuecomment-220831983) works for me

**Comment by cristianurbano** [comment]
This wor

**Comment by ihsansengun** [comment]
https://www.codementor.io/angularjs/tutorial/compiling-sass-postcss-with-angular-cli
