### ISSUE TITLE
[Feature request] Add loaders option

### ISSUE THREAD

**Issue by perrin4869** [postcss/postcss-import#215]
This is the one thing stopping me from switching from sass to postcss right now. I am using a small subset of `bootstrap` right now, and therefore I am importing `sass` files individually from the source of `bootstrap-sass`. It would be very useful to have a syntax such as follows:

```javascript
const sassLoader = { // Could be distributed in a package such as 'postcss-import-loader-sass'
  test: '*.scss',
  loader: (filepath, contents) => sassToPostCss(contents), // TODO: implement
};

postcss()
  .use(atImport({
    loaders: [sassLoader]
  }))
  .process(cssString)
  .then(function (result) {
    var css = result.css
  })
```

I could try to put together a pull request when I get some free time, but I'm not sure when that would be. Thanks!

**Comment by MoOx** [comment]
You can probably already do that using the [transform](https://github.com/postcss/postcss-import#transform) option. I am afraid your proposal is a bit overkill as it's a very limited use case.
Another simpler solution might be to transform scss files first and then import them as raw css.

**Comment by perrin4869** [comment]
The problem with the `transform` option is that it gets only the file content and not the name - so I cannot tell if it is `scss` or normal `css`.
There are many vendor libraries distributing the source written with all kinds of preprocessors. [semantic-ui](http://semantic-ui.com/) looks amazing, yet it is written in `LESS`, which is the reason I did not use it ultimately, since my project was written with `sass`. Having this kind of `loader` option as found in many other libraries would greatly increase the usability of vendor libraries within `sass`, or even allow the usage of older code written with a preprocessor, which is why I do not think it is overkill, but a very natural way to extend `postcss-import`.
The implementation also shouldn't be terribly complicated either, maybe I could put it together and test it in a few hours...

**Comment by perrin4869** [comment]
Also, this would make the `loaders` written reusable, instead of having clients reimplement them again and again within their code.
But at the very last, I think `transform` should get the `filepath` as an argument too, so that the transformation can be properly determined.

**Comment by MoOx** [comment]
transform have multiple arguments, docs seems out of date https://github.com/postcss/postcss-import/blob/8c3230e6767f0ec4b2890ce931a8b974a34c62e4/index.js#L283

**Comment by MoOx** [comment]
Anyway, if you "import" CSS, you should import raw CSS. It make no sense to import Sass or LESS since you won't be able to use variables mixins etc.

**Comment by perrin4869** [comment]
Oh I see. Very good point!

**Comment by perrin4869** [comment]
Well, you could theoretically wrap the scss as follows:

```sass
// bootstrap.sass
/*!
 * This is a subset of the imports found inside "bootstrap-sass@3.3.6/assets/stylesheets/_bootstrap.scss"
 */

// Core variables and mixins
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/variables";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/mixins";

// Reset and dependencies
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/normalize";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/print";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/glyphicons";

// Core CSS
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/grid";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/forms";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/scaffolding";

// Components
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/component-animations";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/dropdowns";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/navs";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/navbar";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/panels";

// Components with javascripts
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/modals";
@import "../jspm_packages/github/twbs/bootstrap-sass@3.3.6/assets/stylesheets/bootstrap/modals";
```

And then import `bootstrap.scss`, and have variables working as expected... I think this is a reasonable enough use-case, no?
