### ISSUE TITLE
Is it me or does this dramatically slow webpack down?

### ISSUE THREAD

**Issue by kevinSuttle** [postcss/postcss-import#217]
Could just be me, but as soon as I started using a couple of plugins, including this one, my Webpack build takes forever, there is no hot reloading, and the browser takes _minutes_ to pick up CSS changes.

**Comment by MoOx** [comment]
It should not.
Please check this option https://github.com/postcss/postcss-import#adddependencyto
Also if you are using v8, please try v7 of this plugin and tell us if there is any change.

**Comment by kevinSuttle** [comment]
@MoOx @kristoferjoseph I've narrowed it down to this plugin and postcss-apply.

Here's my Webpack config:

```js
var path = require('path');
var webpack = require('webpack');
var customProperties = require("postcss-custom-properties");
var cssApply = require('postcss-apply');

module.exports = {
  output: {
    path: ('./_demo'),
    include: '._demo/static/assets/',
  },
  module: {
    loaders: [
     {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        include: [path.resolve(__dirname, '../')],
        loader: 'babel',
        query: {
          presets: ['react', 'es2015'],
          plugins: ['transform-class-properties'],
        },
      },
      { test: /\.css$/, loader: 'style-loader!css-loader!postcss-loader' },
      { test: /\.png$/, loader: 'file-loader' },
      { test: /\.svg$/, loader: 'file-loader' },
    ],
  },
   postcss: function () {
    return [
    require('postcss-import')({
      addDependencyTo: webpack,
    }),
      customProperties(),
      cssApply,
    ]
  },
}
```

**Comment by pascalduez** [comment]
@kevinSuttle No error or usable infos in your term or console? 
Did you try narrowing the plugin list even further? 
Also maybe try to move the apply plugin before the custom properties one.

**Comment by kevinSuttle** [comment]
@pascalduez No errors or usable info :(. I moved the order of the plugins around. I noticed that the apply plugin doesn't hot reload or even manual reload. Perhaps I should open a separate issue there?

**Comment by kevinSuttle** [comment]
@MoOx Do you have a recommendation for dealing with hot reload for this plugin? 

Right now, if say, Buttons.css has an `@import ./vars.css`, and I make a change to vars.css, I have to save it _and_ Buttons.css to see the changes take effect.

**Comment by MoOx** [comment]
This depends on the stuff you use. If you use webpack, read carefully the readme, the response in in there (also, read postcss-loader doc in this case).
