### ISSUE TITLE
It does not pick up changes in import

### ISSUE THREAD

**Issue by slavikse** [postcss/postcss-import#218]
for example: main.css -> @import "test/test.css";
the first execution of all good.
then changing the color: #890 -> #895 in test.css
change plugin does not pick up.
changes only come when writing new rules.

**Comment by MoOx** [comment]
Can you try with v7 of this plugin?

**Comment by slavikse** [comment]
Unfortunately no :(

**Comment by MoOx** [comment]
What is your asset pipeline? Webpack? Gulp?

**Comment by slavikse** [comment]
gulp task:
```
let options = [
  atImport,
  nested,
  media
];

export default () => {
  gulp.task(name, () => {
    return gulp.src(files)
      .pipe(postcss(options))
      .pipe(gulp.dest(there))
  })
}

```

**Comment by MoOx** [comment]
You have to rebuild yourself your entry point when all possible dependencies are updated. It's not a postcss-import issue sorry.

**Comment by slavikse** [comment]
I show the whole problem.
I disabled all plugins.
import is not working properly, as I described above :(
changes are not picked up
```js
const
  name = 'style',
  files = 'source/*.css',
  wFiles = 'source/**/*.css',
  there = 'public';

let options = [
  atImport
];

export default () => {
  watch(name, wFiles);

  gulp.task(name, () => {
    return gulp.src(files)
      .pipe(plumber({errorHandler: notify}))
      .pipe(postcss(options))
      .pipe(gulp.dest(there))
  })
}

main.css
@import "test/test.css";

test.css
.test {
  color: #815; // changing to 810. changes are not picked up :( what's the problem?
  font-size: 10px; // add a new rule changes are picked up
}
```

**Comment by MoOx** [comment]
Sorry I don't know gulp enough. Try asking people that works with gulp, not sure what is the best place for this.

**Comment by slavikse** [comment]
well thank you
