### ISSUE TITLE
Dependency chain vulnerability

### ISSUE THREAD

**Issue by stevensacks** [postcss/postcss-import#219]
```
├─┬ postcss-import@8.1.2
│ ├─┬ pkg-resolve@0.1.14
│ │ └─┬ jspm@0.17.0-beta.21
│ │   ├─┬ sane@1.3.4
│ │   │ ├─┬ minimatch@0.2.14
```

Minimatch has a strong warning that pre-version 3 has a vulnerability to DoS attacks.

**Comment by MoOx** [comment]
Like you can see in the tree you posted, this is an issue related to a dep. Please open the issue overthere.
Anyway, pkg-resolve is going to be removed, see #212. Also #211 and #210.
