### ISSUE TITLE
TypeError: Cannot read property 'before' of undefined

### ISSUE THREAD

**Issue by iamvdo** [postcss/postcss-import#22]
With this CSS:

```css
@import url(http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic);
```

The error occurs on `first.before = "\n\n" + first.before`  from `index.js:112`

Same error using postcss-import v4 with postcss v3.

Related: iamvdo/pleeease#40

**Comment by MoOx** [comment]
Released as 5.0.1

**Comment by rudeworks** [comment]
I just upgraded to PostCSS 5.0.1 and this error started appearing again.

**Comment by ai** [comment]
Seems like it happens because of `postcss.parse` in plugin. Your plugin uses different PostCSS version, rather than runner. So it will parse nodes in old AST.

**Comment by rudeworks** [comment]
dude @ai you have eyes everywhere, wha...
