### ISSUE TITLE
Duplicated @imports within imported style sheets throw warnings, break

### ISSUE THREAD

**Issue by jasongonzales23** [postcss/postcss-import#221]
This may be a duplicate, but still documenting in case it is helpful.

I have my css broken into very small components. For this particular error here is what is happening:

I have

```
vars/colors.css
vars/global.css
textInput.css
buttons.css
```

Both textInput.css and buttons.css import colors.css and global.css

In a form component I have

```
@import 'textInput.css'
@import 'buttons.css'
```

which gives me the following warnings:

```
WARNING in ./~/css-loader?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/forms/forms.css
postcss-custom-properties: /Users/jasongonzales/work/src/styles/variables/colors.css:5:3: Custom property ignored: not scoped to the top-level :root eleme
nt (:root { ... --lightest-grey: ... }), in atrule
```

... and later in the cascade of warnings

```
WARNING in ./~/css-loader?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/forms/forms.css
postcss-custom-properties: /Users/jasongonzales/work/src/styles/textInput.css:19:5: variable '--light-blue' is undefined and used without a fallback
```

and then none of the styles are applied.

If I only import textInput.css or buttons.css all styles are applied.

**Comment by MoOx** [comment]
The warning are related to postcss-custom-properties. Did you include a file in a media query or something?
Otherwise, can you try v7 of this plugin? (v8 have some issues).

**Comment by jasongonzales23** [comment]
Hello @MoOx! Thanks for the reply. I tried V7 to no avail! Also, the include was not in a media query. I think I represented as clearly as possible the issue the scenario above, but let me know if you need further clarification. My workaround for now, is to put the textInput.css and button.css in the same file so that I don't call colors.css and global.css twice in the form.css.

**Comment by kevinSuttle** [comment]
I'm having a similar issue.

```
../../Themes/One.css
../../Themes/Two.css
../../Themes/Index.css
```

In Index.css:
```
@import "One.css";
```

In subsequent files:
```
./src/Component/Component.css
```
```
@import "../Themes/Index.css";
```

_[All hell breaks loose]_

I tried throwing the options in, but the differences between `root`, `path`, and `resolve` are confusing to me.

**Comment by MoOx** [comment]
Using v7, you can call the same files multiples times, but won't have it included multiples times. If you have issues, please show stack traces and your file tree.

**Comment by kevinSuttle** [comment]
Relevant: https://github.com/postcss/postcss-custom-properties/issues/50

**Comment by MoOx** [comment]
> [All hell breaks loose]

Can you post the version of postcss-import used and full stack trace?

**Comment by kevinSuttle** [comment]
`"postcss-import": "^8.1.2"`

Output, based on the structure above: https://github.com/postcss/postcss-import/issues/221#issuecomment-231865571
```
Cannot find module "-!./../../node_modules/css-loader/index.js!./One.css"
Error: Cannot find module "-!./../../node_modules/css-loader/index.js!./One.css"
    at webpackMissingModule (webpack:///src/Inputs/Input.css:3:75)
    at eval (webpack:///src/Inputs/Input.css:3:211)
    at Object.<anonymous> (webpack:///./src/Inputs/Input.css?426b:1063:2)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:556:30)
    at fn (http://localhost:9001/static/preview.bundle.js:87:20)
    at eval (http://localhost:9001/static/preview.bundle.js:2972:2)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:2972:2)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:556:30)
    at fn (http://localhost:9001/static/preview.bundle.js:87:20)
    at eval (http://localhost:9001/static/preview.bundle.js:817:2)
```

**Comment by kevinSuttle** [comment]
@MoOx Hope that helps.

**Comment by kevinSuttle** [comment]
Switching to `postcss-import@7.1.3` fixes this for me.

**Comment by MoOx** [comment]
@kevinSuttle fyi, in your first stack trace, postcss-import is clearly not responsible since the stack trace is a webpack stack trace, not a postcss-import stack trace that should show the place where it's looking for https://github.com/postcss/postcss-import/blob/master/lib/resolve-id.js#L61-L66

Also the reference to `webpack` in your postcss function is incorrect. Please read the postcss-loader carefully.

**Comment by kevinSuttle** [comment]
I wonder why this is true though.
> Switching to postcss-import@7.1.3 fixes this for me.

**Comment by MoOx** [comment]
You probably changed something else.

**Comment by RyanZim** [comment]
@jasongonzales23 Is this still an issue with the latest version?

**Comment by jasongonzales23** [comment]
@RyanZim , I am sorry to say I can't validate. I've moved on to another approach for component-izing css.

**Comment by RyanZim** [comment]
Gonna close this, open a new issue if you have this problem.
