### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by laszlokorte** [postcss/postcss-import#232]
I tried to use postcss-import but I forgot to write the semicolon at the end of the import line:

```
@import "foo.css"
```
instead of 
```
@import "foo.css";
```

As a result I got this error message:
> TypeError: Cannot read property 'length' of undefined
    at module.exports (/xxxxx/node_modules/postcss-import/lib/join-media.js:2:40)

Which made me spend half an hour searching for the bug I assumed to be in postcss.

Would be nice if the error message could be improved.

**Comment by MoOx** [comment]
Dup of #223. It's a postcss 5.1 regression. Can probably be fixed in this lib. PR welcome.
