### ISSUE TITLE
Add dependency message

### ISSUE THREAD

**Issue by ai** [postcss/postcss-import#233]
New `postcss-loader` will support `dependency` message to notify webpack about imports. So we need to add few lines on every import:

``` js
result.messages.push({
  type: 'dependency',
  file: absoluteFilePath
})
```

@MoOx @TrySound write me if you need any help with it.

**Comment by ai** [comment]
Any updates? How I can help with it?

**Comment by MoOx** [comment]
First thing to do is to start again with v7, since nobody helped on the huge concurrency issue related to v8.
Codebase of v8 is far more complicated than v7 (and more buggy). 
I don't have lot of time for this - I don't even use postcss-import anymore so...

People said they wanted to help (see #210) but I didn't see any PR :)

Maybe I can handle the revert to v7...

**Comment by longlho** [comment]
Yes it'd be great to switch back to v7 and narrow down the feature set a bit (like `import` in media query). We do use this at Yahoo and I can maybe offer some contribution. (I've been PR-ing to css-modules & css-loader).

**Comment by ai** [comment]
@MoOx you should give a direct order to people who want to help ;). Like “Could you fix this issue? What is ETA?”

**Comment by ai** [comment]
So you need a PR for this issue? In `master`?

**Comment by michael-ciniawsky** [comment]
It would work the same way for CLI usage aswell

```js
result.messages
  .filter((msg) => msg.type === 'dependency' ? msg : '')
  .forEach((dep) => chokidar.add(dep.file))
```

**Comment by ai** [comment]
@MoOx so what help do you need to fix this issue? PR to `master`?

**Comment by troutowicz** [comment]
Had an issue today with HMR not working when using postcss-import 8.1.0 with postcss-loader 1.0.0. The fix suggested by @ai  in https://github.com/postcss/postcss-loader/issues/122 fixed my problem. Looks like the issue discussed here might be the cause?

**Comment by michael-ciniawsky** [comment]
When someone familiar with the codebase can provide a short intro to what to

- is the issue(s) between v7/v8 
- how does `postcss-smart-import` and other solutions handle dependencies atm
- is there a possiblity/interest to 'merge' `postcss-smart-import` and friends i the future, generally speaking, try to focus on **one** solution to handle `@import` s

I, like mentioned in other issue before, can start working on it , but starting point, where to /wht first at best would be helpful and highly appreciated :)

**Comment by MoOx** [comment]
See https://github.com/postcss/postcss-import/issues/210#issuecomment-255721659

**Comment by RyanZim** [comment]
@MoOx @ai Would one of you please tell me what is needs done to get this implemented? I would be willing to submit a PR, but I need to know if `master` is the correct place or if we are reverting to v7 first. :exclamation:

**Comment by michael-ciniawsky** [comment]
@RyanZim  I'm neither @ai nor @MoOx but i8 think it depends on your time and if your are familiar enough with the v8 code base to fix v8 related issues. I8f you not already aware, there is discussion [here](https://github.com/postcss/postcss/issues/906). TLDR; `postcss-smart-import`, which is a basically a fork, working, updated and cleaned up , would be a good starting point

**Comment by RyanZim** [comment]
I'm strapped for time ATM, but wouldn't mind helping/maintaining `postcss-import`. I noticed that issue soon after I posted this, will follow that discussion.

**Comment by RyanZim** [comment]
@ai For postcss-cli, we need:

```js
result.messages.push({
  type: 'dependecy',
  file: absoluteFilePath
  parent: fileContainingTheImport
})
```

Does that sound good to you?

**Comment by ai** [comment]
@RyanZim sounds good (only fix a `dependecy` to `dependency`).

Do you need to add `parent` field to `postcss-assets` and `postcss-inline-svg` too?

**Comment by RyanZim** [comment]
Not ATM.

**Comment by RyanZim** [comment]
@ai Then again, that might be a good idea to add `parent` to other plugins. No rush, though.

Perhaps we should make a `dependency` message spec someplace, so that all plugins implement it the same? Just a crazy idea...

**Comment by ai** [comment]
@RyanZim we could add it to Plugin and Runner guideline. But first I want to stabilize it :D.

**Comment by ai** [comment]
@RyanZim I create a issues in other plugins about `parent` key.

**Comment by RyanZim** [comment]
PR done: #241
