### ISSUE TITLE
v9.0.0 Discussion

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-import#242]
Attention @ai @MoOx @jonathantneal and anyone else who is interested:

As discussed in https://github.com/postcss/postcss-import/issues/212, we will need to make breaking changes to postcss-import in the near future. That means a new major version.

As @MoOx said elsewhere, it's fine to make 3 releases a day if we have to. I agree with that, but that advice does not apply to major versions IMO. I would prefer not to have to make another major version right after this one.

Does anyone have ideas/recommendations for other breaking changes that we should/could make?

If they can be implemented in a reasonable amount of time, I will hold off on the major release so we can ship all the breaking changes together. If not, I will just ship v9 with no other changes than #212.

Feel free to brainstorm; crazy ideas are OK. :smile_cat:

**Comment by michael-ciniawsky** [comment]
This is the code I started 'fresh' with a few days ago. It's very basic atm, e.g `postcss-load-config`, recursive @imports are missing etc. The reason I post it here is, that imo the current code base of postcss-import is/has become way to complicated. No offense to anyone here :), but for comparison. Let's assume e.g recursion could work with that, maybe a few `root`(path) && `node.params` checks here and there and bam! 😛 `@imports` don't even need to be strictly at the top here, though it is advisable and 'standard'.

```js
const { join, resolve, dirname } = require('path')
const { readFile } = require('fs')

const { assign } = Object

const postcss = require('postcss')

function read (file) {
  return new Promise((resolve, reject) => {
    readFile(file, 'utf8', (err, file) => err ? reject(err) : resolve(file))
  })
}

function process (file, $, { options, plugins }, result) {
  return read(file).then((css) => {
    postcss(plugins)
      .process(css, options)
      .then((_import) => {
        return $.replaceWith(_import.root)
      })
      .catch((err) => console.log(err))
  })
}

function PostCSSImport ({ root = __dirname, options = {}, plugins = [] }) {
  return function (tree, result) {
    root = resolve(root)

    plugins = plugins.length === 0 ? result.processor.plugins : plugins

    options = assign(result.opts, options)

    let imports = []

    tree.walkAtRules('import', (_import) => {
      let _file = join(root, _import.params.replace(/"/g, ''))

      imports.push(process(_file, _import, { options, plugins }))

      result.messages.push({ type: 'dependency', file: _file })
    })
    
    return Promise.all(imports)
  }
}

module.exports = postcss.plugin('postcss-import', PostCSSImport)
```

**Comment by RyanZim** [comment]
@michael-ciniawsky I agree the codebase could be simplified a bit. A couple of big things your code misses:

- Recursion
  - Deduping
  - Caching of all files so the same file is never read twice
- Correct handling of `@import url list-of-media-queries;` syntax. (https://developer.mozilla.org/en-US/docs/Web/CSS/@import)
- Loading `@import`s from `node_modules`
- https://github.com/postcss/postcss-import#transform

I'm also not sure if your code handles source-maps correctly, haven't tested.

---

v8 was a total rewrite, and it almost ended in disaster. I'm not going to do another total rewrite in the near future.

PRs simplifying the code (even if it means large refactoring) are welcome; those can be released as patch versions.

Are there any features in the current version that you feel should be removed in interests of simplification?

**Comment by michael-ciniawsky** [comment]
> Recursion && Caching

Nope, but must have ✨ 

> I'm also not sure if your code handles source-maps correctly, haven't tested.

No way 😛 

> Loading @imports from node_modules

`@import "~normailze.css"`

 `~` indicates loading from node_modules/bower_components ? 

> Are there any features in the current version that you feel should be removed in interests of simplification?

rm `onImport`, `transform`, `skipDuplicates as an option`, harmonize `root/path/resolve`

**Comment by RyanZim** [comment]
@michael-ciniawsky If you do `@import "normalize.css";` and you have `normalize.css` installed via npm, and no local file by that name, the npm package will automatically be used.

---

> rm onImport, transform, skipDuplicates as an option

- `onImport` Agree this should be removed sometime. Since `dependency` messages were just added, I'm not sure if it should be removed immediately (thoughts from @MoOx @ai ?). I think I might deprecate it though.
- `transform` I dunno, this might be needed by someone trying to build a higher-level abstraction on top of this. Thoughts @MoOx @ai?
- `skipDuplicates`
  - On one hand, :+1: for removal. (@MoOx do you know why this was added in the first place?)
  - On the other hand, the current implementation only requires two `if` statements, why remove something so simple? This might also come in handy for debugging.

---

> harmonize root/path/resolve

The default resolver is basically an abstraction around [node-resolve](https://github.com/substack/node-resolve). The `resolve` option allows you to substitute your own resolver. `root` is an alias for setting `opts.basedir` for node-resolve. Likewise, `path` is an alias for `opts.paths`.

`resolve` needs to stay IMO.

Regarding `root` and `path`: perhaps they should be moved into a separate `resolveOpts` object (Ref: https://github.com/postcss/postcss-import/issues/195). You would then pass your options like this:

```
{
  resolveOpts: {
    root: '/some/absolute/path'
  }
}
```
(This is just a brainstorm, not sure if I like it)

I've personally never used `path`, perhaps someone can fill me in on how it works.

Perhaps the docs could be improved by splitting the low-level options (like `resolve`) into a separate section.

**Comment by ai** [comment]
My main dream about postcss-import — cover 90% of cases without a configuration.

**Comment by ai** [comment]
Maybe we should enable `skipDuplicates` by default? What is a point to import same documents twice. Also webpack do not have duplicates too :)

**Comment by michael-ciniawsky** [comment]
> The default resolver is basically an abstraction around node-resolve. The resolve option allows you to substitute your own resolver. root is an alias for setting opts.basedir for node-resolve. Likewise, path is an alias for opts.paths.

> resolve needs to stay IMO.

@RyanZim its not about removing resolve, but about how to config it in the simplest way possible, with a sane chrome for messing around with paths/files. Defining a root `basedir`  and resolve it (absolute) 👍 , fallback to `dirname(result.opts.from)` (relative) 👍 . Having 3 options props passing node-resolve options around 👎 .

> opts.paths - require.paths array to use if nothing is found on the normal node_modules recursive walk ----> (probably don't use this) <---- node.resolve README.md

> My main dream about postcss-import — cover 90% of cases without a configuration.

@ai Fuck yeah 👍 😛  `postcss.config.js` located in import directory (optional/advanced) > Fallback to main instance plugins (`result.processor.plugins`) && options (`result.opts`) || `options.plugins` && `options.options` 

(options.plugins + options.options is discussable if you ask the radical me in simplify mode)

>  Maybe we should enable skipDuplicates by default? What is a point to import same documents twice. Also webpack do not have duplicates too :)

:+1:

**Comment by MoOx** [comment]
skipDuplicates should remains imo. In CSS it does not make sense to have a duplicated output, especially with libraries like bootstrap.

**Comment by michael-ciniawsky** [comment]
@MoOx You mean as feature? Sure, but as option ? postcss-import skips them, which already the default, done :). less the read, less to think, less to configure 👍

**Comment by RyanZim** [comment]
> Maybe we should enable skipDuplicates by default?

@ai It is enabled by default. The question is if there is any sane use-case for _not_ skipping duplicates.

---

> My main dream about postcss-import — cover 90% of cases without a configuration.
-- @ai 

:+1: That is the one point we all agree on.

---

@michael-ciniawsky I don't get the point of `~`.

Think about it: how many npm package names end in `.css`? `normalize.css` is the only one I can think of. I would say the collision probability is very low. Not to mention, that would just complicate the resolver. If someone opens an issue here complaining about a collision, we might implement something there; for the time being, let's just leave that as it is IMO.

---

Does anyone know why the `path` option was added? Is anyone using it? Can anyone give a concrete use-case for it? If the answer to all these questions is no, I think we have a case for removing it.

I would sooner add `moduleDirectories` as per https://github.com/postcss/postcss-import/issues/195. (This is debatable; do the debate somewhere else, this thread is getting long enough :wink: )

**Comment by RyanZim** [comment]
Should also add: let's keep this discussion primarily limited to semver-major changes.

Remember: the reason we are talking about v9 is that we need to fix a bug in a backwards-incompatible way. I would like to get this shipped ASAP. I plan on opening another discussion issue after v9 is shipped.

**Comment by michael-ciniawsky** [comment]
> I don't get the point of ~. ....

@RyanZim Discard it then :) it's not really important. For all that `path`, `root`, `resolve` stuff

```js
const options = {
   root: 'path/to/imports',
   relative: true || false // default => true
}
```

When relative is set `true` it joins the root with result.opts.from

```js
path.join( path.resolve( path.dirname(result.opts.from), root) )
```

otherwise just resolve the `root`

**Comment by michael-ciniawsky** [comment]
```css
@import "lib/bootstrap.css"

@import "styles/button.sss"
...
```

```js
const parser = require('postcss').parse
....                                                                         
path.extname(node.params.source) !== 'css' ? parser = result.opts.parser : parser 
...
```

**Comment by RyanZim** [comment]
Regarding `relative` option, etc:

There are so many ways to do this. I'm about tired of all this bikeshedding. :bike: @ai Perhaps you can make a final decision on this.

---

Regarding custom parsers:

That's a known issue. It's partially related to PR https://github.com/postcss/postcss-import/pull/204. I'm not sure if I like that approach, though.

I can't think of a single reason in the world someone would use this plugin with LESS or SCSS parsers/syntaxes. They both have `@import` capabilities (neither are fully compatible with `postcss-import` IIRC). Therefore, I would move to _not_ attempt to explicitly support them.

Since SugarSS is little more than an indent-based css, I think we should attempt to support it. I was thinking along the lines of adding a `sugarss` option sometime after v9 that would use the SugarSS if the extension was `.sss` (regardless of whether it was imported from `node_modules` or not). I thought I would make it an option (not enabled by default) in interests of being spec-compliant, but I'm open to making that functionality default if there is consensus for that.

Are there any other custom parsers that I don't know about (other than postcss-safe-parser)?

**Comment by michael-ciniawsky** [comment]
> There are so many ways to do this. I'm about tired of all this bikeshedding. 🚲

Was not meant to be bikeshedding :), maybe the example was misleading, what I was trying to express, was having one way with absolute @import paths (options.root) and one with relative @import paths (options.relative => result.opts.from). Implementation details => You're are the boss 😛 forget the path.yxz stuff.

> Regarding custom parsers

Why not using the parser instance of the main instance via `result.opts.parser`when file extension !== `.css`? Currently there is mainly SugarSS true, but who knows what might be coming in the future? That way it's not a `postcss-import` concern and no extra 'bloat'.

**Comment by RyanZim** [comment]
> Why not using the parser instance of the main instance via result.opts.parserwhen file extension !== .css?

That's a pretty good idea.

This could break down if another custom parser (we'll call it xyzCSS) would become popular. Then if a `.sss` file imports an `.xyz` file, you would get the wrong parser. However, SugarSS is the only popular parser ATM, so let's just worry about that later. :grinning: 

Should we handle custom syntaxes the same way? I'd be fine with it.

---

@michael-ciniawsky No insult mean by the word "bikeshedding". You have some good ideas, I'm not sure if I agree on all of them, but I appreciate good discussion.

I have a slight case of [Analysis Paralysis](https://en.wikipedia.org/wiki/Analysis_paralysis) about resolving options. I'd prefer to leave the decision to @ai.

**Comment by ai** [comment]
I don’t like too many options. So I am not big fan of `relative` option. In npm and Sass, they don’t need it. Maybe we should use same behavior:

```css
@import 'lib/bootstrap.css'; /* global */
@import './style/button.css'; /* relative */
```

**Comment by ai** [comment]
BTW, `.sss` is not the only parser. Some developers use `postcss-scss` to import `.scss` files. Of course, they don’t have Sass commands there, they use `.scss` for `// inline` comments.

**Comment by RyanZim** [comment]
> ```
@import 'lib/bootstrap.css'; /* global */
@import './style/button.css'; /* relative */
```

@ai That's pretty well how postcss-import works, except (in an effort to be a bit more spec-compliant), the `./` is optional for relative imports. I really don't feel like changing this ATM since it would break a lot of code that was working perfectly fine. I do think we should encourage the use of `./` for relative imports. I always use `./`, and it would be easy to update the docs.

Unless someone has strong feelings otherwise, I move to leave path resolving as it currently stands for lack of consensus (and lack of time to reach consensus before the next major version).

---

> BTW, .sss is not the only parser. Some developers use postcss-scss to import .scss files. Of course, they don’t have Sass commands there, they use .scss for // inline comments.

True, hadn't thought about the fact that some developers would use the SCSS parser just for `//` comments. @ai Do you think that there are any developers mixing SugarSS and SCSS in the same project?

**Comment by ai** [comment]
@RyanZim technically, it is possible (for example, legacy code). But not common.

What problem do we have with auto-switching parser according file extension? (sorry, maybe I miss it above)

**Comment by RyanZim** [comment]
> What problem do we have with auto-switching parser according file extension?

There is no problem with that. Will try a PR when I get a chance.

> technically, it is possible (for example, legacy code). But not common.

Not sure what you're referring to here. Mind clarifying what you mean by "it"?

**Comment by ai** [comment]
@RyanZim it = having SugarSS and SCSS sources in one project.

**Comment by RyanZim** [comment]
That's what I thought, just wanted to clarify.

I think this gives us some things to work on for v9. I will be submitting PRs for the various things discussed here. If they are matters of debate, a decision can be made via discussion on the PR thread. Stay tuned!

Closing this issue for now, if there is something else that anyone feels should be discussed, comment below and I will reopen. Thanks to everyone for all your help!

**Comment by RyanZim** [comment]
@ai A few questions/problems with auto-switching via file extensions:

Should `.scss` files use `postcss-scss` as a `syntax` or a `parser`?

Another problem:

- If a `.sss` file imports a `.css` file, the `.css` file should be parsed with the default parser, _ignoring_ `result.opts.parser`.
- Suppose you are using postcss-safe-parser or postcss-scss as a parser, and all your files have a `.css` extension. If one `.css` file imports another `.css` file, it seems reasonable to assume that the second one will be parsed with the custom parser. That means _respecting_ `result.opts.parser`.

So we have a predicament: do we ignore or respect `result.opts.parser` for `.css` files?

One possible solution would be to respect `results.opts.parser` if `path.extname(parent) === path.extname(import)` and ignore it otherwise. This would cover both the scenarios above, but wouldn't work perfectly in at least one (edge) case:

If `a.css` is parsed with postcss-safe-parser, and imports `b.sss`, which imports `c.css`, `c.css` will be parsed with the default parser, not postcss-safe-parser.

Thoughts?

**Comment by michael-ciniawsky** [comment]
```js
extname(import) === '.css' && result.opts.parser === 'postcss-safe-parser' ? result.opts.parser : 'postcss-parser'
```

**Comment by ai** [comment]
File extension should change parser, not a syntax (syntax is parser + stringifier, stringifier will be one for all and controlled by gulp-postcss/postcss-loader).

**Comment by ai** [comment]
Yeap, if we import .css - .sss - .css, latest .css should be parsed with default parser.

We could split parsers with ext based (sugarss, scss) and standard based (default, safe).

**Comment by ai** [comment]
Yeap, using opts.parser on importing .css into .css is correct.

**Comment by RyanZim** [comment]
Wow, this gets pretty complicated. I'll try to see if I can get things running, based on the ideas above.

**Comment by RyanZim** [comment]
@ai What should the behavior be when `result.opts.syntax` is specified? Should all imports be processed with that regardless of extension? Not sure how many users of postcss-import actually use custom syntax, but...

**Comment by ai** [comment]
@RyanZim use only `parser` part of `syntax` (with same logic as we discuss above). `syntax` is just a shortcut to `{ parser, stringifier }`

**Comment by RyanZim** [comment]
OK, I've got a working prototype. It needs more tests yet, though.

**Comment by RyanZim** [comment]
Strawman implementation: https://github.com/postcss/postcss-import/pull/245

**Comment by RyanZim** [comment]
Attention everyone: Advice/Thoughts wanted on https://github.com/postcss/postcss-import/issues/216.

**Comment by RyanZim** [comment]
OK, https://github.com/postcss/postcss-import/pull/245 is merged and v9 is winding down.

Two things that need discussion yet:

# `transform`

Do we need this option? @michael-ciniawsky had brought this up earlier, but it got lost in the noise.

I would be in favor of removing it.

- Use-cases are limited, and anyone with a complex enough use-case can use the `load` option; all that's needed is a little file loading boilerplate.
- It adds a bit of complexity.
- It creates the too-many-options syndrome for new users of postcss-import.

@ai Thoughts?

# Deprecation of legacy import hooks

[`addDependencyTo`](https://github.com/postcss/postcss-import#adddependencyto) is deprecated in the docs; should we add a `console.warn` when it is used to give lazy devs a poke, or altogether remove it?

[`onImport`](https://github.com/postcss/postcss-import#onimport) should be deprecated sometime IMO. Don't know if it should be right away (this release) or not. I'm not really in favor of warning for this, since I know that would cause pain at `postcss-cli`. `postcss-cli` needs to do breaking changes to support the `dependency` message, and cutting a major takes time (we've been working for 13 days just on v9 here). I don't suppose deprecating something in the docs is a breaking change (though warning about its use is IMO).

**Comment by ai** [comment]
I like `transform`. It is just a shortcut. If you need just to change a inputed file, but do not want to load it.

But could we add a PostCSS plugin only to imported files? The best way to transform CSS it s PostCSS plugin :D.

**Comment by RyanZim** [comment]
@ai We already have a separate option for running postcss plugins on imported files: https://github.com/postcss/postcss-import#plugins. `transform` is only useful for the weird edge-cases where you want to do plain string manipulations on the files. That's such an edge-case, I don't feel we need to support it (especially when it's possible with `load`).

**Comment by ai** [comment]
@RyanZim OK, in this case I totally agree that we could remove it and ask to use `load`

**Comment by RyanZim** [comment]
@ai SGTM (PR coming), thoughts on legacy import hooks?

**Comment by RyanZim** [comment]
@ai @MoOx @michael-ciniawsky thoughts on legacy import hooks (https://github.com/postcss/postcss-import/issues/242#issuecomment-262414932)?

**Comment by ai** [comment]
+1 for deprecate warning for `addDependencyTo`

**Comment by michael-ciniawsky** [comment]
@RyanZim

### `transform`

As you mentioned above, it is basically applying a **plugin** to transform the imported file, or do I miss something  here in terms of import logic ?* 😛 If so imo `options.plugins` can/should handle that ? Or is it an entirely `{String}` based transformation?

* options.transform ===
```js
postcss(options.plugins).use(transform).process(import, options.options)
```
 ? 

Then maybe consider renaming transform => use, for API consistency :) ? It should be the first 'plugin' applied, before inherited plugins or options.plugins are applied on the imported file. Still questionable imo, because folks can use their 'custom transform (plugin)' in the main chain if needed or set it as the first one in options.plugins 😎 . 

###  `OnImport` 

What common usecases exists that need to apply a function after the import process and isn't that basically a plugin also? I never use that, so this is an out of the blue question 😛.Your main postcss 'chain' (plugins === functions) is in charge after the importing?

If I got something completely wrong here, I still find these various options confusing to some point, what is your opinion on merge and refactor these two options to something like e.g 

```js 
transform || use: {  before[Import]: () => {},  after[Import]: () => {} }
```

### `load`

Finally what is the propose of  `load`, to overwrite the behaviour how files are read from disk e.g async/sync/stream?

**Comment by RyanZim** [comment]
@michael-ciniawsky `transform` is strictly string-based; no postcss involved here. `load` is to customize the behavior how files are read from disk. `load` also has fairly limited use-cases, so I am proposing removing `transform` and using `load` to cover both cases.

`onImport` isn't a function for manipulating the import data; it was used for getting a list of imported files before postcss-import supported the `dependency` message. I don't want to remove `onImport` in this release, since postcss-cli still uses it. Possibly later, though.

**Comment by michael-ciniawsky** [comment]
@RyanZim So the `load`option will work in the direction like e.g 

```js
const { createReadStream } = require('fs')
const transform = (css /* {String} */) => css.replace(...)

options.load = (filename, createReadStream, transform)
```
?

**Comment by RyanZim** [comment]
@michael-ciniawsky Not sure what you mean; this would be an example use:

Assuming `loadFile` takes a filename and returns a promise resolving to the contents of the file; and `transform` takes a string and returns a transformed string,
```js
options.load = (filename, options) => {
  return loadFile(filename)
  .then(contents => {
    return transform(contents)
  })
}
```

**Comment by michael-ciniawsky** [comment]
@RyanZim I meant it in that way :)

```js
options.load = (filename, loadFile, transform) => {...}
```

How does the options param look like ?

```js
{ loadFile: '', tranform: () => {} }
```

Is changing the loading behaviour in terms of how to read form disk really necessary? Maybe I got something wrong in terms of usage here 😛 

```js
options.load = (filename) => (contents) => contents.replace  // ?
```

**Comment by RyanZim** [comment]
@michael-ciniawsky `load` gets `filename` and `options` as arguments. In my example, you would need to define `loadFile` & `transform` yourself, somewhere else in the file.

**Comment by michael-ciniawsky** [comment]
RyanZim What is the propose of the options param in options.load? :trollface:  😛 


```js
options = {
   root: { path: '', relative: true }, 
   // default => result.opts.from 
   // ? { path: result.opts.from, relative: true } 
   // : { path: process.cwd(), relative: false }
   load: (filname) => loadFile(file) => contents.replace(...), // default => readCache()
   plugins: [ /* PostCSS Plugins */ ] // default => [] => result.processor.plugins
   options: { /* PostCSS Options */ } // default => {} => result.opts
  onImport: 'deprecated' :)
}
```

?

**Comment by RyanZim** [comment]
Not sure, just in case you might need it I guess.

**Comment by RyanZim** [comment]
Main PR for v9: https://github.com/postcss/postcss-import/pull/252.

**Comment by simonsmith** [comment]
Just to chime in on this. We use `transform` and `onImport` on the SUIT CSS preprocessor. `transform` allows us to run linting tasks on each imported file. This is preferable to linting the entire file after other plugins have run and preprocessed the source.

As I understand it there is a more idiomatic way to do this now with `load` and implement a custom `transform` function. Also sounds like something I could move into `easy-import` if people missed it (same with globbing etc).

We use `onImport` to allow a watch task to be aware of changes in a dependency. I think `postcss-cli` used it this way too. Would be a shame to see that behaviour go.

**Comment by RyanZim** [comment]
@simonsmith I understand what you are saying.

**`transform`:**

You can do this will just a few more lines of code:
```js
var fs = require('fs-promise'); // <-- Any promisified fs lib will work here
opts.load: function (filename) {
  return fs.readFile(filename, 'utf8')
  .then(function (contents) {
    // Do your transform/linting here and return the modified contents
  })
}
// Run postcss
```

Also, if your linting can be done as a postcss plugin, you can use the `plugins` option.

**`onImport`:**

You are correct about postcss-cli; that's partially why we didn't remove it yet. The preferred method to get a list of imported files is to use the new `dependency` message. We are trying to standardize the `dependency` message throughout the whole postcss ecosystem, so that is the way to move forward. Usage is:
```js
var deps;
postcss(plugins)
.process(css, opts)
.then(function (result) {
  deps = result.messages.filter(m => m.type === 'dependency')
  // Do something with the result
});
```
