### ISSUE TITLE
less mixins are not supported when using with postcss-less syntax

### ISSUE THREAD

**Issue by jakwuh** [postcss/postcss-import#248]
Hi! I've created a [sample repo](https://github.com/jakwuh/postcss-import-less-mixins-demo) to demonstrate what I am talking about.
Despite the usage of `postcss-less` syntax, `postcss-import` still fails parsing less mixins.
```
Warning {
       type: 'warning',
       text: '/private/tmp/postcss-import-less-mixins-demo/sample.less:5:3: Unknown word'
```
Am I missing something?
Thanks in advance.

**Comment by RyanZim** [comment]
I'll look into this when I get a chance.

FYI, we're heavily refactoring custom syntax/parser support for the upcoming v9.

**Comment by RyanZim** [comment]
This is an issue with `postcss-less`, not `postcss-import`. Using `postcss-less` (without `postcss-import`, I can't even parse the less code you used in your example without getting the same error.

`postcss-less`:

> This project is not stable and is in development.

Apparently, this is one of the incomplete parts.

**Comment by jakwuh** [comment]
@RyanZim thank you for your time. Could you please explain me briefly how could I reproduce this error without `postcss-import`?  I have tried transpiling the same code without any plugins / with other plugins but still wasn't able to reproduce the same error.

**Comment by RyanZim** [comment]
Here are the relevant parts of my configuration:
```json
{
    "use": [
      "autoprefixer"
    ],
    "syntax": "postcss-less",
    "input": "src/*.less",
    "dir": "dist/",
    "map": "file"
}
```
I get this error:
```
/{full path}/src/more.less:6:3: Unknown word   4 | }
  5 | .mixin-class {
> 6 |   .a();
    |   ^
  7 | }
  8 | .mixin-id {
```
The contents of `more.less` are:
```less

.a, #b {
  color: red;
}
.mixin-class {
  .a();
}
.mixin-id {
  #b();
}
```

**Comment by jakwuh** [comment]
@RyanZim Yes, this is actually a `postcss-less` bug. Thank you once more. I've created an appropriate issue. https://github.com/webschik/postcss-less/issues/63
