### ISSUE TITLE
Resolving module @imports seems at odds with css-loader

### ISSUE THREAD

**Issue by gnarf** [postcss/postcss-import#253]
Webpack's css-loader uses the approach of denoting a module prefix with a `~` 

In our project we have a variables file that is located in `@imports '@our/ui/lib/variables.css';`, this syntax works fine for postcss-imports but then css-loader will also parse it and complain that it can't find the module `@imports '~@our/ui/lib/variables.css';` only inverts the problem.

To workaround it, I wrote a resolve function that strips the leading ~ if it exists, and would like to ask that you consider making this exception to support `css-loader!postcss-loader` scenarios.

```js
const postcssImportResolveId = require('postcss-import/lib/resolve-id')

module.exports = function stripTilde(uri, base, options) {
  // css-loader and postcss-import disagree about how to @import from
  // modules.  We need css-loader to see a ~ to demonstrate that it
  // comes from a module:
  // @import '~@our/ui/lib/variables.css'
  // postcss-import doesn't use a ~, so we need to strip it here:
  if (uri[0] === '~') {
    return postcssImportResolveId(uri.substring(1), base, options)
  }
  return postcssImportResolveId(uri, base, options)
}
```

**Comment by RyanZim** [comment]
@gnarf Just to clarify, are you asking us to strip a leading `~` from all import paths?

@MoOx @ai What are your thoughts on this?

**Comment by gnarf** [comment]
Yes! It's an odd situation but css-loader treats 'foo/bar.css' as
'./foo/bar.css' and uses the ~ to support looking in the modules directory

On Dec 2, 2016 17:20, "Ryan Zimmerman" <notifications@github.com> wrote:

@gnarf <https://github.com/gnarf> Just to clarify, are you asking us to
strip a leading ~ from all import paths?

@MoOx <https://github.com/MoOx> @ai <https://github.com/ai> What are your
thoughts on this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/postcss/postcss-import/issues/253#issuecomment-264578068>,
or mute the thread

**Comment by ai** [comment]
@gnarf you could disable `@import` handling in `css-loader` by `css-loader?-import`.

Processing `@import` with 2 systems (`css-loader` and `postcss-loader`) is very dangerous.

**Comment by gnarf** [comment]
Hrm, I'm not entirely sure why the import stays in the css file after postcss parses it then... Wouldn't it get parsed by the browser or whatever else is upstream if I weren't using css-loader?

**Comment by RyanZim** [comment]
@gnarf If you disable css-loader's import functionality, postcss-import would parse all of the imports.

**Comment by gnarf** [comment]
This seems unintuitive. Since postcss runs "first", isn't it still going to
output the same @import it's outputting now?

**Comment by gnarf** [comment]
Or rather, why doesn't postcss-import know to remove the `@import` if it handled everything?  If it is dangerous, why does the foot gun exist (and is the default behavior?)

**Comment by ai** [comment]
@dnarf could you show your loaders config? Maybe you process css-loader before postcss-loader?

**Comment by gnarf** [comment]
I think I figured it out while trying to read up on postcss-loader's.  whoever set this up did not read postcss-loader's docs... importLoaders isn't set on the css loader, I'm gonna test this later when back at my computer to make sure and close...

**Comment by gnarf** [comment]
Well, I added `importLoaders=1` to my query but no luck, still end up with the same error:

Here is the relevant part from webpack.confg module.loaders:

```js
      // load "localSource" with css-modules and autoprefixing for ./src
      {
        test: /\.css$/,
        include: [localSource],
        loader: 'css-loader',
        query: {
          module: 'localIdentName=[name]---[local]---[hash:base64:5]',
          importLoaders: 1,
        },
      },
      // load other css files outside of `src` with plain css loader
      {
        test: /\.css$/,
        exclude: [localSource],
        loader: 'css-loader',
        query: {
          importLoaders: 1,
        },
      },
      // postcss all css via postcss-loader:
      {
        test: /\.css$/,
        loader: 'postcss-loader',
      },
```

I'm not understanding why, if `postcss-import` handles the `@import` stuff, it isn't removing/replacing it, I.E. why does css-loader even still see it.

If it helps reproduce, the situation is such:

```css
/* src/client/somedir/file1.css */
@import '../app/variables.css'

/* src/client/app/variables.css */
@import '@our/ui/lib/variables.css'
```

Webpack complains with the error:

```
ERROR in ./~/css-loader!./src/client/app/variables.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./@our/ui/lib/variables.css in [redacted]/src/client/app
 @ ./~/css-loader!./src/client/app/variables.css 3:10-100
```

I'm unlikely to check up on this again until monday, don't let me hold up a release if it's important for 9.0.0 to go out, I have a workaround working for now, but would love to figure out what is happening

**Comment by ai** [comment]
I though that you need one `test` with `loaders` inside? Look how I wrote in postcss-loader docs. But webpack had so many config syntax, maybe I missed it.

**Comment by gnarf** [comment]
webpack supports chaining loaders like this if multiple tests match they apply

**Comment by gnarf** [comment]
I'll try to reduce a test case for you that I can make public on Monday.  Thanks for the quick responses tonight!

**Comment by gnarf** [comment]
okay, I feel like a complete idiot now, I *just* noticed that `postcss-loader` wasn't in that loader `ERROR in ./~/css-loader!./src/client/app/variables.css`, and started digging.

There is a second "storybook" instance of webpack running that is using a configuration so out of date I'm suprised anything works...  This explains why I was seeing an error but everything appeared to be functioning normally...

Sorry to have wasted your time :/

**Comment by michael-ciniawsky** [comment]
<img src="https://i.imgflip.com/1f986i.jpg">

**webpack.config.js** (webpack >= 2.1.0-beta.27)
```js
      // load "localSource" with css-modules and autoprefixing for ./src
      {
        test: /\.css$/,
        include: [localSource],
        use: [ { loader: 'css-loader', options: { module: '...' } } ]
      },
      // load other css files outside of `src` with plain css loader
      {
        test: /\.css$/,
        exclude: [localSource],
        use: [ 
         { loader: 'css-loader', options: { importLoaders: 1 } }, 
         { loader: 'postcss-loader', options: { plugins: () => [...] } }
        ]
      }
```

Personally I would also load all `.css` with one **setup**, it tends to be less error prone, even if some `css` might not 'need' `postcss-loader` at all and the build time takes 0.00002 ms longer.... 😛

**Comment by gnarf** [comment]
Personally, I'd rather make sure the `postcss-loader` applies to all the css with consistent options.  Since it seems you forgot to include it in the `include: [localSource]` example, you've demonstrated exactly why I set it up with multiple tests in a chain like this.  It avoids having to keep the options consistent between the postcss-loader in both the src and not src folders, when it is only the `css-loader` that has different options.

So shrug... I feel my setup is less error prone, since I didn't make an error and you did?
