### ISSUE TITLE
Add option to blacklist paths

### ISSUE THREAD

**Issue by IonicaBizau** [postcss/postcss-import#254]
Let's say I want to blacklist a specific url, which is added in the result, inlined, currently.

How can I do that?

**Comment by RyanZim** [comment]
@IonicaBizau I'm don't think that is possible currently. Wouldn't be opposed to adding that, would just need to add some conditional logic around https://github.com/postcss/postcss-import/blob/master/index.js#L182.

Won't have time to work on this in the near future, PR welcome.

We should probably accept a string or regex; or an array of strings or regexes to match against.

**Comment by IonicaBizau** [comment]
@RyanZim I did try to hack into the code and specifically I already tried to change that line, but it just didn't work... It was still replacing the `@import`s with the content.

I'd be happy to add it, but will need some guidance where that should be added... 😁 

Thanks!

**Comment by RyanZim** [comment]
Adding another `if` statement with an empty `return` if the path is blacklisted should do it, not sure what your issue was. Right now I'm working 10 & 12-hour days at my day job, so no time to look at this now.

**Comment by IonicaBizau** [comment]
It turns out that this tool is smart enough to know when it should inline the things and when not. Therefore a blacklist is not critical for me now.

Still, it'll be nice to have in the future.

**Comment by RyanZim** [comment]
Fixed in #327
