### ISSUE TITLE
AtDependencyTo Deprecation

### ISSUE THREAD

**Issue by felixsanz** [postcss/postcss-import#255]
What does this mean?

> **DEPRECATED**. If you are using postcss-import v8.2.0 & postcss-loader v1.0.0 or later, this is unnecessary.

I'm using above those versions and if i try to remove `atImport({ addDependencyTo: webpack }),` from my code it won't work anymore

**Comment by michael-ciniawsky** [comment]
@felixsanz postcss-import  > 8.2.0 adds the imported files to `result.messages` and postcss-loader > 1.0.0   adds them to webpacks for file watching (loader.addDependencyTo) automatically. Passing that as plugin options should be unnecessary.

**components/button.css**
```css
.button {}
```

**index.css**
```css
@import 'components/button.css';

.main {}
```

```js
postcss([ require('postcss-import')() ]).process(css, options).then((result) => {
   result.css = '.button {}...'
   result.messages = [ {type: 'dependency', file: 'path/to/import.css' } ]
  // postcss-loader filters the array for type: 'dependency' and pass it to webpack.addDependencyTo
})

I need the following to eventually debug occuring problems

- webpack version
- postcss-import version
- postcss-loader version 
- webpack.config.js (as gist)
- current webpack output (as gist)

**Comment by RyanZim** [comment]
Thanks @michael-ciniawsky !

**Comment by felixsanz** [comment]
Actually i think i missunderstand it.

I removed `atImport({ addDependencyTo: webpack }),` entirely. That's why it didn't work.
What i had to remove was only the `addDependencyTo` option. :sob:

**Comment by RyanZim** [comment]
Glad you got it fixed @felixsanz!
