### ISSUE TITLE
jspm catch resolved?

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss-import#258]
Should this [JSPM catch](https://github.com/postcss/postcss-import/blob/master/lib/resolve-id.js#L2-L9) be removed?

It looks like the fix was released in jspm 0.16.35 (released May 25, 2016) https://github.com/jspm/jspm-cli/issues/1778

**Comment by RyanZim** [comment]
That JSPM issue was resolved, however, you will note that `pkg-resolve` is not listed as a dep in the [package.json](https://github.com/postcss/postcss-import/blob/master/package.json). JSPM users that need it can install it manually and postcss-import will use it. For this reason, we still need the `try/catch`; PR welcome to remove the comment at https://github.com/postcss/postcss-import/blob/master/lib/resolve-id.js#L3.

**Comment by thisconnect** [comment]
I am trying to speed up my postcss task by pre bundling it with rollup. Unfortunately rollup breaks saying:
```Error: Could not resolve 'pkg-resolve' from /Users/connect/source/tools/node_modules/postcss-import/lib/resolve-id.js ```

I don't understand what or how JSPM users would use postcss-import. Is it meant for CSS packages from JSPM instead of npm ? Is that a thing?

In this case shuoldn't there be a postcss-jspm-import, that has pkg-resolve in package.json?

**Comment by michael-ciniawsky** [comment]
@thisconnect `pkg-resolve` is a `peerDependency of `postcss-import`  since `v9`, you must explicitly install it yourself. How do you bundle with rollup ? with `rollup-plugin-postcss` ?

**Comment by thisconnect** [comment]
Hi @michael-ciniawsky thanks for you quick reply. I am doing more of an experiment.

> How do you bundle with rollup ? with rollup-plugin-postcss ?

I don't use postcss-plugin-postcss. I use postcss directly, but this task is by far the slowest. Just requiring postcss + all postcss-plugins takes a lot of time. I am experimenting if I can speed up the startup time. Inspired by https://medium.com/@Rich_Harris/how-to-not-break-the-internet-with-this-one-weird-trick-e3e2d57fee28#.17nupnk65

My experiment is to rollup the postcss task and bundle as commonjs module that I can bundle all my CSS with. Also my hope is that this speeds up the loading of postcss, as it is just 1 big file and does not have to require the plugins and their dependencies anymore.

Of corse I ran into a few problems some with rollup itself (https://github.com/rollup/rollup/issues/988), but they are resolved now. My current postcss setup is: postcss, postcss-import, postcss-copy, postcss-pxtorem, postcss-cssnext and stylelint.

It is almost a surprise that without postcss-import, rollup is able to bundle the whole postcss script + all other plugins (not sure yet if that will run) :).

Obviously rollup has issues with `try { jspmResolve = require("pkg-resolve") }`. rollup-plugin-commonjs would inline that to the top, and end up with import jspmResolve from 'pkg-resolve' or something like that.

Sorry for writing such a long comment.

**Comment by RyanZim** [comment]
@thisconnect I'm fooling with the idea of removing jspm support altogether in the next major release; we will be refactoring module resolving then. Until then, sorry. :disappointed:

**Comment by thisconnect** [comment]
No problem I am in no hurry. Great to hear (for me). Thanks!

**Comment by RyanZim** [comment]
Fixed in v10
