### ISSUE TITLE
Provide an option for extensions

### ISSUE THREAD

**Issue by jhnns** [postcss/postcss-import#260]
Currently, postcss-import will expand all paths to [`.css` automatically](https://github.com/postcss/postcss-import/blob/2a687f867ba73e51aa9a838fa3f14e08174786f7/lib/resolve-id.js#L34). Would you be open for a pull-request to add an `extensions` option? This way, you could also compile other file types like Sass (if you're only using a subset of Sass for instance).

@karlhorky would take care of that PR.

**Comment by michael-ciniawsky** [comment]
@jhnns [postcss-partial-import](https://github.com/jonathantneal/postcss-partial-import) extends postcss-import with non spec compliant behavior e.g (globs, **extentions**).

**Comment by jhnns** [comment]
Awesome, thanks! Sorry for bothering you.

**Comment by michael-ciniawsky** [comment]
>  Sorry for bothering you

By no means 😛 , if @karlhorky is interested in helping out, he could join PostCSS Gitter, there is discussion going on about merging those two in the near future in a not to 'spec'  voilating way + dev friendly sugar like globs, extensions, cleaning up confusion about throwing X plugins at the same problem :D

**Comment by karlhorky** [comment]
Joined!

> there is discussion going on about merging those two in the near future in a not to 'spec' voilating way

Cool, that sounds great. I'm in the middle of setting up many other things right now, but this project sounds very cool so I may be able to find time to help here too!
