### ISSUE TITLE
PostCSS Sugar Discussion

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss-import#261]
There has been discussion about how strict or sugary PostCSS Import should be. The suggestion has been made to follow this philosophy:

1. PostCSS Import follows and resolves imports according the [`@import` specification from CSS Cascading and Inheritance](https://drafts.csswg.org/css-cascade-3/#at-ruledef-import), and never does anything to explicitly interfere with this.

2. Should classical resolution of an import fail, PostCSS Import will automatically and gracefully resolve files by two common and popular patterns. This is specifically and in order:
   1. The [resolve algorithm](https://nodejs.org/api/modules.html#modules_all_together) used by Node.
   2. The [glob algorithm](https://github.com/isaacs/minimatch#minimatch) used by npm and most shells.

Regarding the resolve algorithm, PostCSS Import will:
- Presumes a `.css` extension, like the Node experience with `.js`. As an option, users may configure this.
- Changes the `package.json` resolution expectation:
   - Uses the file specified by the `style` key relative to the package if it is present. Otherwise;
   - Uses the file specified by the `main` key relative to the package if it is present and uses a `.css` extension. Otherwise;
   - Uses the `index.css` file relative to the package.
- Presumes no prefix, unlike the [Sass experience](http://sass-lang.com/guide#topic-4) with `_`. As an option, users may configure this.

To move forward, we’re looking for agreement on this philosophy from a handful of [postcss org members](https://github.com/orgs/postcss/people). Otherwise, we’re looking to make changes to it that we can agree on moving forward.

To move forward, we do not need to discuss or agree on how these things will be implemented. We can, but I’ve specifically avoided defining configurations that might sidetrack us.

To move forward, we do not need to discuss caching. We can, and caching is important, but I think it might also sidetrack us.

**Comment by michael-ciniawsky** [comment]
### Interface 

```js
require('postcss-import')({
  resolve: {
    root: processor.opts.from || process.cwd()
    paths: []
    globs: true
    modules: [ 'node_modules', 'bower_components' ]
  },
  parser: '' || require('')
  plugins: []
})

```

### Options

|Option|Default|Type|
|:---:|:-------:|:---:|
|**`root`**|`processor.opts.from || process.cwd()`|`{String}`|
|**`paths`**|`[]`|`{Array}`|
|**`globs`**|`true`|`{Boolean}`|
|**`modules`**|`['node_modules', 'bower_components']`|`{Array}`|
|**`parser`**|`processor.opts.parser`|`{String|Function}`|
|**`plugins`**|`[]`|`{Array}`|

**`paths`**:

- 1
```js
resolve: {
  paths: ['path', '/path', '/path/']
}
```

- 2 (recommended)
```js
resolve: {
  paths: ['path', '/path', '/path/', ..., filter]
}
```

- 3
```js
resolve: {
  paths: [ ['path', '/path', '/path/'], filter]
}
```

### Caching

Stick with `read-cache` ?

**Comment by RyanZim** [comment]
@michael-ciniawsky Let's discuss implementation details later, in a separate thread.

**Comment by michael-ciniawsky** [comment]
@RyanZim Yep thats more of an Rationale, I want to keep and update according to consensus, just drafting the structure out atm :)

**Comment by andyjansson** [comment]
I think it's important not to hard code the aforementioned patterns, but instead provide a pluggable architecture so we can plug in our own implementation if we choose to do so. 

IMO the out-of-the-box behaviour should be in line with the `@import` specification, whereas the rest could be supplied as optional packages which extend the default behaviour. 

Depending on the project, `@import`s can lead to a lot of expensive (time-consuming) IO operations, so one of the things I'd like to implement as an optional package is a caching strategy. To do that I need to:

1. build a dependency graph of the imports ("file `foo` imports `bar`, `baz`, `bat`")
2. write the imported files to the cache after they've been fully processed (that is, after that file has been imported, and the imports of that file has been resolved and so on)
3. return the cached copy once requested
4. invalidate cache for the dependents after a file has been modified (done with the dependency graph and comparing mtime)

So, what I'd like to see in postcss-import is: 

* a way of supplying a custom implementation for resolving requested file paths to their actual file paths (be it for globs, various read locations, implicit file extensions, underscored file names or whatever). It should be known what file issued the request (e.g. if the requested file is in a path relative to the file which requested it). 

* a way of knowing that requested file `bar` resolved into file `baz` when requested by file `foo` (that is, for packages to know what other packages resolved something into).

* a way of supplying a custom implementation for loading the requested files (so I could return a cached copy if I'd like to). 

* a way of accessing the fully processed result for each import (so I could write the caches). 

What form this would take is up for discussion. One option is taking a middleware approach. Another option is to register an array of plugins which in turn can plug into some event system once loaded. 

My two cents.

**Comment by jonathantneal** [comment]
@simonsmith, would you let us know how you feel about putting the sugar into postcss-import?

Remember, postcss-import already has node and package resolution. easy-import adds glob and custom extensions (all covered in the prompt). partial import has glob, custom extensions, custom prefixes (all covered in the prompt), and manifest touching.

I totally understand that you *just* finished putting a lot of work into easy-import. In a previous thread, @TrySound had planned to deprecate that project. Now both projects are becoming the same thing, and usage statistics show that both projects are continuing to adopt more users; that’s not great for users trying to decide between 3 import plugins that all promise magic.

https://npm-stat.com/charts.html?package=postcss-easy-import
https://npm-stat.com/charts.html?package=postcss-partial-import

While partial-import has 10:1 users as easy-import, I’d sooner deprecate that project and move everything into easy-import under the postcss banner. However, that still leaves half the sugar in postcss-import and half the sugar in easy-import. This thread is intended to entirely resolve the matter. I hope what I’m saying makes sense, and I really, really hope we can work together on this.

**Comment by simonsmith** [comment]
Hey,

I've been reading this entire thread thinking you meant SugarSS. Ha!

I presume you mean features that are outside of what is deemed as the spec? My thoughts were that was what easy-import was meant to do. That's the impression I've had from reading various issues here and our [brief discussion about it](https://github.com/postcss/postcss-import/issues/145#issuecomment-263737123)

What was the problem with all the features living in `postcss-import` to begin with? Correct me if I'm wrong but doesn't `@import` work just fine in browsers without a preprocessor? I didn't think any of the features handled here were intended to reach browsers one day.

**Comment by RyanZim** [comment]
> What was the problem with all the features living in postcss-import to begin with?

Legacy reasons. We are discussing moving all the features into postcss-import, but wanted to make sure you were fine with that (this change would make easy-import unneeded).

**Comment by simonsmith** [comment]
I guess it's unfortunate that this discussion is happening _just_ after I fixed a load of bugs. But I agree that there should be one import solution and probably always should have been.

**Comment by jonathantneal** [comment]
Thank you, everyone! We have an acceptable quorum, but I think a thumbs up from @ai would “seal the deal” and allow us to move forward.

**Comment by ai** [comment]
I think import should be sugarly. Because there is very small subset or users, which need only W3C compatible support.

There is a reason to be compatible with CSS Custom Properties, because polyfill plugin is temporary. You expect to remove it when browsers will support spec.

But there is no sense to remove `postcss-import`. Browsers already support it. But users don’t need standard limited slow `@import`.

**Comment by dehuszar** [comment]
I'm really glad this conversation is happening, as I have been trying to figure out how to best keep postcss-reference up-to-date and idiomatic with community best-practices.

Personally, I would like at least the ability to disable strict mode, or allow flexibility around forcing `@import` statements to the top.  In postcss-reference, I've used the pattern of:
```
@reference {
  @import 'file.css';
}
```
Even if I put all those `@reference` imports at the top, it still fails because of this strictness.

I can just make all the referenceable stylesheets available by forcing users to state their files directly in the plugin config, but I think there's value in being able to use the `@import` composability.  In my case, there's no expectation that the `@import`s would ever be evaluated by the browser, so strict mode compliance feels arbitrary.

Whether the best implementation pattern is to place a flag in the postcss-reference config which extends and overrides postcss-import strictness in this one specific way, or whether postcss-import has it's own flag, or hooks that other plugins can utilize to do the same, I don't have a strong opinion.

I think, regardless of how the above pans out, postcss-reference will try to maintain a composable, in-css option for defining and/or importing referenceable rules as well as allowing for using node's fs module to load referenceable stylesheets into memory via the plugin config.

**Comment by dehuszar** [comment]
Whoa.  Just realized the date on this conversation.  1 year old to the day from the last comment.  Thought I was just catching it at the start

**Comment by jonathantneal** [comment]
This conversation went stale. I’m closing it out.
