### ISSUE TITLE
Missing code under :root selector

### ISSUE THREAD

**Issue by QuantumInformation** [postcss/postcss-import#262]
Same issue as desc here:https://github.com/sebastian-software/postcss-smart-import/issues/43

repo:

https://github.com/quantumjs/smart-terminal/blob/master/postcss.config.js

**Comment by RyanZim** [comment]
@QuantumInformation See my comment in the gitter channel

**Comment by RyanZim** [comment]
Here is what I posted on gitter:

@QuantumInformation You are using postcss-css-variables. That plugin will remove all your variables once all the var() statements have been transpiled.

Try using one of the variables in your css, and see if the value isn't substituted.

**Comment by QuantumInformation** [comment]
This is the way that is supported:

https://github.com/cssrecipes/custom-media-queries

**Comment by MadLittleMods** [comment]
@QuantumInformation @RyanZim You can use `opts.preserve = true`, https://github.com/MadLittleMods/postcss-css-variables#preserve-default-false if you still need to hang on to the declarations.
