### ISSUE TITLE
unexpected behavior in combination with nested custom media queries

### ISSUE THREAD

**Issue by smuemd** [postcss/postcss-import#263]
consider the following setup

```css
/* in components-hero (seperate css file)*/
#Selector2 {
  @media (--lg-viewport) {
  }
}

/* in theme-default (another seperate css file) */
@custom-media --lg-viewport screen and (min-width: 60em);

/* and finally in index.css */
@import 'components-hero';
@import 'theme-default';
```

The error:
```console
postcss-custom-media: Missing @custom-media definition for '--lg-viewport'. The entire rule has been removed from the output.
```

However, if I put everything into a single file, it works:

```css
/*  single file works */

#Selector2 {
  @media (--lg-viewport) {
  }
}

@custom-media --lg-viewport screen and (min-width: 60em);
```

Any ideas what could be wrong here?

**Comment by RyanZim** [comment]
@smuemd I would guess something is wrong with the file loading. Try compiling index.css without the postcss-custom-media plugin, just postcss-import. Post the output here.

**Comment by smuemd** [comment]
@RyanZim 

I am Closing the issue. It is working now. I can not reproduce the odd behaviour previously described. Thank god. Must have been some strange typo in my query, that I totally missed.

Apologies for the confusion and thank you for your help.
