### ISSUE TITLE
Syntax error formatting in the console

### ISSUE THREAD

**Issue by robcrocombe** [postcss/postcss-import#264]
Hi, I'm using this plugin in Gulp. When there is an error in the main file (not imported) it displays in a code frame like this:

```
  11 | */
  12 |
> 13 | a {
     | ^
  14 |   color: red;
  15 |
```

However, if the error is from an imported file I get this (for example):

```
postcss-import: /Users/.../stylesheets/app.css:1:1: /Users/.../stylesheets/src/base.css:54:1: Unclosed block
```

Is there a way I can get the pretty-printed error message instead? Thanks

**Comment by RyanZim** [comment]
Not sure.

@ai We are currently sending errors back via `result.warn()` https://github.com/postcss/postcss-import/blob/master/index.js#L282. Do you know offhand if there is a better way to do this?

**Comment by michael-ciniawsky** [comment]
```js
if (err.name === 'CssSyntaxError') err.message + '\n\n' + err.showSourceCode() + '\n'
```

or don't add it to result.warn and pass it through. `gulp-postcss` joins and logs warnings with `gutil`. That's also the reason while the  file path is displayed twice in the example above. `gulp-postcss` would handle the err like the code above does.

**Comment by RyanZim** [comment]
@michael-ciniawsky Thanks for chiming in, I knew there was probably a better way, but didn't have time to look.

I would consider erroring for syntax errors in the next major release; for now, we need to still warn to keep backwards compatibility.

PR welcome to add `err.showSourceCode()` to the error message.

**Comment by ai** [comment]
@RyanZim `result.warn()` is for warnings. It is better to throw correct a `SyntaxError` (it is a little bit tricky to build correct one, but you will have this cute code example)

**Comment by RyanZim** [comment]
@ai I will definitely throw an error in the next major, but I thought changing the `result.warn` behavior would be a breaking change.

**Comment by robcrocombe** [comment]
@RyanZim I take it it's been resolved. Thanks!
