### ISSUE TITLE
Resolve is non-recursive?

### ISSUE THREAD

**Issue by sunny-g** [postcss/postcss-import#266]
In a previous version of this plugin, `@import`s seemed to be recursively resolved but I am noticing that now in 9.1.0 they aren't. Is this intentional? 

These are the outputs of a `console.log` within a custom `resolve` defined within this plugin

before (webpack v1.x.x, postcss-import v7.1.3):
<img width="365" alt="screen shot 2017-01-18 at 6 22 10 pm" src="https://cloud.githubusercontent.com/assets/2055636/22091258/12659e14-ddab-11e6-9f42-39fb49d2b2c4.png">

after (webpack v2.2.0, postcss-import v9.1.0):
<img width="271" alt="screen shot 2017-01-18 at 6 18 43 pm" src="https://cloud.githubusercontent.com/assets/2055636/22091243/ed9b29e6-ddaa-11e6-992b-2edd41271533.png">

**Comment by RyanZim** [comment]
Works fine for me, https://runkit.com/57ebc041d4a27f140028fd78/5880bd0127f9e0001374d852; not sure what your issue is.

Closing for now, if you can make a MCVE, I'll reopen.

**Comment by sunny-g** [comment]
Figured it out - I have a nested `@import` wrapped in a `:global` tag, and it isn't being resolved in v9 though it was in v7, which is why it appeared to me to not be recursing: https://runkit.com/sunny-g/5880fcfecea9be001416093e

**Comment by RyanZim** [comment]
@sunny-g Yep, imports have to be at the top in v8+.

**Comment by sunny-g** [comment]
Thanks.
