### ISSUE TITLE
Import CSS files as as a reference to use

### ISSUE THREAD

**Issue by qasimalyas** [postcss/postcss-import#267]
Hi,

Is there an approach to reference a file without actually importing its content? 

In my example I have a css file which is a generated file for icons thats already being used elsewhere lower the css chain. I now need to be able to reference this file earlier up the css file without importing its content. I know this was [raised before](https://github.com/postcss/postcss-import/issues/32) but my use case is different an isn't just variables but classes as well.

thanks

**Comment by RyanZim** [comment]
@qasimalyas I assume you're using postcss-simple-vars. postcss-custom-properties don't have to be defined before they're used IIRC, so that may be something to look into.

I don't think this belongs in postcss-import. Sorry.

CC: @ai
