### ISSUE TITLE
@import won't work (path problem)

### ISSUE THREAD

**Issue by ukaric** [postcss/postcss-import#268]
Hi,

Frankly I have been bashing my head to get `@import` to work like it should for over a day now it works when i set path to `node_modules`  normalize but other than that its not working i saw the `from` option but i need little help in configuring it i use gulp.

Here is my project structure.

![2017-02-10 4](https://cloud.githubusercontent.com/assets/9012882/22809057/f63baaa8-ef2f-11e6-88e0-b23755592c01.png)

Here is the code.
```
const gulp = require('gulp');
const notify = require('gulp-notify');
const path = require('path');
const plumber = require('gulp-plumber');
const postcss = require('gulp-postcss');
const precss = require('precss');
const importcss = require('postcss-import');
const autoprefixer = require('autoprefixer');
const lost = require('lost');
const config = require('../../config').styles;

const preprocessros = [importcss, precss, autoprefixer, lost];

gulp.task('styles', () => {
  gulp
    .src(config.src)
    .pipe(
      plumber({
        errorHandler: notify.onError({
          title: 'Error in Style task.',
          message: '<%= error.message %>',
          sound: 'Notification.IM',
          onLast: true,
          wait: true
        })
      })
    )
    .pipe(postcss(preprocessros))
    .pipe(gulp.dest(config.dest))
    .pipe(
      notify({
        title: 'PostCSS',
        message: 'PostCSS transformation done !',
        icon: path.join(__dirname, '../', 'postcss.png'),
        sound: false
      })
    );
});

```

I would be thankful if someone is to enlighten me how to make `path` option work in my case. 

The issue is that it looks under `C:\Users\uros\Desktop\hugo-site\app\assets\css` folder for node_modules even tho `cwd` is root.

**Comment by RyanZim** [comment]
Please post your `@import` statements from your css, as well as any error messages.

**Comment by kadza93** [comment]
![2017-02-10 5](https://cloud.githubusercontent.com/assets/9012882/22809538/8d95e1ea-ef33-11e6-9369-8beacaf289dd.png)

**Comment by jt3k** [comment]
i have a slightly different problem with `@import`

package.json
![image](https://cloud.githubusercontent.com/assets/1261240/23022545/7f82adde-f462-11e6-9ff5-c516f3ac74e8.png)

webpack-config -- loader
![image](https://cloud.githubusercontent.com/assets/1261240/23022592/b8189672-f462-11e6-8351-c3d683f52a0b.png)

webpack-config  -- postcss method -- section
![image](https://cloud.githubusercontent.com/assets/1261240/23022611/d6621a22-f462-11e6-8960-6ce9ee4a275c.png)

i include my pcss file in js  `import '../styles/common.pcss';`
and in this file i have @import to  other `.pcss` file
![image](https://cloud.githubusercontent.com/assets/1261240/23022799/cc84c058-f463-11e6-9709-ac108edfbb9d.png)

the error:
![image](https://cloud.githubusercontent.com/assets/1261240/23022810/db536c56-f463-11e6-95ba-1eada1f961b7.png)

**Comment by michael-ciniawsky** [comment]
@jt3k Where is `postcss-loader` in `package.json`? 😛 and why is `postcss-scss` installed?

`addDependendcyTo` is deprecated since `postcss-import >= v9.0.0` && `postcss-loader >= 1.0.0` , `@imports are handled automatically now

`[hash:base63:10]` =>  `[hash:base64:10]` or is the 63 on propose?

**Comment by jt3k** [comment]
@michael-ciniawsky thank you! but...

my problem has been solved in another way.

**Comment by RyanZim** [comment]
@kadza93 I cannot reproduce, can you make a minimal repo demonstrating this and give me the GH link?

**Comment by kadza93** [comment]
@RyanZim Here is the [repo](https://github.com/kadza93/bug-import) I made, I stripped everything down to the task that is failing. I'm running `Windows 10 Version 1607 (OS Build 14393.693)`

**Comment by RyanZim** [comment]
@ukaric Your problem is that you have installed https://www.npmjs.com/package/normalize-css; you want https://www.npmjs.com/package/normalize.css instead. :laughing: One typo can make a big problem!

**Comment by RyanZim** [comment]
Anyhow, thanks for reporting, during testing I uncovered a bug in postcss-cli.
