### ISSUE TITLE
webpack 2 problems

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-import#269]
After moving to `webpack 2` from `webpack 1`, i get an error
```shell
ERROR in ./my.scss
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/path/to/fs'
	Error: ENOENT: no such file or directory, open '/path/to/fs'
	Error /loading path/to/fs as "fs" from /path/to/node_modules/extract-text-webpack-plugin/loader.js
 @ multi ./my.js ./my.scss
```
If use `postcss-import 8.*.*` version all works fine.

**Comment by michael-ciniawsky** [comment]
@evilebottnawi For debugging I need the following information please

- package.json (dependencies/devDependencies)
- webpack.confg.js (CSS Loader Config)
- postcss.config.js
- `.scss` file with imports 

The according to the StackTrace the error lies somwhere in `extract-text-webpack-plugin` not `postcss-import`
If you use SASS/SCSS I wonder why you use `postcss-import`. SASS has `@import` handling build in, it's recommended to use it instead, but lets see :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky i have and sass and css together, migration period :smile: tomorrow i can do test repo

**Comment by RyanZim** [comment]
@evilebottnawi ping?

**Comment by evilebottnawi** [comment]
@RyanZim sorry don't have now time, i will try to do in this week :smile:

**Comment by evilebottnawi** [comment]
@RyanZim i can try to solve this problems and find strange behavior - if i comment line https://github.com/postcss/postcss-import/blob/master/lib/resolve-id.js#L5
```js
try {
  // jspmResolve = require("pkg-resolve")
}
catch (ex) {
  // pass
}
```
All works fine. If uncomment i get error above.

**Comment by evilebottnawi** [comment]
@RyanZim found issue about this https://github.com/webpack/webpack/issues/2411#issuecomment-247132992

**Comment by evilebottnawi** [comment]
Solved by https://github.com/webpack/webpack/issues/2411#issuecomment-278639981, btw i think best add option to load `pkg-resolve` or not, it is allow avoid this issue

**Comment by RyanZim** [comment]
@evilebottnawi That whole `pkg-resolve` thing is going to be removed in the next major version. I'm curious why this is causing a problem for you, though. Run `npm ls pkg-resolve` in your project and post the output here. Thanks!

**Comment by evilebottnawi** [comment]
@RyanZim one of global package have dependencies `pkg-resolve` and `require` load this from global context not local.

**Comment by evilebottnawi** [comment]
@RyanZim close issue, solution in https://github.com/postcss/postcss-import/issues/269#issuecomment-291816275
