### ISSUE TITLE
Unable to @import files at the bottom of the css.

### ISSUE THREAD

**Issue by sandiprb** [postcss/postcss-import#270]
I've certain files which I want to import at the bottom in CSS files (simply reason being this imports carry some overrides for certain components) and it's giving warning like `text: '@import must precede all other statements (besides @charset)'` any options to resolve this

**Comment by RyanZim** [comment]
Sorry, postcss-import does not support `@import` statements anywhere but at the top of the CSS.

As a workaround, you could make a file like this:
```css
@import "base.css";
@import "overrides.css";
```
Where `base.css` is your main CSS, and `overrides.css` is the file you want to import at the bottom.

**Comment by partyka1** [comment]
Why this isn't noticed in documentation?

**Comment by RyanZim** [comment]
@partyka1 It is documented in the README:

> - **This plugin attempts to follow the CSS `@import` spec**; `@import` statements must precede all other statements (besides `@charset`).

**Comment by partyka1** [comment]
My mistake, I have searched for it in readme.md, but somehow I didn't find it. I can agree, that generally it's not good practice to put @import's in different places in css file, but when working with legacy code, maybe option to turn off such restriction would be useful?

**Comment by RyanZim** [comment]
Sorry, due to the way postcss-import works, such an option is impossible to implement.
