### ISSUE TITLE
v9.1 + pkg-resolve = Module not found

### ISSUE THREAD

**Issue by bytasv** [postcss/postcss-import#276]
Hello,

I read issues section I noticed that `pkg-resolve` was supposed to be removed in major version. However I still see it that:
```javascript
try {
  jspmResolve = require("pkg-resolve")
}
catch (ex) {
  // pass
}
```
in `resolve-ids` exists.

I'm not sure why, but I'm getting this error:
```
/Users/____/webpack/build.js:29
      throw new _gulpUtil2.default.PluginError('webpack', buildError);
      ^
Error: ./~/postcss-import/lib/resolve-id.js
Module not found: Error: Can't resolve 'pkg-resolve' in '/Users/_____/node_modules/postcss-import/lib'
resolve 'pkg-resolve' in '/Users/____/node_modules/postcss-import/lib'
  Parsed request is a module
```

I found some issues linking to webpack but I think I already tried all options that I can find with no success.

Isn't this suppose to be fixed at `postcss-import` level?

**Comment by RyanZim** [comment]
> Isn't this suppose to be fixed at postcss-import level?

It's supposed to be.

Run `npm ls pkg-resolve` and post the output here.

**Comment by bytasv** [comment]
@RyanZim so this is inside application:
```
 butkus@...  ~/___   master ✚ ● ?  yarn why pkg-resolve                                                                                 1 ↵  1719  18:07:29
yarn why v0.21.3
[1/4] 🤔  Why do we have the module "pkg-resolve"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.88s.
 butkus@...  ~/___   master ✚ ● ?  npm ls pkg-resolve                                                                                     ✓  1720  18:09:59
application@ /Users/butkus/___
└── UNMET PEER DEPENDENCY eslint@3.19.0

npm ERR! peer dep missing: eslint@^2.9.0, required by eslint-config-airbnb@9.0.1
```

And I get the same in module directory as well

**Comment by RyanZim** [comment]
OK, delete `node_modules` and reinstall. See if that helps.

**Comment by bytasv** [comment]
@RyanZim I've tried it multiple times, it didn't help. However I don't see how that could help, since the code snippet (that I pasted) is located in `postcss-import` package. I actually tried to remove that snippet, but then I got similar error because `sugarss` is being fetched the same way... Really confused what's going on and how to fix it. And why is it working in another setup... :)

**Comment by RyanZim** [comment]
> the code snippet (that I pasted) is located in postcss-import package.

Yeah, that snippet is in the postcss-import package, however, it doesn't list `pkg-resolve` as a dep. It only loads it if it's available. Your output from `npm ls` doesn't jive with the error messages you're getting.

Try making a minimal reproducible example, push it to a GH repo, and post the link here. I'll try to take it from there. I'm afraid that's the only way I can figure this out.

**Comment by RyanZim** [comment]
@bytasv ping?

**Comment by bytasv** [comment]
@RyanZim I've got carried away with other work that I had to continue before doing this. Will try to make an isolated case soon and will ping you back

**Comment by RyanZim** [comment]
Hey, we changed things around; this should be fixed in v10.
