### ISSUE TITLE
Recursive imports fail silently, transpile empty CSS

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss-import#278]
With the following configuration options:

```js
{
  path: ['blocks']
}
```
And a folder structure like this:
```
styles
├── blocks
│   ├── foo.css
│   ...
├── foo.css
...
```
If I have a file at `styles/foo.css` that looks like this:
```css
@import 'foo';
```
It transpiles an empty CSS file w/o errors.

As a work-around, I can do this:
```css
@import 'blocks/foo';
```
But I'm kinda' thinking this should throw an error!

**Comment by RyanZim** [comment]
Ugh, I never use `path` myself. What happens if you `path.resolve` `'blocks'`?

**Comment by jedmao** [comment]
The path is not the problem. It resolves just fine. The problem is the recursive import, since they are both named foo.

**Comment by RyanZim** [comment]
Ah, OK; I'll look into this as soon as I get a chance.

**Comment by RyanZim** [comment]
Hey there, I'm terribly busy. If you can, a reduced test case repo on GH would sure help me get around to this faster.

**Comment by jedmao** [comment]
@RyanZim, see #280

**Comment by RyanZim** [comment]
See https://github.com/postcss/postcss-import/pull/280#issuecomment-298134082

**Comment by jedmao** [comment]
Excellent! I just need to reorder my paths!
