### ISSUE TITLE
Nested imports have wrong path

### ISSUE THREAD

**Issue by FezVrasta** [postcss/postcss-import#279]
```
/component1/index.sss
/component2/index.sss
```

```
// component1
@import '@scope/module/file.sss'
```

```
// component2
@import '../component1/index.sss'
```

The `component2` will throw an error:

```
Module build failed: Error: ENOENT: no such file or directory, open '/Users/FezVrasta/app/component2/@scope/components1/index.sss'
```

**Comment by RyanZim** [comment]
Might be related to https://github.com/postcss/postcss-import/issues/278, IDK. Can you make a test case repo?

**Comment by FezVrasta** [comment]
#278 doesn't throw an error at all. I don't know if it's related, I'll try to create a repro.

**Comment by michael-ciniawsky** [comment]
Are scope npm packages supported by node-resolve ? Does this also happen with a non-scoped npm package ?

> ** no such file or directory, open '/Users/FezVrasta/app/component2/-->@scope <--/components1/index.sss' **

btw don't use `@import` with webpack, it will bloat your code base 😉

**Comment by FezVrasta** [comment]
Looks like I had to manually define the `root` parameter to make it work properly. I thought it would have used `process.cwd()` by default but seems like it's not the case.

Is this a bug or the expected behavior?

**Comment by RyanZim** [comment]
> Reading the docs, it should already set it to process.cwd().

Actually not set to that in most cases; from the docs:

> Default: process.cwd() or dirname of the postcss from

So it's `path.dirname()` of your input file in most cases. What postcss runner are you using, and where is your input file located?

**Comment by FezVrasta** [comment]
I'm on an app based on `create-react-app` and ejected. So, webpack mostly.

**Comment by RyanZim** [comment]
It has something to do with your directory structure. In your case, you're probably best off just setting `root`.

**Comment by FezVrasta** [comment]
I see, thank you for the support!
