### ISSUE TITLE
Node#before is deprecated. Use Node#raws.before

### ISSUE THREAD

**Issue by francoisromain** [postcss/postcss-import#286]
Hello
When I use `postcss-import` and then `postcss-next`, there is this warning in the console:

`Node#before is deprecated. Use Node#raws.before`

I made a repo to reproduce here:
https://github.com/francoisromain/test-postcss-import-cssnext

**Comment by michael-ciniawsky** [comment]
https://github.com/MoOx/postcss-cssnext/issues/374 (Issue)
https://github.com/MoOx/postcss-cssnext/pull/384 (PR)

`postcss-import >= 10.0.0` shouldn't cause this and supports PostCSS v6

Can be closed 😛

**Comment by lemmon** [comment]
I am still getting this even with latest postcss versions:

```
"postcss": "^6.0.5",
"postcss-cssnext": "^2.11.0",
"postcss-import": "^10.0.0"
```

**Comment by julmot** [comment]
Me too.

**Comment by francoisromain** [comment]
Is it related to this: https://github.com/jonathantneal/postcss-nesting/issues/38 ?

**Comment by julmot** [comment]
It's the same error. Since the message doesn't include a plugin name, it could be any postcss plugin.

**Comment by RyanZim** [comment]
If you're using postcss-cssnext, you're going to get this error until postcss-cssnext is updated. Period. Locking since this isn't a postcss-import issue.
