### ISSUE TITLE
How do you configure postcss-import in vue-cli?

### ISSUE THREAD

**Issue by wuhuanhost** [postcss/postcss-import#291]

**Comment by wuhuanhost** [comment]
### app.vue
![image](https://user-images.githubusercontent.com/2606813/26869104-c6a3588e-4b9d-11e7-933e-feb0dbad2a1e.png)

### vue-loader.conf.js
![image](https://user-images.githubusercontent.com/2606813/26869145-f159bb54-4b9d-11e7-9873-d842290bb61f.png)

### test.css
![image](https://user-images.githubusercontent.com/2606813/26869179-198d6724-4b9e-11e7-89e9-3f2588413e80.png)

> `nom run dev ` after fter the operation error
![image](https://user-images.githubusercontent.com/2606813/26869248-60717126-4b9e-11e7-9342-dcc5e644fdf0.png)

How do you use postcss-import in vue-cli?

**Comment by RyanZim** [comment]
Sorry, not familiar with vue.js. Perhaps try asking on stackoverflow.com?
