### ISSUE TITLE
importing creates hundreds of duplicates

### ISSUE THREAD

**Issue by bradennapier** [postcss/postcss-import#294]
I have a situation where I 'have' to import a file in EVERY single css file in my entire app.  This is because you get thousands of errors if you try to use css variables and haven't imported the file that defines the variables in that specific css file in question.

```
@import "styles/theme";
```

The problem is that every single time I do that it creates another `:root`.  Chrome doesn't seem to slow down much but safari is taking about 10-15 mintues just to load a list of available styles because it appears to be bogged down by this?  There are some situations that I get to hundreds of :root with all the same variables declared over and over and over.

![image](https://user-images.githubusercontent.com/15365418/27204814-108b9336-51e2-11e7-8ba1-d14646e8dec2.png)

**Comment by michael-ciniawsky** [comment]
What build tool are you using? Do you need the custom properties available for any other postcss plugin?

**Comment by bradennapier** [comment]
Webpack 2.  I feel it could be due to a few things I am doing but it's obviously a pretty annoying issue :).  The biggest problem is that I need to include the theme file in every single css file because otherwise i get tons of errors from the custom properties that expects the file itself to have the :root with variables and fallbacks

```
module.exports = {
  plugins: [
    require('postcss-import')({
      addModulesDirectories: [
        'shared'
      ]
    }),
    require('postcss-simple-vars'),
    // require('postcss-import')({}),
    require('postcss-cssnext')({
      browsers: [ 'last 2 versions', '> 5%' ],
      features: {
        customProperties: {
          preserve: true
        }
      }
    }),
    require('postcss-simple-vars'),
    require('postcss-inline-media'),
  ]
}
```

**Comment by michael-ciniawsky** [comment]
Pass the variables to the plugin instead :) https://github.com/postcss/postcss-custom-properties#variables (used by cssnext)

In general && if avoidable I recommend to **not** use `@import` at all in conjunction with webpack can bloat your CSS significantly in some cases. E.g for frameworks like bootstrap it is better to add an additional `<link>`. Most of the time keeping the CSS strictly scoped to the component is the less painful solution, it's a shift in mind compared to the 'traditional' approach of writing CSS, but in the common way will have a hard time getting it 'right' 😛.

```css
.component {
    display: flex;

    &__x {
      flex: 1 1 50%;
    }

    &--y {
      color: red;
    }
}
```

Finally if you _really_ need to rely on `@import` use `css-loader`'s `importLoaders` instead  of `postcss-import` , which will make a separate request webpack can dedupe to some point

`@import 'path/to/file.css'` => `importLoaders` => `require('css-loader!postcss-loader!./path/to/file.css')`

**Comment by bradennapier** [comment]
Yeah I am using css-modules and its been a dream but it def has its major drawbacks in terms of implementing certain behaviors.

**Comment by SuperOl3g** [comment]
In my case problem with using css-loader's `@import` parsing is that `css-loader` is going after `postcss-loader`. So postcss plugins runs without variables which are imported on the next step.

**Comment by fredericgrati** [comment]
I have the same pb @SuperOl3g. Did you find a solution ?

**Comment by RyanZim** [comment]
Closing for lack of action.
