### ISSUE TITLE
Any chance to skip the precede check by option?

### ISSUE THREAD

**Issue by jackysee** [postcss/postcss-import#295]
I try to include `postcss-normalize`, which gives you the benefit of browsers-targeted `normalize.css` code. 

```css
@import-normalize;
@import "base.css";
```
But in the above case `postcss-import` would complain about it and just output the `normalize.css` code.
To workaround it, I have to create a 'normalize.css'
```
@import-normalize;
```
And then import it
```css
@import "normalize.css";
@import "base.css";
```
Should there be an option to turn off the precede check?

**Comment by RyanZim** [comment]
Man, that's an ugly one I never thought of. However, I don't think it's possible to get around this due to the way postcss-import works. I'll do a little thinking and get back to you (ping me if I don't).

**Comment by unregistered** [comment]
Any update on this? I've been looking for the same feature for doing imports within nesting statements like sass supports.

```
.parent {
  @import 'parent-styles';
}
```

**Comment by RyanZim** [comment]
@unregistered That kind of stuff postcss-import cannot & will not support.

**Comment by RyanZim** [comment]
Sorry so long. For now, I can't think of anything better than the `normalize.css` workaround. If someone can figure out something better, please let me know.

**Comment by UncleBill** [comment]
>Man, that's an ugly one I never thought of. However, I don't think it's possible to get around this due to the way postcss-import works.

 Add an option to enable the skipping, leave the ugly thing to the developer who wants this. 
I would like to have this feature! `postcss-import` is kind of preprocessing, so it could not follow the preceding spec.
