### ISSUE TITLE
nesting import

### ISSUE THREAD

**Issue by ksjogo** [postcss/postcss-import#296]
What would need to be done to support scoped imports e.g.:
```
my-scope {
	@import "scoped-stuff";
}
```
It looks like the parser code is only checking statements on top level, which is a bit weird, as that results in no warning given when using this code.

**Comment by RyanZim** [comment]
From the readme:
> - **This plugin attempts to follow the CSS `@import` spec**; `@import` statements must precede all other statements (besides `@charset`).

We can't support nested imports due to the way the plugin works.

postcss-import is slow enough the way it is; doing a full recursive walk just to warn about incorrect import statements is going to have non-trivial performance impact.

**Comment by roblevintennis** [comment]
If in my application I have a file within `app/assets/stylesheets` that has an import like:

`@import "some-npm-module/src/styles/icons";`

and that file in turn has an import like:

`@import './typography.css';`

I notice that the source file will still be: `app/assets/stylesheets/first-file.css` and thus the relative `./` import won't be found e.g. in my real scenario I'm getting errors like:

```shell
    ERROR in ./app/assets/stylesheets/internal-base.scss
    Module build failed: ModuleBuildError: Module build failed: Error: Failed to find './typography.css'
      in [
        /Users/roblevin/workspace/mavenlink/app/assets/stylesheets,
            /Users/roblevin/workspace/mavenlink/node_modules/@mavenlink/design-system/src/styles
      ]
        at resolveModule.catch.catch (/Users/roblevin/workspace/mavenlink/node_modules/postcss-import/lib/resolve-id.js:39:13)
```

even though typography.css is right beside the file that's importing it:


```shell
$ tree src/styles/
src/styles/
├── colors.css
├── icons-vars.css
├── icons.css
└── typography.css
```


So I'm taking

> We can't support nested imports due to the way the plugin works.

as a confirmation that, yes, it won't "follow imports" to consider whatever file is being processed in determining what's relative. I manually logged out the source files from `parseImport` and they were always the top level file e.g. the one in `app/assets/stylesheets` regardless of what file the import statement actually resided.

I suppose I'm restating what you said, but I'm just hoping to be crystal clear that I'm understanding how the plugin works. Thanks!

**Comment by RyanZim** [comment]
The nested imports I was referring to was having an `@import` statement inside a block of CSS, not nested imports you're describing. Please open a new issue if you need help.
