### ISSUE TITLE
Filtering imports

### ISSUE THREAD

**Issue by hirokiosame** [postcss/postcss-import#297]
I'd like to be able to filter (with whitelist/blacklist/custom-function) the files that are imported by postcss-import so that certain files can be resolved by the webpack css-loader instead (eg. for unique modules). I tried passing in a `load` function but I may be doing it incorrectly:
```
require('postcss-import')({
	load: (function () {

		const loadContent = require('postcss-import/lib/load-content');

		return function (filename, options) {
			if (filename.match(/module-for-css-loader/)) {
				return `@import "~module-for-css-loader";`;
			}

			return loadContent(filename, options);
		};
	})(),
}),
```

**Comment by RyanZim** [comment]
> so that certain files can be resolved by the webpack css-loader instead (eg. for unique modules)

I'm not sure I'm understanding why you need to use the webpack css-loader?

**Comment by hirokiosame** [comment]
@RyanZim 

I have a shared var file that loads the fonts it uses. Every file I have imports this var file and because postcss-import inlines them, it gets duplicated for every usage (this bloats the file with the fonts for every time the vars are imported). If this is handled via css-loader, the dependencies are resolved by Webpack, and duplicates will be prevented.

**Comment by RyanZim** [comment]
postcss-import itself dedupes files; not sure what you're doing in your config. @michael-ciniawsky can you provide some insight here perhaps?

**Comment by michael-ciniawsky** [comment]
@hirokiosame Why do you need `postcss-import` in your setup, as you stated `css-loader` handles `@import` the 'webpack way'  (`@import 'file.css' => require('css-loader!postcss-loader!./file.css')`) for you to avoid duplicates in your CSS, since ever webpack works 'only' on JS files

That aside what you are looking for is this (https://github.com/postcss/postcss-import/pull/259) (ignore the `beforeImport`) it should be implemented as e.g `options.filter` to `@import` some files via `postcss-import`  and let the rest fallthrough to `css-loader`. Would be highly appreciated if you finish this PR is guess 😛

> :warning: I don't recommend to use `postcss-import` + webpack, it's just not working that way there. CSS is awkward with webpack and every `@import` is one too much, avoid them altogether at best and try to scope the CSS explicitly to the file whenever possible :). E.g use `postcss-custom-properties` to enhance the PostCSS AST with 'global' variables instead of `@import` them

**Comment by hirokiosame** [comment]
@RyanZim postcss-import dedupes files when it is the one resolving it, however, in my situation, there are multiple postcss entry points because I am using Vue to create components.

@michael-ciniawsky Here's a very reduced and simplified version of my repo:

__font-effra.css__
```
@font-face {
	font-family: effra;
	font-style: normal;
	font-weight: 300;
	src:
		url("/fonts/effra/effra-light-webfont.woff2") format("woff2"),
		url("/fonts/effra/effra-light-webfont.woff") format("woff");
}
```

__vars.css__
```
@import "font-effra.css";

:root {
	--heading-d1-size: 56px;
	--heading-d2-size: 44px;
	--heading-d3-size: 32px;
	--heading-t1-size: 24px;
	--heading-t2-size: 20px;
	--heading-t3-size: 16px;
	--heading-t4-size: 14px;
	--heading-t5-size: 12px;
}
```

__ComponentA.vue__
```
<template>
...
</template>

<script>
...
</script>

<style>
@import "./vars.css"

.component-a {
	font-size: var(--heading-d1-size);
	...
}
</style>
```

__ComponentB.vue__
```
<template>
...
</template>

<script>
...
</script>

<style>
@import "./vars.css"

.component-b {
	font-size: var(--heading-d1-size);
	...
}
</style>
```

__index.js__
```
export { default as ComponentA } from 'ComponentA.vue';
export { default as ComponentB } from 'ComponentB.vue';
```

The Webpack configuration exports `index.js` and uses `ExtractTextPlugin` to produce an `index.css` out of it. `index.css` has the font base64 inlined twice because the respective components import them separately (in isolation). If postcss-import can ignore `@import "font-effra.css";` and let Webpack handle it via css-loader, the duplication won't happen.

I imagine this quite an edge-case, so sorry for the lack of explanation earlier on.

https://github.com/postcss/postcss-import/pull/259/files looks to be no longer maintained. Would you mind if I pick it up to make the requested changes in the PR?

**Comment by michael-ciniawsky** [comment]
If you use CSS Custom Properties without a fallback, just import them into ìndex.js

**index.js**(`App.js`)
```
import vars from './vars.css' // works like an @import to index.css
import fonts from './fonts.css' // works like an @import to index.css

import Component1 from '.component1.vue'
import Component2 from '.component2.vue'
import Component3 from '.component3.vue'
```

> https://github.com/postcss/postcss-import/pull/259/files looks to be no longer maintained. Would you mind if I pick it up to make the requested changes in the PR?

Of course 😛 always appreciated :)

**Comment by hirokiosame** [comment]
@michael-ciniawsky Not sure what you mean but I am already using `postcss-custom-properties` via cssnext. Since every Vue component is being built as an entrypoint (basically in isolation), they each need to import var and the font respectively.

Anyway, here's the PR :)
https://github.com/postcss/postcss-import/pull/299

Thanks so much for the support
