### ISSUE TITLE
Importing Fails After Concatenating Files

### ISSUE THREAD

**Issue by trisys3** [postcss/postcss-import#298]
Sorry for the complicated title, I just have no idea why this is happening, and it is very specific. I am also not sure if it is happening in `postcss-import` or somewhere else, but it triggers with `postcss-import` so I figured I would add it here.

The basic issue seems to be that if I have any imports in my `app.css`, and concatenate that with another file that is in another folder, I get an error saying `postcss-import` could not find the imported file, even if the imported file exists. This only happens if the concatenated file was changed after `app.css`, which does not seem to make sense as I have no caching specifically turned on. Does `postcss-import` do any caching? I notice `resolve-id.js` in the error message (see below), but `postcss-import` should not care about the order files were created/modified, right?

Subset of gulp-specific configuration:

```
const concat = require('gulp-concat');
const postcss = require('gulp-postcss');
const atImport = require('postcss-import');

gulp.src(['app.css', 'themes/concatenated.css'])
    .pipe(concat(app.css))
    .pipe(postcss([atImport()]));
```

app.css only needs a single import statement. Whether or not that points to an existing file, you get an error, but to get the error I am seeing the imported file needs to exist. For example:

```
@import 'imported.css';
```

Both `imported.css` and `concatenated.css` need to exist but can be empty.

The error I am getting is:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: Failed to find 'imported.css'
    in [
        /path/to/repository/themes
    ]
    at /path/to/repository/node_modules/postcss-import/lib/resolve-id.js:48:11
    at <anonymous>
```

To get the error, `app.css` needs to have been changed *after* `concatenated.css`. If `concatenated.css` was changed after `app.css`, even if `imported.css` was changed after `concatenated.css`, I get the error. Finally, `concatenated.css` needs to be in a different folder from `app.css`. If they are both in the same folder, I never get the error even if I never change `concatenated.css`.

What the heck is going on here?

**Comment by michael-ciniawsky** [comment]
1. `concat` && `@import` are interchangeable approaches for nearly the same thing. Why not just `@import concatened.css` ?

2. Use `gulp-concat` **after** `gulp-postcss` to resolve all `@import` s first (`@import` needs to be at the top of the file) => `@import x.css ...css` (1.css) concat `@import  y.css ...css` (2.css) => Error

Its seems the @import simply fails because the path is wrong, `postcss-import` by default imports files relative to `path.dirname(file)` of the current file being processed by `gulp`

**Comment by trisys3** [comment]
I can't import the concatenated file because the path has a variable in it. Preprocessors usually allow this, but `postcss-import` does not, and I couldn't find any other way to add variables to import statements.

Variables are also the reason I can't use `gulp-postcss` after `gulp-concat`. As far as I can tell, `cssnext` always warns on variables without values, even if the values come later. I could look into having `cssnext` run without variables, then having just the variable plugin run after concatenation.

The path is correct. As I said, this works if `app.css` is changed after `imported.css`.

**Comment by trisys3** [comment]
I updated the issue. Apparently, another factor to this is that the main CSS file & the file that gets concatenated at the start need to be in different folders, which I did not realize.

**Comment by RyanZim** [comment]
Closing for lack of action.
