### ISSUE TITLE
rebase assets url

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-import#3]
available only if "to" option has been provided

**Comment by iamvdo** [comment]
Why not include `postcss-url` inside `postcss-import` as an option ? It would a great addition.
Related iamvdo/pleeease#34

**Comment by MoOx** [comment]
You can just chain import & url plugins for now.
I've to admit cssnext is facing the same problematic https://github.com/cssnext/cssnext/issues/57
Not sure what will be the real benefit of doing that in this plugin.

**Comment by iamvdo** [comment]
>I've to admit cssnext is facing the same problematic

Yes, this is the reason why I think that include `postcss-url` inside `postcss-import` is a good idea. When importing files, there are many chances that included paths will be wrong.

But you're right, we can chain plugins.

**Comment by jasonkuhrt** [comment]
@iamvdo Does this make sense to you? https://github.com/cssnext/cssnext/issues/57#issuecomment-71674245
