### ISSUE TITLE
Does it work in webpack's watch mode?

### ISSUE THREAD

**Issue by ennovum** [postcss/postcss-import#302]
Hi. Should the plugin work with webpack's watch mode? In my case when I run webpack, the `import` plugin works alright. But after the first rebuilding (file changed) the `@import`s are not inlined anymore. Is it a known issue?
[EDIT]
Here is my setup:
https://github.com/ennovum/kickoff

**Comment by michael-ciniawsky** [comment]
`postcss-load-config` loses context with your current setup, this worked in `watch` mode

**postcss.config.js**
```js
const env = require('./env'); // Can be removed if you use the postcss.config.js params instead :)

module.exports = ({ file, options, env }) => ({// env == NODE_ENV (by postcss-load-config)
  plugins: {
    'postcss-import': {
      root: env.rootDir, // file.dirname (?) => Always relative to processed file
      path: env.srcDir,
      skipDuplicates: true
    },
    'postcss-extend': {},
    'postcss-mixins': {},
    'postcss-cssnext': {
      browsers: ['last 2 versions', '> 5%'],
    },
    'stylelint': env === 'development'  ? {} : false,
    'cssnano': env ==='production' : {} : false
  }
})
```

I recommend this config structure in general 😛 

```
|-.webpack
| |- resolve.js
| |– module.js  // => loaders (rules)
| |– plugins.js
| |– server.js
|
|– src
|
|– package.json
|– webpack.config.js
|– postcss.config.js
```

**.webpack/loaders.js**
```js
const rules = (env, paths) => ({
  rules: [
    ...loaders
  ]
})

module.exports = rules
```

**webpack.config.js**
```js
const env = process.env.NODE_ENV

const argv = process.argv[2] // optional for reusable 'paths.root'

const paths = {
  root: ... || argv,
  src: ...
}

// .webpack Config Parts => {Function} 
const resolve = require('./.webpack/resolve')
const modules = require('./.webpack/module')
const plugins = require('./.webpack/plugins')
const server = require('./.webpack/server')
...

module.exports = {
  ...
  resolve(env, paths)
  module: modules(env, paths),
  plugins(env, paths),
  devServer: env === 'development' : server : {}
  ...
}
```

Anyways this issue can be closed as unrelated to `postcss-import` which works correctly

**Comment by RyanZim** [comment]
Closing as I assume @michael-ciniawsky's webpack knowledge is correct; he's the resident webpack expert.

**Comment by ennovum** [comment]
> `postcss-load-config` loses context with your current setup

@michael-ciniawsky, is there any particular reason why it happens? Should I create an issue in `postcss-load-config` now?

As you can see I do have both `webpack.config.js` and `postcss.config.js`, only they depend on my common `buildconf`. Is there something wrong with this approach?

BTW all the other `postcss` plugins work in the watch mode.

**Comment by ennovum** [comment]
I created the issue with some new findings:
https://github.com/michael-ciniawsky/postcss-load-config/issues/105

**Comment by ennovum** [comment]
@RyanZim this one can be closed. Thanks for all the help!
