### ISSUE TITLE
Problem with webpack, css-loader, postcss-import and referenced resources

### ISSUE THREAD

**Issue by ChristophM2000** [postcss/postcss-import#304]
I have a problem with webpack, css-loader, postcss-import and referenced resources like images or fonts.
I’m using React in my project.
I‘m using for all components the newest released version.
 
My simlpified file structure looks like this:
```
/
|- fonts
    |- font.woff
|- fonts.css
|- components
    |- layout
        |- index.css
        |- index.js
``` 

fonts.css contains the `@font-face`s rules and has relative urls to the fonts in fonts dir.
`@font-face {… url('./fonts/font.woff ' …);`
 
Now I import the font.css file via `@import '../../fonts.css'` into components/layout/index.css. That index.css is than imported in index.js via `import fonts from  './index.css';`
 
webpack.config.js css rule:
```js
{
    test: /\.(css)$/,
    use: [
        "style-loader",
        {
            loader: "css-loader",
            options: {
                modules: true, importLoaders: 1
            }
        },
        "postcss-loader"
    ]
}
```

postcss.config.js:
```js
module.exports = {
    plugins: [
        require('postcss-import'),
        require('postcss-cssnext'),
    ]
}
```

My problem is that webpack throws this error on build:
```
Module not found: Error: Can't resolve './font.woff' from components/layout/.
```

The problem is that postcss-import inlines the fonts.css into index.css without modifiing the paths to font.woff, so it is obvious that it does not find the file.
If I remove the postcss-loader the import processing is done by webpack css-loader, and that takes care of modifiing the font.woff path, and it works.
 
Why postcss-import does not modify the paths of external resources when it inlines css and what is the  recommended solution?
 
Greetings,
Christoph

**Comment by michael-ciniawsky** [comment]
It's better to use `css-loader` here, bc each `@import` becomes a module request and `url`s are handled to some point, otherwise you will need something like `postcss-url` to rewrite the asset paths or hardcode the correct path (which can easily become confusing when the project grows). The issue can be closed as this is a webpack specific thing unrelated to `postcss-import` directly

**Comment by ChristophM2000** [comment]
The reason I use postcss-import is that I also use postcss-cssnext and have global variables defined in a variables.css that I need to import in all of my css files. And because cssnext needs to work with these values like color modifications, the variables need to be accessible in that stage.

So the only solution for me is to correct the strange behavior by myself?

**Comment by michael-ciniawsky** [comment]
`postcss-cssnext`  can enhance the PostCSS AST with the vars (`variables.json`) instead

**Comment by michael-ciniawsky** [comment]
https://github.com/postcss/postcss-custom-properties#variables

**Comment by RyanZim** [comment]
You need to use postcss-url after postcss-import. https://github.com/postcss/postcss-url

**Comment by ChristophM2000** [comment]
Thank you very much, ich solved it via postcss-custom-properties variables. That way I could completely get rid of the postcss-import.
