### ISSUE TITLE
[Webpack] Imported files do not trigger a reload when updated

### ISSUE THREAD

**Issue by sbaechler** [postcss/postcss-import#308]
Whenever I change a css file in my project which is not the root css file, Webpack does not trigger a reload.

I have tested this with Webpack 2 and 3. I have also tried out most workarounds that I have found on the web although most of them are for older versions of postcss and postcss-import.

I have created a very simple project where the issue can be reproduced:
https://github.com/sbaechler/test-import

A change of the styles in 'left.pcss' or 'right.pcss' should trigger a recompile but it doesn't.

**Comment by RyanZim** [comment]
@michael-ciniawsky any chance you could look at this?

**Comment by michael-ciniawsky** [comment]
```diff
const path = require('path');

const basePath = path.dirname(__dirname);


module.exports = ({ file }) => ({
    plugins: {
        'postcss-import': {
            root: file.dirname,
        },
        'postcss-cssnext': {
            browsers: [
                'last 2 versions',
                '> 5%',
                'iOS >= 10.0',
                'not ie <= 11',
            ],
        },
        'postcss-reporter': {
-          clearAllMessages: true,
            clearReportedMessages: true,
            throwError: false,
        },
    },
});
```

**Comment by michael-ciniawsky** [comment]
This option removes the `message.dependency` `postcss-loader` needs/uses to add `@import`'s to webpack

**Comment by RyanZim** [comment]
Thanks @michael-ciniawsky.

@sbaechler If you're clearing all the messages, that will break it. postcss-import sends messages that aren't shown, but are used by postcss-loader so postcss-loader knows what files to watch. Closing as per @michael-ciniawsky's diff.

**Comment by sbaechler** [comment]
@michael-ciniawsky Awesome, thank you.
