### ISSUE TITLE
Newlines added after comments

### ISSUE THREAD

**Issue by psren** [postcss/postcss-import#310]
I found a little problem with this library and my tests fail if i enable your plugin.
I have to use it in my tests, because i depend on the functionality by postcss-import.

Some newlines get added after comments.
Is this intended behavior?

```diff
 - Expected
    + Received

    @@ -1,9 +1,11 @@
     .jim { display: block; }

     /* @important(start) */
    +
     .john { display: block !important; }
    +
     /* @important(stop) */

     .joe {
         /* @important(start) */
         display: block !important;
    @@ -13,11 +15,13 @@
```

**Comment by RyanZim** [comment]
Please post a minimal, reproducible, test case repo demonstrating this behavior.

**Comment by RyanZim** [comment]
Closing for lack of response.
