### ISSUE TITLE
add an option to override completely modulesDirectories

### ISSUE THREAD

**Issue by jorrete** [postcss/postcss-import#312]
Hello,
My use case it's that I need to control totally the include paths and because node_modules it's always included (first) it causes me some problems.
Sometimes (while developing locally) I want to pass the local folder of my styles while there is a copy in node_modules. When I do that I take care to make sure the order of include paths (loca, node_modules) so I can see the changes without need to update the packages. But because node_modules it's always included first I can't do that.
Thanks.

**Comment by RyanZim** [comment]
@jorrete You'll need to pass a custom resolve function to do this: https://github.com/postcss/postcss-import#resolve.
