### ISSUE TITLE
Webpack watch mode breaks on error in imported file

### ISSUE THREAD

**Issue by eknkc** [postcss/postcss-import#313]
Hi,

It seems that with postcss-loader and postcss-import, webpack watch mode works as expected. Changes on imported files are watched properly, however if there is a syntax error on imported file then watch mode stops working. Changes on the imported file does not trigger a recompilation.

Any ideas?

`webpack 3.6.0, postcss-import 11.0.0, postcss-loader 2.0.8`

**Comment by RyanZim** [comment]
@michael-ciniawsky ping?

**Comment by michael-ciniawsky** [comment]
I need a project for reproduction please

**Comment by RyanZim** [comment]
Closing for lack of response.
