### ISSUE TITLE
please resolve @imports as css-loaders and html-loaders

### ISSUE THREAD

**Issue by melonHuang** [postcss/postcss-import#318]
I use postcss-cssnext in the project. And when I try to share css variables through files,  I have to use postcss-import before postcss-cssnext.

Webpack's css-loader and html-loader uses the approach of denoting a module prefix with a `~`
But postcss-import doesn't apply the same rule.

So if I want to use postcss-import, I have to stand with the inconsistency of resolveing rules.
eg. 
```
<!-- refering image.jpg in html -->
<img src="~module/image.jpg" >

// refering image.js in css when using postcss-import rules
background: url(module/image.jpg)
```

I thinks it's better if postcss-import apply the same rule of css-import and html-import. Because most of the time we need to use them.

**Comment by michael-ciniawsky** [comment]
Use `css-loader`'s `importLoaders` options and let `css-loader resolve your `@import`'s instead please (remove `postcss-import` enterily). `postcss-import` should by no means implement this webpack specific weirdness and the `~` is deprecated anyways to my knowledge

**Comment by melonHuang** [comment]
`importLoaders` works fine when using the autoprefixer plugins in postcss. But it won't work when trying to share css variables. 

eg.
```
/* main.css */
@import './color.css'
body {
    background: var(--bgColor);
}
/* color.css */
:root {
    --bgColor: #eee;
}
```

This will throw error `Unable to parse color from string "var(--bgColor)"`

So I give up defining variables in css files, and define them in the cssnext's config file, which is not that elegant because each time I want to modify a variable I have to look for and edit the config file and restart the compiler.
```javascript
require('postcss-cssnext')({
  features: {
    customProperties: {
      bgColor: '#eee'
    }
  }
})
```

Do you have any better ideas?

**Comment by michael-ciniawsky** [comment]
You can use a `postcss.config.js` file and require the variables there since this file will be watched when variables are edited. Otherwise until browsers support isn't mature enough this is the least complicated method to pass variables I'm aware of
