### ISSUE TITLE
Simple example of using postcss-import as a task in gulp

### ISSUE THREAD

**Issue by DjonyBastone** [postcss/postcss-import#319]
Please show a simple example of using postcss-import as a task in gulp. 
"gulp-postcss": "^7.0.0", "postcss-import": "^11.0.0" - with these versions of the documentation can't reproduce

I found an example for "gulp-postcss": "^5.1.10", "postcss-import": "^6.2.0" - it works:
```
gulp.task('css', function () {
	var processors = [
		atImport
	return gulp.src('./src/*.css')
		.pipe(postcss(processors))
		.pipe(gulp.dest('./dest'));
});
```

By analogy made for new versions - does not work

**Comment by michael-ciniawsky** [comment]
The standard gulp setup didn't really change, could you provide more info about what exactly doesn't work ? You may need to provide the correct `root`  for `postcss-import` via a callback, but that entirely depends on your setup && file structure 

```js
gulp.task('css', () => {
    // callback to access the current 
    // vinyl-file processed by gulp
    const config = (file) => ({
        plugins: [
            require('postcss-import')({ root: file.dirname })
        ]
    })
    
   return gulp.src('./src/*.css')
    .pipe(postcss(config))
    .pipe(gulp.dest('./dest'));
})
```

But that's an 'advanced' setup, yours should basically work just fine. I guess `@import` paths are wrong somewhere

**Comment by DjonyBastone** [comment]
file structure:
```
/
|_src 
|    |_css
|        |_block
```
The import files are in the folder /src/css
The imported files are in the folder /src/css/block

The contents of the file /src/css/index.css : 
`@import "/src/css/block/body.pcss";`

The contents of the file /src/css/block/body.pcss :
```
.page {
    background-color: #2C2C2C;
}
```

how the code should look like in gulpfile.js?
If root file is not index.css, what is this file and how it should look?

**Comment by michael-ciniawsky** [comment]
```diff
- @import "/src/css/block/body.pcss";
+ @import "./block/body.pcss";
```

**Comment by DjonyBastone** [comment]
how the code should look like in gulpfile.js?
```
gulp.task('css', () => {
    // callback to access the current
    // vinyl-file processed by gulp
    const config = (file) => ({
        plugins: [
            require('postcss-import')({ root: './scr/css/*.css' })
        ]
    });
    return gulp.src('/scr/css/block/*.css')
        .pipe(postcss(config))
        .pipe(gulp.dest('/dest'));
});
```

**Comment by michael-ciniawsky** [comment]
```diff
- require('postcss-import')({ root: './scr/css/*.css' })
+ require('postcss-import')({ root: file.dirname /* => ./src/css */ })
```

This way each imported file is relative to it's imports starting in the directory of the imported file

**Comment by DjonyBastone** [comment]
fail (((
![image](https://user-images.githubusercontent.com/17172262/33111707-3a445480-cf71-11e7-8264-d61123031030.png)

gulpfile.js
```
const gulp = require('gulp');
const postcss = require('gulp-postcss');
const atImport = require('postcss-import');

gulp.task('css', () => {
    const config = (file) => ({
        plugins: [
            require('postcss-import')({ root: file.dirname /* => ./src/css */ })
        ]
    });
    return gulp.src('/scr/css/*.css')
        .pipe(postcss(config))
        .pipe(gulp.dest('/dest'));
});
```
The contents of the file /src/css/index.css :
`@import "./block/body.css";`

The contents of the file /src/css/block/body.css :
```
.page {
    background-color: #2C2C2C;
}
```
In my case, quick start does not work

**Comment by michael-ciniawsky** [comment]
```diff
- return gulp.src('/scr/css/*.css')
+ return gulp.src('/src/css/*.css')
```

**Comment by michael-ciniawsky** [comment]
```diff
- .pipe(gulp.dest('/dest'));
+ .pipe(gulp.dest('dest'));
```

**Comment by DjonyBastone** [comment]
Is also not working. Poured this example on Github - [pcss-import](https://github.com/DjonyBastone/pcss-import)

**Comment by DjonyBastone** [comment]
@michael-ciniawsky if not difficult please check the example - what's the problem

**Comment by michael-ciniawsky** [comment]
https://github.com/DjonyBastone/pcss-import/blob/master/gulpfile.js#L11  You still have the typo in there ? https://github.com/postcss/postcss-import/issues/319#issuecomment-346251899 `scr => src`. Also add this line to your `gulpfile.js` please

```diff
    return gulp.src('/scr/css/*.css')
        .pipe(postcss(config))
+       .on('error', (err) => console.error(err))
        .pipe(gulp.dest('/dest'));
```

**Comment by DjonyBastone** [comment]
Many thanks!!!! 
I'm not versed in JS. Just learning.
Literally took the line "root: file.dirname /* => ./src/css */"
Now it works
```
const gulp = require('gulp');
const postcss = require('gulp-postcss');

gulp.task('css', () => {
    const config = (file) => ({
        plugins: [
            require('postcss-import')({ root: './src/css *' })
        ]
    });
    return gulp.src('./src/css/*.css')
        .pipe(postcss(config))
        .pipe(gulp.dest('./dest'));

});
```
