### ISSUE TITLE
Question: How to import from module/src?

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [postcss/postcss-import#320]
Hi guys,

I have `module/src/common-styles/variables.pcss`, how to import it to `style.pcss`?

I write such way:

```css
/* style.pcss */
@import "~module/src/common-styles/variables.pcss";
```

But webpack says: `Module build failed: Error: Failed to find '~module/src/common-styles/variables.pcss'`

but if I write this way:

```css
/* style.pcss */
@import "module/src/common-styles/variables.pcss";
```
(without "~" sign (BTW, I cannot understand how it works...))

then it works.

But my WebStorm says me that it is kind of unresolvable instead of "~" way. So what should I do?

Thanks.

**Comment by RyanZim** [comment]
The `~` sign is webpack-specific. I'm not a webpack expert; @michael-ciniawsky can you help here?

**Comment by michael-ciniawsky** [comment]
> The ~ sign is webpack specific

`postcss-import` doesn't support this syntax. If you want to use it use the `css-loader` with the `importLoaders` option instead and remove `postcss-import`

**Comment by AlexanderTserkovniy** [comment]
Does not work w/o `postcss-import`:

```
ERROR in ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]___[hash:base64:10]"}!./node_modules/postcss-loader/lib?{"config":{"path":"/frontend/postcss.config.js"}}!./src/components/presentational/SignInForm/SignInForm.pcss
Module not found: Error: Can't resolve '~ui-components/src/common-styles/font.pcss' in '/frontend/src/components/presentational/SignInForm'
@ ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]___[hash:base64:10]"}!./node_modules/postcss-loader/lib?{"config":{"path":"/frontend/postcss.config.js"}}!./src/components/presentational/SignInForm/SignInForm.pcss 4:10-379 11:51-420 16:41-410 17:49-418 17:449-818
```

**Comment by AlexanderTserkovniy** [comment]
Hi guys @michael-ciniawsky @RyanZim, I found another issue, could you help?

I import fonts fonts the module:
`@import "module/src/common-styles/font.pcss";`

In the font file there is relative path usage of fonts:
```css
@font-face {
  font-family: "Work Sans Medium";
  font-style: normal;
  font-weight: 500;
  src: url("../assets/fonts/Work_Sans/WorkSans-Medium.ttf") format("truetype");
}
```

And this module is linked via npm link. Module bundler is webpack (resolve.symlinks tried did not work). So it says:

```
Module not found: Error: Can't resolve '../assets/fonts/Work_Sans/WorkSans-Medium.ttf' in '/Users/[path]/frontend/src'
```

**Comment by RyanZim** [comment]
https://github.com/postcss/postcss-url ?

**Comment by AlexanderTserkovniy** [comment]
@RyanZim thanks it helped! :) so using it and path not starting with `~`.

**Comment by RyanZim** [comment]
Closing for now.
