### ISSUE TITLE
Import file by absolute URL

### ISSUE THREAD

**Issue by softshape** [postcss/postcss-import#330]
Is this possible at all?

I have a statement 
`@import "/common/css/message.jquery.css";`

I tried all the variations for the **path** option to make postcss-import find this file; none of them work. Where should **path** point to make this work?

**Comment by softshape** [comment]
I've found the reason. On Windows, postcss-import won't woth with slashes in URL correctly. I had to replace them with backslashes, like `\\css\\message.jquery.css`, and it works now.

**Comment by softshape** [comment]
Please reopen the issue - while the backslash solution fixes this for Windows, it's not compatible with Linux. In production everyone uses standard slashes, so we had to restore the URL back to `@import "/common/css/message.jquery.css"` and postcss-import's broken again.

Please advice how to configure postcss-import for absolute path to work it properly both in Windows and Linux environments?

**Comment by RyanZim** [comment]
Ah, sorry; didn't realize that (not a windows user).

**Comment by RyanZim** [comment]
Just trying to understand this. If you're doing `@import "/common/css/message.jquery.css";`; there's no question where that points to on *nix. But I'm not sure how you could resolve that path on Windows; would the leading `/` represent `C:\`?

**Comment by softshape** [comment]
And where `@import "/common/css/message.jquery.css"` points on Linux? This is browser's CSS first of all, and browser resolves it as "http://domain.com/common/css/message.jquery.css". 

postcss-import doesn't show how it resolves this path; the error is just like this:

> Error: Failed to find '/common/css/message.jquery.css'

The full path to this CSS file on my computer is C:\Work\src\common\css\. I tried to add both C:/Work/src/common/css/ and C:/Work/src/ to **path** variable; no luck.

**Comment by RyanZim** [comment]
On Linux, it's an absolute path, starting from the very root of the filesystem. If you're trying to use `/` to resolve from your project root; postcss-import doesn't support that AFAIK.

**Comment by RyanZim** [comment]
Closing for lack of response.
