### ISSUE TITLE
Don't import js files when css files are available

### ISSUE THREAD

**Issue by ocombe** [postcss/postcss-import#334]
I'm trying to import `@fortawesome/fontawesome`, in my scss file I use the following code:
```scss
@import "~@fortawesome/fontawesome";
```

But then I get an error in webpack:

```sh
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/renderer/styles.scss
Module build failed:
undefined
        ^
      Invalid CSS after "var noop": expected "{", was "= function noop() {"
      in C:\www\i18n-editor\node_modules\@fortawesome\fontawesome\index.es.js (line 5, column 10)
 @ ./src/renderer/styles.scss 4:14-200
 @ multi ./src/renderer/styles.scss
```

The package.json for fortawesome contains the following properties:
```
"main": "index.js",
"module": "index.es.js",
"jsnext:main": "index.es.js",
"style": "styles.css",
```

Apparently postcss import is trying to import `index.es.js` which is a js file, instead of `styles.css`. It should check the different supported package.json properties to see if there is a `style` property first, before it tries to load any other entry. Or it should not try to load js files if that's all that is available to it.

**Comment by RyanZim** [comment]
You've got webpack configured wrong; `~` is a webpack-specific thing, postcss-import doesn't handle that. @michael-ciniawsky is the webpack expert here. Can you post the relevant portions of your webpack config?

**Comment by ocombe** [comment]
The ~ is handled by webpack indeed, it's not the problem here (I think), since this plugin is loading something from that node module, just not what it should

**Comment by RyanZim** [comment]
@ocombe The entire import statement containing the `~` is being handled by webpack. postcss-import would error out if it had to process an import with a `~`.

**Comment by michael-ciniawsky** [comment]
Remove `postcss-import` and let `css-loader` handle `@import` as a JS Module Request (webpack dedupes `@import` then (at least most of the time)). Then add `style`  to  `mainFields`  in [`config.resolve`](https://webpack.js.org/configuration/resolve/)

**webpack.config.js**
```
const config = {
  resolve: {
    mainFields: [ 'style' ] // Resolver looks for pkg.style
  } 
}
```

The issue is unrelated to `postcss-import` and can be closed

**Comment by ocombe** [comment]
Ok thanks!

**Comment by ItalyPaleAle** [comment]
Is there a way to get postcss-import to handle this rather than css-loader? The reason is that using `importLoader` with css-loader fixes Font-Awesome/Fork-Awesome for me, but it breaks `@apply`.
