### ISSUE TITLE
Processing silently aborts on missing import

### ISSUE THREAD

**Issue by timkelty** [postcss/postcss-import#35]
When importing a file that doesn't exist, postcss processing seems to abort suddenly (i'm using `gulp-postcss`; I get `Starting 'build:postcss'` but never a `Finished`, and my `dest` files aren't created).

It seems like it should either:
* Continue processing and leave @import rule untouched
* Continue processing and remove @import rule
* Fail w/ an error

**Comment by timkelty** [comment]
Note: with the new `glob` feature (thanks @kswedberg!), this is not a problem.

`@import './doesnotexist/**/*.css';` will remove that rule and continue processing.

**Comment by MoOx** [comment]
What about that https://github.com/postcss/postcss-import/blob/732b2535be2a336ac0c2c47c5e3e966d20be4866/index.js#L377-L382 ?
You are sure nothing is catching this error ?

**Comment by timkelty** [comment]
Well the `import-missing.css` test is passing, so maybe it is just a problem when running through gulp-postcss?

**Comment by MoOx** [comment]
Looks like indeed.

**Comment by w0rm** [comment]
@MoOx shouldn't this error be an instance of [CssSyntaxError](https://github.com/postcss/postcss/blob/master/Runner%20Guidelines.md#31-dont-show-js-stack-for-csssyntaxerror) to output a bit of css code that caused this error?

**Comment by MoOx** [comment]
It's totally not a syntax error.

**Comment by MoOx** [comment]
I think the current error is pretty clear about what is happening.

**Comment by MoOx** [comment]
Any status on this @timkelty @w0rm ?

**Comment by w0rm** [comment]
@MoOx imho you may close this issue as the error is correctly thrown and catched by gulp-postcss.

**Comment by timkelty** [comment]
Yep, go ahead and close.
