### ISSUE TITLE
Perf problems, maybe due to recursive loop

### ISSUE THREAD

**Issue by Whoaa512** [postcss/postcss-import#355]
Hey awesome module but I'm running into perf problems with a very low module count.

While adding `console.time` logs, I noticed that `parseStyles` inside postcss-import is called multiple times for the same file in some recursive loop that I don't fully understand.

Here's a small repo that I created to demonstrate what I'm talking about.

https://github.com/Whoaa512/postcss-import-perf

When you run `yarn start`, you'll notice that the log `parseStyles on ${FILENAME}` shows up multiple times for `/src/components/Switch/switch.css`.

This is somewhat representative of what I'm seeing in my application expect the I see files in question hit that `parseStyles` function as many as 30 times in what appears to be a loop processing the same files over and over.

Could you help understand what's going on here? 

What does this comment mean? https://github.com/postcss/postcss-import/blob/f72bdc20cdc6495b07a15c4929873abe04c72950/index.js#L260

**Comment by RyanZim** [comment]
That comment means that we need to recurse and process any nested import statements. i.e. if A imports B, check if B imports something else.

**Comment by RyanZim** [comment]
@Whoaa512 Can you please reduce your test case a little more and remove react/webpack from the equation (postcss-cli is fine)? It makes it easier for me to look at the problem.

**Comment by Whoaa512** [comment]
Sure, I'll thin it out today.

**Comment by RyanZim** [comment]
Closing for lack of response.
