### ISSUE TITLE
Ignores import if ; missed at the end of line

### ISSUE THREAD

**Issue by A** [postcss/postcss-import#366]
Hello, mb it isn't an error of your great plugin, but I decided to notify it. I have this css:

```css
@import "reset.css";
@import "base.css"
@import "header.css"
```

My build finished without any error, but only `reset.css` inlined.

**Comment by RyanZim** [comment]
Semicolons are required in CSS; without them, it won't work properly.

**Comment by A** [comment]
@RyanZim i updated issue,plz check

**Comment by A** [comment]
Of curse I know how css works, I created this issue, bcz this behavior is quiet and different of how postcss behaves. If it isn't addressed correct, or if you don't want to fix it, i'm ok with it. Just notified you.

**Comment by RyanZim** [comment]
This would be an issue with postcss, not with `postcss-import`. Perhaps postcss should be throwing an error here. In any case, this isn't something postcss-import can fix

**Comment by A** [comment]
Ok, thank you much for answer.
