### ISSUE TITLE
postcss-import breaks the sourcemap in some special case

### ISSUE THREAD

**Issue by andreymal** [postcss/postcss-import#378]
If:

1) the CSS file starts with a comment;
2) there are no extra characters (e.g. spaces or newlines) between this comment and CSS;
3) the `postcss-import` plugin is enabled —

then the sourcemap is shifted by few lines.

You can download example here: [postcss_test4.zip](https://github.com/postcss/postcss-import/files/10296362/postcss_test4.zip)

**Command:** `postcss src/main.css -o build/main.css --map`

**postcss.config.js**

```javascript
module.exports = (ctx) => ({
  map: {inline: true},
  plugins: [
    require('postcss-import')(),
  ]
})
```

**src/main.css**

```css
/* test */.foo {
    color: blue;
}

body {
    color: red;
}
```

Correct sourcemap (without `postcss-import`, maybe with any other plugins, Firefox):

![](https://i.imgur.com/HA3P0wo.png)

Incorrect sourcemap (with `postcss-import`, Firefox):

![](https://i.imgur.com/jmOlOzj.png)

Note that the broken sourcemap will by visible only in Firefox if you will use postcss directly.

If you will use Webpack, then the sourcemap will look broken even with Chrome. But I don't think that this is Firefox or Webpack bug, because everything works fine when the `postcss-import` plugin is disabled.

**Comment by RyanZim** [comment]
I'm not going to download a zip file to reproduce this; please use a GitHub repo or GitHub gist.

**Comment by andreymal** [comment]
@RyanZim why? This zip file has no viruses or something else. You can reproduce this even without this zip file. All required information is attached as plain text in the text of this issue. I do not see any reason to create a GitHub repo or GitHub gist.

**Comment by RyanZim** [comment]
Sorry so long in getting around to this.

`postcss-import` isn't just messing with the sourcemap; it's modifying the CSS. The output with `postcss-import` enabled is:
```css
/* test */.foo {
    color: blue;
}body {
    color: red;
}
```

**Comment by romainmenke** [comment]
I can not reproduce this.

<img width="360" alt="Screenshot 2022-12-23 at 17 58 28" src="https://user-images.githubusercontent.com/11521496/209373125-66731b98-be3d-49dc-b4cd-bb4fc671574a.png">

This occurred many versions ago of `postcss`, `postcc-import` and source map dependencies.
I think we can close this?

**Comment by andreymal** [comment]
Okay. I'm not working very closely with postcss at the moment; if I run into a similar problem again, I think I'll create another issue.

**Comment by romainmenke** [comment]
Thank you for following up on this @andreymal.
It is rare to get feedback from the original poster after 4 years :)
