### ISSUE TITLE
Glob fails with livereload

### ISSUE THREAD

**Issue by jeffjewiss** [postcss/postcss-import#38]
I'd like to preface this by saying I'm having a hard time isolating this bug.

I have an ember-cli app using Postcss with a number of plugins. The import plugin works fine for finding node modules, like normalize.css, and relative files (ie. "components/header"). However, when I enable globbing in the options object and try a number of syntaxes:

```
@import "components/*
@import "components/**/*
@import "components/*.css
@import "components/**/*.css
```

It works fine on first load, but upon saving a file and having livereload kick off a new build of the application the globbed components aren't included in the build, so in a way it fails silently. I initially thought it had to do with my settings or config, but then it shouldn't even work for the first load.

I was hoping to get some help in isolating this behaviour because I think this type of setup is likely fairly common.

**Comment by MoOx** [comment]
For my concern, I don't use glob/nor ember so I am probably not the best person to help. And I didn't write the glob feature, @kswedberg did.

**Comment by kswedberg** [comment]
@MoOx, thanks for calling this to my attention. 
@jeffjewiss, I've never used ember-cli, but I can test it out with a regular postcss setup and livereload. It has been working fine piped through gulp and using gulp-watch. If you could give me more info about what you're using for the livereload setup, I'll try to match up as much of it as possible here and see if I can locate a problem.

**Comment by jeffjewiss** [comment]
@kswedberg sorry for the delay in replying.

I'm going to try and setup an isolated test case or new Ember project and share the repo in the hopes that it helps isolate or demonstrate the issue. I'll post here when I have something, cheers.

**Comment by kswedberg** [comment]
Great. Thanks, @jeffjewiss !

**Comment by jeffjewiss** [comment]
I created a test case with an Ember app generated using ember cli here: https://github.com/jeffjewiss/ember-cli-postcss-import-example

To install it and get it running you'll need to `npm install` `bower install` and then you should be able to start it with `npm start`.

There's a glob import in `app/styles/app.css` for the components folder. If you edit  `app/styles/components/test.css` while the app is running (something trivial like changing the background color), the component styles are no longer imported. If you use the full path instead of a glob it works fine.

**Comment by kswedberg** [comment]
thanks for the example project, @jeffjewiss. I'll take a look as soon as I can.

**Comment by kswedberg** [comment]
@jeffjewiss I set up the project locally and got it running. I think the problem might have something to do with how ember (or broccoli?) caches the resulting files. Not sure. In any case, I was able to get things working fine by add `from: 'app/styles/app.css'` to `app.postcssOptions.plugins[0].options` in Brocfile.js. So the `app` variable declaration now looks like this:

```js
var app = new EmberApp({
  postcssOptions: {
    plugins: [
      {
        module: postcssImport,
        options: {
          glob: true,
          from: 'app/styles/app.css'
        }
      }
    ]
  }
});
```

Let me know if that works for you, too.

**Comment by jeffjewiss** [comment]
@kswedberg thanks for looking in to this issue and finding a fix! I'm not familiar enough with how broccoli caches files to confirm if that's causing the issue, but I suspect it's related.

My solution was to update the broccoli plugin to extend the postcss options for each plugin so that they all have access to the "from" and "to" paths. I think that's likely better than having to repeat it for each plugin.

That seemed to fix the issue on my example app so I'm going to close this issue. I'll report back if it reappears on other apps.

Thanks!

**Comment by kswedberg** [comment]
Excellent. Glad it works, @jeffjewiss . And, yes, please let me know if the problem persists elsewhere.
