### ISSUE TITLE
Imports generated with [new postcss.atRule()] fail during postcss-import step

### ISSUE THREAD

**Issue by BananaBobby** [postcss/postcss-import#381]
Hey, I've got a rare case, where I add imports to css files manually with my own postcss plugin before passing it to postcss-import plugin. I've got two possible cases there:

1. I have an import rule in the file and I have to an import with variable overrides after that. It works for me in that case as I'm just using `rule.cloneAfter({ params: path });`

2. I've got a variables file, where I should import a file with overrides. I don't have another import rule there, so have to create one manually. I do it like this:
```
const atRule = new postcss.atRule({
    name: 'import',
    params: `'${themePath}'`,
    // also tried adding parent: root here
});
root.prepend(atRule);
```

It breaks when I run it with the 2nd one: `Error: Failed to find '../../themes/cjk/colors.variables.css'.`

If I disable postcss-import plugin - I get correct import path. Also if I write the same import manually in the css file - I get 2 imports that have the same path, but postcss-import breaks on the one that was created manully. 

My current assumption is that I'm missing some properties when I create an atRule manually, since it works fine with clone, but cant figure out what can it be.

**Comment by RyanZim** [comment]
My first guess is that you're getting your path wrong. Try building a reduced test case that has a flat directory structure (i.e. all the CSS is in the same directory), and see if you can reproduce.

**Comment by BananaBobby** [comment]
Built with a custom build script instead, so I'm closing it, unless anyone else needs to handle this rare case.
