### ISSUE TITLE
can import path support alias ??

### ISSUE THREAD

**Issue by cleverboy32** [postcss/postcss-import#386]
i  found postcss with webpack, cant resolve alias path import.

for exmaple: 

@import '~main/styles/index.css'; cant resolve the file.  but webpack css-loader can.
but if i use postcss-loader, i cant use css-import-loader.
hope the question can resolve

**Comment by RyanZim** [comment]
`~` is webpack-specific syntax that postcss-import does not support.

**Comment by viT-1** [comment]
It is not webpack specific. For example it also used in [typescript projects](https://github.com/viT-1/systemjs-ts-es6-vue/blob/617f45c63c35fe7d615f2c1ca6130d95d71bfa2c/src/tsconfig.paths.json) and js project (resolved [by Babel and its tsconfig plugin](https://github.com/viT-1/systemjs-babel-es6-vue/blob/6b3259cb300cebfd7bafaefff637882e607457a3/babel.alias-and-html.json))
