### ISSUE TITLE
import paths don't change

### ISSUE THREAD

**Issue by Mr-Chilly** [postcss/postcss-import#388]
I'm trying to chnage import paths in my scss files:

```
@import 'theme/variables/colors';
```
to:
```
@import 'themes/uk/theme/variables/colors';
```
whilst using rollup & rollup-plugin-postcss.

I've tried a few things, however I cant seem to get this plugin to chnage the import paths at all!

```
const postcssImport = require("postcss-import");

module.exports = context => ({
  plugin: [
    postcssImport({
      // root: "dave/dave/dave",
      // resolve(id, basedir, importOptions) {
      //   console.log(id);
      //   return "dave/dave/dave";
      // }
      path: ["dave/dave/dave/"]
    })
  ],
  modules: true,
  namedExports: true,
  sourceMap: true,
  minimize: true
});
```

Sorry for the noob question, and you point out where im going wrong! thanks

**Comment by RyanZim** [comment]
`postcss-import` inlines your imports, it's not for changing your import paths.
