### ISSUE TITLE
Can we add the option to import underscored file names like Sass

### ISSUE THREAD

**Issue by Designer023** [postcss/postcss-import#39]
In Sass you can import files with underscores without adding underscores in the code- When the file name is actually _my-file.scss :

    @import "my-file.scss"
    // or 
    @import "my-file"

Unless I'm missing something it would be handy to add this. Having loads of underscores in the names makes it ugly to read and its also useful to have a prefix that's ignored so we can exclude the files from watch tasks etc

Thanks you

**Comment by MoOx** [comment]
Hum, not sure I want this sassy thing in here.
That's specific to sass & his way to build non _* files & consider _* files as partial (not to build as output files).

**Comment by bloodyowl** [comment]
maybe let people implement a custom path resolver could do without making it sass-specific.

**Comment by MoOx** [comment]
good idea indeed @bloodyowl

**Comment by srcspider** [comment]
+1 to simple path resolver

Would personally like to be able to specify files relative to a root.

**Comment by MoOx** [comment]
> Would personally like to be able to specify files relative to a root.

You have [`root` and `paths` options](https://github.com/postcss/postcss-import#options) for that

**Comment by SlexAxton** [comment]
Might be what you're looking for https://github.com/jonathantneal/postcss-partial-import

**Comment by TrySound** [comment]
Ref #145

**Comment by MoOx** [comment]
Closing in favor of #145
