### ISSUE TITLE
Enhancement: Removing unused @chaset at-rulers and possible encoding convertions

### ISSUE THREAD

**Issue by iAdramelk** [postcss/postcss-import#4]
Never used `@charset` at-rules myself and not really understand why somebody may want to make css files with different `@charset` values (importing css from external libraries perhaps?), but specificaition allows it.

Good idea will probably to do the following: If any of imported files have `@charset`, then convert file to UTF-8 from this charset and remove `@charset` at-rule.

But it is not really a urgent feature, it can be done sometimes later.

**Comment by TrySound** [comment]
@MoOx Does this make sense now?

**Comment by MoOx** [comment]
Why not now?

**Comment by TrySound** [comment]
cssnext issue was closed and I always use only utf-8 :)

**Comment by MoOx** [comment]
Yeah but you are not alone? What is the problem of keeping this issue open?

**Comment by TrySound** [comment]
@MoOx Will be fixed in 10 or more version ... :)

**Comment by MoOx** [comment]
Nobody asked for this in a while, I guess we can close...
