### ISSUE TITLE
Postcss-import combined with react hotloader

### ISSUE THREAD

**Issue by 0nn0** [postcss/postcss-import#40]
Hey there.

Has anyone gotten auto-reload (ReactHotloader) working using on imported css files using the postcss-import plugin? The problem I'm having is that any changes made in css files that get imported by a main css file do not to directly show up on screen.

I'd like to figure out whether this is an issue caused by my own setup, the import-plugin, ReactHotLoader, and whether there is a good solution for this.

I've created an example case in the following repo: https://github.com/0nn0/hotloader-postcss-imports/

You can produce the problem using the following steps.
1. Check out Branch postcss-import-plugin
2. Run `npm install`
3. Run `npm run start`
4. Open `http://localhost:3000/`
5. Change background-color in styles.css (change will be directly visible)
6. Change background-color in component.css (change will NOT be visible until you restart the app)

If I do not use the postcss-import plugin, then none of the postcss-plugins set in the webpack config will be applied on any of the to be imported css files, in this case components.css.

Any help would be much appreciated.

**Comment by MoOx** [comment]
From what I see, you are not using postcss-import https://github.com/0nn0/hotloader-postcss-imports/blob/master/webpack.config.js#L32

**Comment by 0nn0** [comment]
@MoOx It's in the postcss-import-plugin branch

https://github.com/0nn0/hotloader-postcss-imports/tree/postcss-import-plugin

**Comment by MoOx** [comment]
The thing is, webpack do not know the dependencies.
That we implemented a `onImport()` hook used by [cssnext-loader](https://github.com/cssnext/cssnext-loader).
Maybe you should also take a look to [react-styled](https://github.com/bloodyowl/react-styled), we (@bloodyowl and me) have good hot reload results with this module.

**Comment by 0nn0** [comment]
@MoOx Thanks for the help.

With the cssnext-loader the page reloads nicely as expected.

When I use the cssnext-plugin for postcss it breaks the reloading for css that gets imported (see the postcss-cssnext branch). I would love to be able to use cssnext with other postcss plugins while keeping the reloading. Is there no way to inform webpack about the dependencies to enable auto-reloading in this setup?

**Comment by MoOx** [comment]
The part that use cssnext can be used by any loader

https://github.com/cssnext/cssnext-loader/blob/c7b79f5281a5e63adca933fc4ec434f965e686e3/index.js#L25-L27

I think postcss-loader should be able to use this if postcss-import is detected. Maybe you can create an issue on this loader.

That said, I've created a issue on cssnext to be able to plug your own stuff https://github.com/cssnext/cssnext/issues/118

**Comment by 0nn0** [comment]
Created an issue (here)[https://github.com/postcss/postcss-loader/issues/8] for the postcss-import loader. 

Will keep an eye on react-styled and your cssnext issue regarding plugins.

Thanks again for your help!

**Comment by MoOx** [comment]
Cool. Thanks !
