### ISSUE TITLE
Import scss file from home directory ~

### ISSUE THREAD

**Issue by jolution** [postcss/postcss-import#403]
Hey there,

I try to import SCSS files from my home directory, like:
`@import '~/Developer/foldername1/extensionname/Frontend/assets/scss/element/extensionname.scss';`

The path has not been changed except for the tilde, the Home directory/folder on the Mac.

> ~

The folder /Developer has been moved to the home directory, so I adjusted the paths. I have tried it with fileending and without, as well as with url () and without. I also included include_path, unfortunately without success. 

Error: File to import not found or unreadable: ~/Developer(...)

Since I can no longer create a symlink for security reasons, and the path of several on different computers with different user names is synchronized, the question would be what I could test? A heartfelt thank you

**Comment by jolution** [comment]
I changed ~/Developer for a symlink in /var, and it seems to work. The tilde doesnt work here.

**Comment by RyanZim** [comment]
The tilde is an expansion that's done by your shell, and isn't straightfoward to support here, sorry.
