### ISSUE TITLE
@import doesn't work with `.pcss` or `.postcss` files - only `.css`

### ISSUE THREAD

**Issue by coderesolution** [postcss/postcss-import#404]
This dependency doesn't appear to work with `.pcss` or `.postcss` files, but works perfectly with my `.css` files.

Please can this be resolved, or is there an existing solution?

Thank you in advance

**Comment by RyanZim** [comment]
You will need to include the `.pcss` or `.postcss` extension in your import statement to load them

**Comment by coderesolution** [comment]
@RyanZim so `.pcss` and `.postcss` files don't work with the importing via `/dir/*` or `/dir/**`?

Is it possible to allow my import to work with any, for example, something like:
```
@import '/directory/**/*.{css,pcss,postcss,scss,sass}'
```

Thanks!

**Comment by RyanZim** [comment]
I think the above import should work

**Comment by RyanZim** [comment]
If this is something you really want, PR welcome to add an extensions option to customize the extensions away from the default of `['.css']`
