### ISSUE TITLE
Async FS calls to improve perfomance

### ISSUE THREAD

**Issue by ai** [postcss/postcss-import#41]
PostCSS 4.1 brings async support, so we can make `postcss-import` [much faster](https://github.com/postcss/postcss/issues/341)

**Comment by andyjansson** [comment]
Added a [PR for caching](https://github.com/postcss/postcss-import/pull/47) which should also help with performance.

**Comment by jedmao** [comment]
I have a commit [here](https://github.com/jedmao/postcss-import/commit/3a788c06a679f5cfab3a5eb92ffaa24a1db30cb1) you can cherry-pick to get started. Unfortunately, that code makes the `ignore` test fail and I can't yet figure out why. I think I've exhausted my willingness to work on this issue, but feel free to take that commit and do what you will with it.

Also, I noticed the use of `fs.existsSync` in this plugin's code. I want to point out the fact that [this will be deprecated](https://nodejs.org/api/fs.html#fs_fs_existssync_path) along with [the asynchronous version](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback), `fs.exists`. There's also [another comment in the docs](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) that states:

> In particular, checking if a file exists before opening it is an anti-pattern that leaves you vulnerable to race conditions: another process may remove the file between the calls to fs.exists() and fs.open(). Just open the file and handle the error when it's not there. 

> fs.exists() will be deprecated.

Maybe the more graceful solution is to just try opening the files and throw any errors that come up.

**Comment by MoOx** [comment]
6.1.1 has an `async` option to enable postcss async use, so we might use it to detect async mode and use async fs read. Should not be a big deal from here. Maybe we might use denodeify to transform fs.readFile to a promise.

**Comment by MoOx** [comment]
I guess we can close, right @TrySound ?
