### ISSUE TITLE
Allow import of multiple files using director or array

### ISSUE THREAD

**Issue by limitlessloop** [postcss/postcss-import#412]
In order to import several files from a npm package, you have store all files at the root of your npm package.

```css
@import yourcss
@import yourcss/reset
```

It would be useful if I could specify a folder or an array of files. For example:

```json
{
    "style": "dist/typolize/"
}
```

And the folder structure would look like the following

```
dist/
    yourcss/
      index.css
      reset.css
```

This would help to organise code from the npm package a lot better.

**Comment by RyanZim** [comment]
We're just following the way Node.js resolves the `main` field; I don't think it's wise to deviate from that standard. If you have a `src`/`dist` directory structure, you can make the top level files simply contain an import (i.e. reset.css contains `@import "./dist/yourcess/reset.css"`)

**Comment by limitlessloop** [comment]
Hi @RyanZim thanks for your reply. The issue with your suggestion is it doesn't allow users to use specific parts of someone's framework. Even tailwindcss has this issue and they put all their stylesheets in the root directory, which is unorganised in my opinion. 

Can you explain a bit more about why you don't think it's wise to deviate from the way Node.js resolves the `main` field? I would argue that CSS imports have a different need than what the Node.js protocol provides.

**Comment by RyanZim** [comment]
First off, we at postcss-import didn't come up with the way the `style` field works; that convention was already in place. I think postcss-import is the largest project that makes use of `style`, but there may be others out there; not sure. I think it's unwise to potentially break the ecosystem by changing a de facto standard.

We also currently use standardized tooling for this: https://github.com/browserify/resolve If we build our own standard, we'd have to fork and maintain that.

Node itself has some experimental changes in the pipe related to this: https://nodejs.org/api/esm.html#esm_package_exports When that is considered stable, if there's good ecosystem tooling for it that we can use, we can revisit this discussion, and I think we can probably move in that directon.

**Comment by limitlessloop** [comment]
Thanks for providing some context. I don't think many packages use the `style` field, it's not well documented or a standard, but I take your comment on board regarding maintaining another process for resolving paths.

The documentation you linked to looks like it could be good to contribute to with use cases like this. I think it's important to allow discussions like this, otherwise we limit the potential for change.
