### ISSUE TITLE
@import - Error: Failed to find './assets/variables'

### ISSUE THREAD

**Issue by sonicparke** [postcss/postcss-import#414]
I'm having trouble figuring out why my imports can't be found.

Trying import an `scss` file into any other `scss` produces this error:

``` sh
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--13-3!./node_modules/postcss-loader/src??postcss!./src/styles.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find './assets/variables'
```

Here is a repo displaying the issue:
https://github.com/sonicparke/tailwind-angular

For ease here is my webpack config for this:
``` js
import * as webpack from 'webpack';
import * as postcssImport from 'postcss-import';
import * as tailwindcss from 'tailwindcss';
import * as autoprefixer from 'autoprefixer';

export default {
  module: {

    rules: [
      {
        test: /\.scss$/,
        loader: 'postcss-loader',
        options: {
          ident: 'postcss',
          syntax: 'postcss-scss',
          plugins: () => [
            postcssImport(),
            tailwindcss('./tailwind.config.js'),
            autoprefixer()
          ]
        }
      }
    ]
  }
} as webpack.Configuration;
```

And my styles.scss:
``` scss
@import './assets/variables';

@tailwind base;
@tailwind components;
@tailwind utilities;

.blue {
  background-color: $blue;
}

```

**Comment by RyanZim** [comment]
IIRC, postcss-loader has its own import parsing, that uses webpack's module resolution; in which case you don't need postcss-import. Not super familiar with webpack.

**Comment by sonicparke** [comment]
@RyanZim Thanks. I just removed it and am getting the same error. However, that doesn't mean I didn't need to remove it so I'll roll without it for a while and hopefully once I get the error resolved I won't need it anyway.

**Comment by sonicparke** [comment]
So `@import` seems to work if it's in the same folder as the file your importing it into. So by moving `_variables.scss` up one folder and importing it as `./variables` it works. Interesting.

**Comment by iworksrc** [comment]
@sonicparke import like this `@import '../src/assets/variables.scss'`

**Comment by changeMyself1992** [comment]
我也是同样的问题 草了
