### ISSUE TITLE
Create React App 3.4.1 > Adding normalize.css

### ISSUE THREAD

**Issue by mjfneto** [postcss/postcss-import#421]
Hi! While following CRA's [documentation](https://create-react-app.dev/docs/adding-css-reset/), I came across an issue with the `@import` rule:

![image](https://user-images.githubusercontent.com/25172271/82121576-87daab00-9764-11ea-8f58-d957c503dcf5.png)

Is this the right place to find a solution to this warning? If not, sorry for the inconvenience.

Addendum: I haven't found `postcss-import` inside `node_modules`. Is this related in any way with the issue?

**Comment by RyanZim** [comment]
`@import-normalize` isn't something that is handled by `postcss-import`, that should be handled by https://github.com/csstools/postcss-normalize.
