### ISSUE TITLE
Allow option to suppress @import after other CSS warning

### ISSUE THREAD

**Issue by K3TH3R** [postcss/postcss-import#426]
I'm working on a new Nuxt.js website right now that uses [@nuxtjs/style-resources](https://www.npmjs.com/package/@nuxtjs/style-resources) to automatically inject a `_variables.pcss` file into each Vue component's `<style>` instance. This allows me to avoid doing this in every component:
```html
<style type="postcss">
  @import '~/styles/_variables.pcss';

  /* actual component styles */
</style>
```

However, `postcss-import` is refusing to import anything in my global style file:
```postcss
@import './lib/_variables.pcss';
@import './lib/_globals.pcss';
@import './lib/_type.pcss';
```
This is, essentially, because that `style-resources` plugin is automatically injecting the variables into the top of the file prior to the `@import` statements being processed. 

My suggestion is to add a property to the `options` object like `suppressWarning` which is `false` by default and if `true`, allows us to bypass the warnings added in #240. I can put together a PR if this sounds like a reasonable idea.

**Comment by RyanZim** [comment]
This isn't just a warning; postcss-import is unable to import your other files if there is CSS before the `@import` statement. What you want to do in your case is create a file that simply contains `@import '_variables.pcss';`, then have `@nuxtjs/style-resources` inline that file into your CSS, and let postcss-import do all the importing.
