### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by jonnitto** [postcss/postcss-import#427]
Currently, this plugin is not compatible with [PostCSS 8]. It would be great if you could make this plugin compatible with the latest version.

[PostCSS 8]: https://github.com/postcss/postcss/releases/tag/8.0.0

**Comment by RyanZim** [comment]
Yep, on my list to do. I maintain both this and `postcss-cli`, I'm focusing on the CLI first. If somebody wants to submit a PR here, that'd speed things up.

**Comment by bcomnes** [comment]
https://evilmartians.com/chronicles/postcss-8-plugin-migration is the migration guide for anyone wanting to take a stab at it.  I unfortunately don't have time at the moment.
