### ISSUE TITLE
Imported CSS changes order within comments

### ISSUE THREAD

**Issue by spacedawwwg** [postcss/postcss-import#434]
**pre-compiled css**
```
/*! purgecss start ignore */
@import '~@example-library/thing.css';
/*! purgecss end ignore */

.other {
  color: red;
}
```

**postcss compiled css**
```
.example-library-thing {
   color: blue;
}

/*! purgecss start ignore */
/*! purgecss end ignore */

.other {
  color: red;
}
```

I'm just wondering if it's possible to retain the order of the imported css within the comments like in the above example?

**Comment by RyanZim** [comment]
Unfortunately, I doubt it. postcss-import depends on `@import`s being at the top.

You're welcome to mess around and see if it's possible to fix this, but I doubt it'll be reasonable; and I won't merge something that makes the codebase completely obtuse just to support this. I know this probably isn't the news you're looking to hear, but I want to be honest with you up front.

**Comment by spacedawwwg** [comment]
@RyanZim no problem! I can get around my specific issue by adding a whitelist pattern to a `purgecss.config`, it was more a question of "is it possible?" - So thank you for the answer!
