### ISSUE TITLE
@import must precede all other statements - warning should be optional

### ISSUE THREAD

**Issue by phawxby** [postcss/postcss-import#439]
Our css pipeline involves doing to importing first, followed buy a whole bunch of other postcss plugins. We receive the "@import must precede all other statements" warning even though later plugins clean it up. The warnings should be optional for those that don't need it.

**Comment by RyanZim** [comment]
The warning is there because postcss-import cannot process those statements that are not at the top; in your pipeline, are these url imports that aren't processed by postcss-import anyhow?

**Comment by RyanZim** [comment]
Closing for lack of reply
