### ISSUE TITLE
Blank lines. Sourcemap and compressed-css error

### ISSUE THREAD

**Issue by yr4ik** [postcss/postcss-import#443]
Blank lines appear after the postcss-import plugin.
As a result, sourcemap is incorrect and extra volume if compression is enabled.

not compressed:
![4210151567](https://user-images.githubusercontent.com/5104469/100100713-e8604880-2e69-11eb-8994-83cf47f9da7e.jpg)

compressed:
![5541e5b93c](https://user-images.githubusercontent.com/5104469/100100859-1fcef500-2e6a-11eb-8101-92d80b63472c.jpg)

without postcss-import:
i have a working sourcemap or css compressed into one line
![80c7894de3](https://user-images.githubusercontent.com/5104469/100101217-a257b480-2e6a-11eb-9413-aacbb24aa80b.jpg)

**Comment by RyanZim** [comment]
I'm not sure I fully understand your issue here; in any case, you should be running your minifier _after_ postcss-import. Are you saying sourcemaps are broken?

**Comment by yr4ik** [comment]
postcss-import adds a line break "\n" after each style block (see screen 1 arrows. And screen 2). Which confuses the sourcamap line numbering.

**Comment by RyanZim** [comment]
`postcss-import` should be correctly producing a sourcemap that takes into account the line breaks; if that isn't the case, that's a bug.

**Comment by yr4ik** [comment]
Wor example:
`const postcss = require('postcss');

 postcss([
		require('cssnano'),
		require('autoprefixer')
	])
	.use(require('postcss-import'))
	.process(css_code, postcss_options)
	.then(pr => {
		result.code = pr.content;
		process.stdout.write(JSON.stringify(result));
	})
`
As a result, the code will not be compressed into one line (img 3). 
As a result will be each css block on a new line (img 2)

If you remove .use(require('postcss-import')) - css will be in one line

**Comment by RyanZim** [comment]
Your plugin ordering is wrong; `postcss-import` should generally be first, and `cssnano` last, like this:

```js
postcss([
    require('postcss-import')
    require('cssnano'),
    require('autoprefixer')
  ])
  .process(...
```
That way, `cssnano` removes the blank lines. Additionally, `autoprefixer` will run on the CSS that was imported from other files.
