### ISSUE TITLE
Add option to run a processor on imported AST

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-import#45]
Convenient to run a linter on the fly. No extra processing.
Ideas:
- change onImport option to pass all files + latest filename/ast
- add an afterParse (or onParse) option that take filename + ast

**Comment by jedmao** [comment]
I shouldn't need to know the filename or AST to run through processors on import. What do you think of a `processors` option instead? It couldn't be simpler than this:

```js
processors: [
    require('postcss-nested'),
    require('postcss-bem-linter')
],
```

And hey! If they really want something more custom, they can always add another processor to the mix:

```js
processors: [
    require('postcss-nested'),
    require('postcss-bem-linter'),
    postcss.plugin('postcss-remove', function (opts) {
        var filter = opts.prop || 'z-index';
        return function (css, result) {
            css.eachDecl(filter, function (decl) {
                decl.removeSelf();
            });
        };
    })
],
```

**Comment by jedmao** [comment]
@MoOx any updates on this one? I'm kind of blocked until this is implemented :(

**Comment by MoOx** [comment]
pr are welcome. Otherwise I will handle that when I get time.
