### ISSUE TITLE
Error in charset handling 'UTF-8' vs "UTF-8" : https://github.com/postcss/postcss-import/pull/447

### ISSUE THREAD

**Issue by Jose-Derecho** [postcss/postcss-import#452]
Hello, this feature has an issue, both files are UTF-8, 

Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Incompatable @charset statements:
  'UTF-8' specified in /path/node_modules/typicons.font/src/font/typicons.css
  "UTF-8" specified in /path/src/styles.scss
     at ....
     at ....
     at ....

**Comment by RyanZim** [comment]
Typicons charset usage is incorrect. As per https://developer.mozilla.org/en-US/docs/Web/CSS/@charset#syntax, charset statements must be double-quoted. I would advise you to file an issue with Typicons to get this fixed.
