### ISSUE TITLE
Migration Clarification - 12.0.1 to 14.0.1 

### ISSUE THREAD

**Issue by sivaraj-v** [postcss/postcss-import#454]
Hi @RyanZim & Postcss Team, 
Greeting to you all !!

After updating to 14.0.1, Core business logic got changed it seems 
From the changelog, I see there are breaking changes are there.

[https://github.com/postcss/postcss-import/blob/master/CHANGELOG.md](https://github.com/postcss/postcss-import/blob/master/CHANGELOG.md)

What is code change as a developer have to change in their code to get output similar to 12.0.1 version ? 

**colors.css**
```
/* colors.css */

:root {
    --errorRed: #e03030;
}
```

**app.css**
```
/* app.css */

@import "./colors.css";

.app {
  border: 1px solid var(--errorRed);
}
```

**postcss.config.js**
```
module.exports = ({
  plugins: [
    require('postcss-import')()
  ],
})
```

**CLI**
> postcss app.css -p -o output.css -m

```
/* Output  - 12.0.1 */ (Working as expected)

:root {
    --errorRed: #e03030;
  }

.app {
  border: 1px solid var(--errorRed);
}
```

```
/* Output  - 14.0.1  */ (Not working as expected)

@import "./colors.css";

.app {
  border: 1px solid var(--errorRed);
}
```

**Comment by RyanZim** [comment]
Did you update to postcss v8?

**Comment by sivaraj-v** [comment]
> Did you update to postcss v8?

Yes, I'm using postcss v8 

```
    "postcss": "8.0.0",
    "postcss-cli": "8.0.0"
```

**Comment by RyanZim** [comment]
Yeah, from what I can see, everything should work. Can you make a reduced test case repo?

**Comment by sivaraj-v** [comment]
Yeah sure

**Comment by sivaraj-v** [comment]
Here is the test case repo @RyanZim 

[https://github.com/sivaraj-v/postcss-import](https://github.com/sivaraj-v/postcss-import)
I have share you the access for repo


```
npm install
npm run postcss:run 
```

**Comment by RyanZim** [comment]
I am unable to install dependencies in that repo with npm, due to some `peerDependency` conflicts. If I unpin all the versions using `^`, it installs fine, and compiles correctly.

**Comment by sivaraj-v** [comment]
Hi @RyanZim  
If you could share us exact version, and the fixed test case repo with all latest version. That will help lot of developer to resolve the issue or else they will stay in older version and facing the same issue.

**Comment by RyanZim** [comment]
Just apply the diff I posted, run either `npm install` or `yarn`, depending on what you're using, and everything should work.
