### ISSUE TITLE
Remove postcss imports

### ISSUE THREAD

**Issue by oscarotero** [postcss/postcss-import#455]
According [to migration guide](https://evilmartians.com/chronicles/postcss-8-plugin-migration), the Step 4 recomends to remove the postcss imports and use the second argument of the Root function.

This is not the case of process-content.js file: https://github.com/postcss/postcss-import/blob/master/lib/process-content.js#L7 

I think the `processContent` function should have another argument for that, in order to remove the direct import. This would be very helpful for the Deno version, to avoid loading two different versions of postcss.

**Comment by RyanZim** [comment]
Agreed, PR welcome.

**Comment by oscarotero** [comment]
Done!
