### ISSUE TITLE
support the "browser" field like browserify

### ISSUE THREAD

**Issue by matthewmueller** [postcss/postcss-import#46]
Would be nice to get support for that, should be pretty simple to swap out `resolve` for `browser-resolve`

**Comment by MoOx** [comment]
I am not familiar with this option in browserify. Is it to make postcss-import working in the browser ?
If so, I am open to a PR :)

**Comment by emilbayes** [comment]
I think this is what @matthewmueller meant: https://github.com/defunctzombie/package-browser-field-spec

**Comment by RyanZim** [comment]
I don't see the point of that; `browser` is for JS, not CSS. Use `style`.

If I'm missing something, please comment; I'll reopen.
