### ISSUE TITLE
devDependencies instead of dependencies

### ISSUE THREAD

**Issue by EatonZ** [postcss/postcss-import#463]
Shouldn't the [installation instructions](https://github.com/postcss/postcss-import/blob/master/README.md#installation) use `npm install -D postcss-import` over `npm install postcss-import` since this is a package used during development, and is not a package containing files that get published?

**Comment by RyanZim** [comment]
Good catch! PR welcome!

**Comment by EatonZ** [comment]
@RyanZim See https://github.com/postcss/postcss-import/pull/464
