### ISSUE TITLE
Unable to find uri in @import

### ISSUE THREAD

**Issue by MaluNoPeleke** [postcss/postcss-import#466]
I am using postcss-cli with a npm script of the package.json like this:
```
  "scripts": {
    "build": "postcss site/postcss/tailwind.css -o assets/css/style.css",
    "watch": "postcss site/postcss/tailwind.css -o assets/css/style.css --watch",
    "prod": "cross-env NODE_ENV=production postcss site/postcss/tailwind.css -o assets/css/style.css"
  },
```
My postcss.config.js:
```
const cssnano = require('cssnano');
module.exports = {
    plugins: [
      require('postcss-import')({ path: "site/postcss/", root: "site/postcss/", from: "site/postcss/" }),
      require('tailwindcss'),
      require('postcss-nesting'),
      require('autoprefixer'),
      ...process.env.NODE_ENV === 'production'
            ? [cssnano({
              preset: 'default',
            })]
            : []
    ]
  }
```
And the tailwind.css in the site/postcss/ directory:
```
@import ./custom.css;
@tailwind base;
@tailwind components;
@tailwind utilities;
```
When I run the script I always get the following error:

> 1:1     ⚠  Unable to find uri in '@import ./custom.css' [postcss-import]

But the custom.css file is in the same directory as the tailwind.css
How can I include it?

**Comment by RyanZim** [comment]
You need to quote your paths, like this: `@import './custom.css';`

**Comment by MaluNoPeleke** [comment]
Thanks and sorry, that was an easy one.
Any idea why it worked but left out the following part?

`/* class name must matches the value of `ratio` setting. */
.lazysrcset-ratio {  
    position: relative;
}
.lazysrcset-ratio > img {
    display: block;    
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
}
.lazysrcset-ratio > img:after {
    display: block;
    width: 100%;
    height: 0;
    content: '';
}
`

**Comment by RyanZim** [comment]
No idea; probably going to need a reduced test case to debug that one.

**Comment by MaluNoPeleke** [comment]
Should I open a new ticket about this?

**Comment by RyanZim** [comment]
Sure
