### ISSUE TITLE
Typo in the README

### ISSUE THREAD

**Issue by JUSSIAR** [postcss/postcss-import#471]
### The README file contains a typo in section **Usage** (subsection _css/input.css_)

There is a line:
> ```@import "normalize.css"; /* == @import "../node_modules/normalize.css/normalize.css"; */```

It includes duplicated `normalize.css` in url

Also there is the same problem in subsection _will give you_

**Comment by RyanZim** [comment]
This isn't a typo, normalize.css is the name of the Node module, so there's a directory in `node_modules` named `normalize.css`, and the main css file is `normalize.css` inside that directory.
