### ISSUE TITLE
Refactor (explode) index.js

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-import#49]
This file is becoming huge. All functions accept too many parameters, it's going to be a pain to maintain if we don't do something :)

**Comment by jedmao** [comment]
Submitted [a PR](https://github.com/postcss/postcss-import/issues/59); though, I think there's much more work to be done. We should try to keep functions as small as 5 lines if possible. They should do only one thing and be named well, according to that one thing. I see a lot of fat functions in here, so there must be a way to reduce them down.

Anyway, I think my PR is a good first pass, to get rid of most of the parameters you mentioned here in this issue.

**Comment by TrySound** [comment]
@MoOx Let's continue. I'd like to make granular PRs which will be simplify codebase more and more. The first great thing would be removing sync mode at all. Caz it doesn't need. process().css is only for debug, not production code. So back compatibility doesn't matter.

**Comment by TrySound** [comment]
@MoOx Then need to cover with tests some "dead code", which has not reaction when I remove it. Some of such code can be wrong.

**Comment by MoOx** [comment]
WIP on dev branch. Thanks @TrySound!
