### ISSUE TITLE
[feature] Add flag to fail when @import statements doesn't precede all other statements

### ISSUE THREAD

**Issue by zardoy** [postcss/postcss-import#490]
Hi! I'm moving from `scss-bundle` as this plugin is more configurable and I can control resolve and loading process.

However, This plugin removes (or sometimes leaves as-is) some imports without printing anything.

Sample code:
```js
//@filename: index.mjs
import postcss from 'postcss';
import postcssImport from 'postcss-import';

const { content } = await postcss(postcssImport()).process(`
$color: red;
@import url('./styles.scss');
`, { from: './index.scss' });
console.log(content);
```
```scss
//@filename: styles.scss
$color: green;
body {
    background: $color;
}
```
Output:
```scss

$color: red;

```

If added this to `index.js:166`:
```
const toPrint = statements.filter((statement) => ['warning'].includes(statement.type))
if (toPrint.length) console.error(toPrint);
```

It printed a warning on line 3 with text `@import must precede all other statements (besides @charset or empty @layer)`. I saw the readme, but not a warning from my script.

I don't see anything configurable from `postcss` side, so I think this plugin must handle it itself.

I propose:

- print warning by default
- add object flag `warn`, so we can disable this warning with `warn: { topImport: false }`. We can also merge this feature with https://github.com/postcss/postcss-import/pull/479

- add flag to fail on this warning, so we can ensure that bundle will be fixed
- I think it make sense to make this behavior default in next major

Thoughts? Of course I can contribute fix myself.

**Comment by zardoy** [comment]
This a duplicate of https://github.com/postcss/postcss-import/issues/439, however I hope I described it in a more clear way with the proposed solution. Also I wonder, why I don't see that warning?

**Comment by RyanZim** [comment]
The warning is added to `result.warnings()` according to the postcss plugin spec. If you're not using a runner for postcss, you'll have to process this yourself: https://github.com/postcss/postcss/blob/main/docs/guidelines/runner.md#42-display-resultwarnings We can't just log to the console, because we don't know what environment postcss is being run in; hence the warning message spec.

If you want to contribute a finished version of #479 that'd be welcome.

**Comment by zardoy** [comment]
Sorry for the delay with response

> I don't see anything configurable from postcss side

It turns out it was my bad, sorry I didn't even know they have runner guidelines. Thank you so much for pointing me to that.

Feel free to close it as I don't see anything actionable from this plugin side, runner can try to find `@import must precede all other statements` warnings and throw an error.
