### ISSUE TITLE
@imports with URLs by nested jsx arent moved to the top of the build

### ISSUE THREAD

**Issue by titoBouzout** [postcss/postcss-import#491]
I am using rollup like this:

```
const postcss= require('rollup-plugin-postcss')
const postcssimports = require('postcss-import')

// ... 
let  plugins: [
  postcss({
	  modules: true,
          plugins: [postcssimports()],
	  extract: true,
	  minimize: true,
	  sourceMap: true, //'inline',
  })]
```

So then, when some nested jsx files do the following 

`import styles from './someComponent.css'`

and someComponent.css has the following 

`@import url('https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap');`

The resulting bundled css file, wont have that declaration at the top of the bundle. It will be somewhere in the middle, depending on how much css you used before.

Is this a bug?

**Comment by RyanZim** [comment]
postcss-import does not generally move imports around. I suspect this is more of a rollup thing than a postcss-import thing.
