### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by MassMessage** [postcss/postcss-import#493]
In order to try solve the following error:

```
Electron Forge was terminated:
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve 'button-up.svg' in 'C:\Users\jckj\Desktop\merge\Newton\src'
```

give from the code:

```
.myContainer {
    @include meta.load-css("7.css/dist/7");
}

```

which is result of searching for the resource files, such as button-up.svg in `src` dir but those files are in the `7.css/dist/7` folder itslf. How can I make `meta.load-css()` search in the 7 dir folder instead of?

**EDIT 1**

I've tried using postcss-import like this: 

```
// postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    'postcss-import': require('postcss-import') ({
      path: ['7.css/dist']
    })
  },
}
```

but this didn't solve the import error. What am I missing?

**Comment by RyanZim** [comment]
This is unrelated to postcss-import; I don't know what `@include` is, we certainly don't support it.
