### ISSUE TITLE
Browser jspm/SystemJS support

### ISSUE THREAD

**Issue by MadLittleMods** [postcss/postcss-import#50]
I want to use `postcss-import` with [`plugin-postcss`](https://github.com/geelen/plugin-postcss)([jspm](http://jspm.io/)/SystemJS plugin). But since `postcss-import` uses `fs` and `resolve` packages/calls it isn't compatible when trying to run it client side in the browser.

I am not sure on the best way to solve this other than using `fetch` and inlining when the promise resolves.

---

*Related*: I opened geelen/plugin-postcss#4 which will add the proper processing `from` option for nice path resolves.

**Comment by MoOx** [comment]
Sounds complicated to handle.

**Comment by MoOx** [comment]
But not impossible I guess. PR will be welcome.

**Comment by geelen** [comment]
This is exactly the use-case that https://github.com/geelen/jspm-loader-css (which replaces plugin-postcss anyway) was built to solve. We even wrote a new syntax for loaders handling mutliple files called ICSS (https://github.com/css-modules/icss). Hopefully that'll negate the need for this plugin to have to support loaders *as well* as the file system.

**Comment by MoOx** [comment]
So we can close ?

**Comment by MoOx** [comment]
I guess we can.

**Comment by onlywei** [comment]
@geelen's jspm-loader-css project seems to have gone stale: https://github.com/geelen/jspm-loader-css/issues/34

Should we re-open?
