### ISSUE TITLE
Shouldn't this plugin work with @use?

### ISSUE THREAD

**Issue by melMass** [postcss/postcss-import#500]
Hi,

Is there a reason for not handling `@use` too?

Thanks

**Comment by RyanZim** [comment]
This plugin follows the native CSS `@import` spec, not SCSS behavior. Since `@use` is not part of native CSS, it's out of scope.

**Comment by melMass** [comment]
Ah!! Thanks I'm a bit in a config rabbit hole, that makes sense. I think I have pretty much the issue of #390 but with vite / SvelteKit.
