### ISSUE TITLE
Add ability to reference values from an import, but not inline the content (similar to LESS `import (reference)`)

### ISSUE THREAD

**Issue by jgornick** [postcss/postcss-import#501]
As the title says, I'm looking to import our design system's utility class framework and use those classes to compose other styles, via other plugins that can reference classes. However, because our design system utility class framework is provided globally, I don't need to inline/import the content into my stylesheet. 

Is there a way to import without inlining the imported content?

**Comment by RyanZim** [comment]
No; this plugin follows the CSS `@import` spec. One way to do this would be pass your class framwork to the plugins that you're using to compose styles as an option (if they support something like that). Another option would be some kind of cleanup plugin run later to remove those unused classes after they've been used via reference.
