### ISSUE TITLE
Mention postcss-import-url in docs?

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-import#516]
@romainmenke Should https://github.com/unlight/postcss-import-url be mentioned in the README for those who want URL imports?

**Comment by romainmenke** [comment]
That would be helpful to others who want to use these plugins together.
Not immediately obvious which options to set to make everything work together.

created a little test to make sure it indeed works : 
- https://github.com/romainmenke/postcss-all-the-imports
- https://github.com/romainmenke/postcss-all-the-imports/blob/main/src/styles.css


`postcss-import-ext-glob` is already mentioned :

> If you are looking for Glob Imports, you can use [postcss-import-ext-glob](https://github.com/dimitrinicolas/postcss-import-ext-glob) to extend postcss-import.

`postcss-import-url` can be mentioned in the same list :

> If you want to import remote sources, you can use [postcss-import-url](https://github.com/unlight/postcss-import-url) with its `dataUrls` plugin option to extend postcss-import.

**Comment by RyanZim** [comment]
Yep, sounds good. @romainmenke want to submit a PR? Feel free to link to your example repo if you think that's helpful.

**Comment by romainmenke** [comment]
submitted :)

I didn't link to the example repo because it might become confusing in the future if it isn't kept up to date. I mainly wanted to be sure that the flow worked.
