### ISSUE TITLE
Not able to use postcss-import. Giving error ->Unable to resolve @import "variables.css"

### ISSUE THREAD

**Issue by siddhantchopra** [postcss/postcss-import#522]
Im trying to migrate my project to vitejs and having an issue with postcss-imports. While running the project, and configuring postcss using vite.config.js for postcss import. The css files are not working
Here is my code-snippet

```js
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';
import atImport from 'postcss-import';

export default defineConfig({
  plugins: [
    react(),
    atImport({
      path: ['src/themes/config/variables.css'],
      resolve: (id, baseDir, importOptions) => {
        console.log(id, baseDir, importOptions);
      },
    })
  ]
});
```

Please let me know what I'm doing wrong so that I can fix this issue

Node version: 18.16.0
These are my modules installed for the project

```
"postcss": "^8.4.23",
"postcss-cli": "^10.1.0",
"postcss-cssnext": "^3.1.1",
"postcss-import": "^15.1.0",
"postcss-syntax": "^0.36.2",
```

![error](https://github.com/postcss/postcss-import/assets/30842286/618bc93d-0ecf-4c09-a371-c36d2ea8f0b4)

**Comment by RyanZim** [comment]
Why are you using the `path` option?
