### ISSUE TITLE
import inside a selector

### ISSUE THREAD

**Issue by pixeline** [postcss/postcss-import#528]
Hello!

For a WordPress project, I would like the WP Editor to use the same CSS as the theme, so the authors see how their content will look like.

I hoped I could simply do this so all the theme css would be applied to the WP Editor contaier, but that does not have any effect:

```css
body#tinymce{
    @import "app.css";
}
```
the compiled css shows exactly the same.
Is there a rightful way to achieve what I want ?

Here is my postcss config file
```js
module.exports = {
    plugins: [
        require('postcss-nested-ancestors'),
        require('postcss-import'),
        require('tailwindcss/nesting'),
        require('postcss-extend-rule'),
        require('tailwindcss'),
        require('autoprefixer')
    ]
}
```

**Comment by RyanZim** [comment]
As noted in the README, this plugin follows the CSS `@import` spec, which requires imports to be at the top of the CSS file. There may be other postcss plugins that allow some kind of inlining like you want, but this isn't the plugin for that.
