### ISSUE TITLE
Default Imports

### ISSUE THREAD

**Issue by Xyeut** [postcss/postcss-import#559]
Hey! I'm working with nuxt3 and I have three files I'm trying to import variables, fonts, and default, ideally, I want to have variables and fonts imported in the default file, however I'm not sure how to I globally import default throughout my project

**Comment by RyanZim** [comment]
I'm not sure if I understand the question. You need to have an `@import` statement wherever you want to import something, there's no way to import a file without that.

**Comment by Xyeut** [comment]
@RyanZim Hey, what I'm trying to do is see if there is any postCSS setting or plug-in that allows for a file to be be imported in every other file
