### ISSUE TITLE
Support a way to process a URL with fragments

### ISSUE THREAD

**Issue by sapphi-red** [postcss/postcss-import#560]
In Vite, we were resolving `@import '#foo'` with [subpath imports](https://nodejs.org/api/packages.html#subpath-imports). But since postcss 16.0.0 (https://github.com/postcss/postcss-import/pull/539), these URLs are filtered out before it reaches any code that the plugin user side can control. That made Vite not able to resolve these URLs (https://github.com/vitejs/vite/issues/15861).

Would it be possible to add an option to skip this default behavior?

**Comment by romainmenke** [comment]
Hi @sapphi-red,

Can you give more info on the use cases?

Is there an alternative syntax that is maybe more suitable?

This plugin follows the CSS specification and url fragments on imports do not have any effect there. So the current implementation is actually correct.

**Comment by sapphi-red** [comment]
Like [this plugin supports](https://github.com/postcss/postcss-import?tab=readme-ov-file#usage), Vite supports importing from node_modules in the import of CSS files.
```css
/* can consume `node_modules`, `web_modules` or local modules */
@import "cssrecipes-defaults"; /* == @import "../node_modules/cssrecipes-defaults/index.css"; */
@import "normalize.css"; /* == @import "../node_modules/normalize.css/normalize.css"; */
```
We pass a custom [resolve option](https://github.com/postcss/postcss-import?tab=readme-ov-file#resolve) to this plugin to also support [Subpath imports](https://nodejs.org/api/packages.html#subpath-imports) (and other resolving features) in CSS. The advantage of supporting this in CSS is that it is intuitive by being consistent with Node.js and allows configuration in one place (`package.json`).

**Comment by romainmenke** [comment]
Those import statements do not have a url fragment.
Can you provide a more complete example please :)

--------

The current implementation completely skips imports with a fragment.
We can make a few changes which might resolve this issue:
- urls with fragments are no longer skipped
- urls with fragments are passed to custom resolvers
- the build-in resolver trims fragments

**Comment by romainmenke** [comment]
After some more thought I think we need to just revert to the old behavior.
Not only Vite, but also other stacks might depend on this same feature.

The intention behind https://github.com/postcss/postcss-import/issues/537 was to make this plugin more correct. Not to make it less useful.

**Comment by romainmenke** [comment]
@sapphi-red Can you check if the test scenario I created covers the Vite use case?
https://github.com/postcss/postcss-import/pull/561/files
