### ISSUE TITLE
Plugin options are no longer passed in

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss-import#60]
Ever since https://github.com/postcss/postcss-import/commit/5bbe1205e7f20a70317797ff941b22516e7c7a14 was merged in, I'm seeing that the plugin options no longer get passed in.

I'm using [cssnext](http://cssnext.io/) and I dove into `cssnext/node_modules/postcss-import/index.js` and added the following to the top of the `AtImport` function block to see what was happening:

```js
function AtImport(options) {
  console.log("options:", options)
  process.exit()
```
And I get the following in my shell:
```
options: undefined
```
If, however, I pull index.js from the previous commit, https://github.com/postcss/postcss-import/commit/c900ccc297eb13cd13dccc9fdbe3f8e3e8583589, I get the following:
```
options: { path: 'src/app/styles/blocks',
  plugins:
   [ { [Function: creator] postcss: [Object] },
     { [Function]
       postcssPlugin: 'postcss-bem-linter',
       postcssVersion: '4.1.11' } ] }
```
It must have something to do with replacing this:
```js
/**
 * Expose the plugin.
 */
module.exports = AtImport
```
with this:
```js
module.exports = postcss.plugin(
  "postcss-import",
  AtImport
)
```
But I'm not sure how that broke things.

**Comment by MoOx** [comment]
Hum that's weird. This is supposed to work. I think it's working for other plugins like postcss-custom-props https://github.com/postcss/postcss-custom-properties/blob/b843b93f6e4eca396c34872329da21c131e31d2f/index.js#L133

I am surprised that tests are passing...

@ai any idea here ?

**Comment by jedmao** [comment]
@MoOx disregard. It has something to do with the `process.exit()` in there. I'm trying to figure out why my `path` option isn't working properly. I'll close this issue for now.
