### ISSUE TITLE
Support comma separated filenames for import

### ISSUE THREAD

**Issue by pauleustice** [postcss/postcss-import#61]
Using Sass it's possible to import using comma separated files, e.g:

```
@import
  'module1.pcss',
  'module2.pcss';
```

This would be great to have available from within this plugin as it tidies up your main stylesheet file.

**Comment by MoOx** [comment]
Sorry but this plugin will respect original import syntax, so unless a w3c draft mention a new syntax, we will not allow that for now.

**Comment by pauleustice** [comment]
Fair enough, but seeing as most people using postcss are porting over from scss and less then don't you think it would be a useful addition?

No good front-end dev should ever be using CSS imports so I'm not sure why replicating exactly that broken feature is useful, whereas adding functionality that extends it - and it's non-breaking too - would surely benefit users?

**Comment by MoOx** [comment]
I will be open to get this merged as a feature disabled by default.

**Comment by TrySound** [comment]
@pauleustice You can use glob pattern for this.

**Comment by mstade** [comment]
I'd suggest closing this issue, if this plugin aims to simply add support for the standard `@import` rule. There already are other tools to process scss, no need to feature creep this plugin to support non-standard syntax to aid in a porting process – a process done *once* anyway.

> No good front-end dev should ever be using CSS imports so I'm not sure why replicating exactly that broken feature is useful, whereas adding functionality that extends it - and it's non-breaking too - would surely benefit users?

This sounds pretty dogmatic. The `@import` isn't broken, and people shouldn't refrain from using it. In fact, it's one of the more forward thinking features of css; its use shouldn't be discouraged.

**Comment by pauleustice** [comment]
@mstade Perhaps 'broken' was the wrong word. But 'seriously flawed,' is certainly an apt description. You can't surely be advocating the use of the heavily documented blocking nature of `@import` within CSS?

@trysound Many things can be accomplished using globbing, but stylesheet authors want these links in a unified location, not hidden away in build or config scripts. Please, reconsider. Libraries like Sass and Less have a huge following for good reason and I believe are a good benchmark for emulation.

**Comment by oleersoy** [comment]
So is 

``` css
@import
  'module1.pcss',
  'module2.pcss';
```

That much better than:
``` css
@import module1.css;
@import module2.css;
```

Either way we are inlining the modules right?

**Comment by TrySound** [comment]
@oleersoy Not better at all. The same as writing in js
```js
var name1,
      name2;
```
or
```js
var name1;
var name2;
```

Not too much too write but we can simply comment any line without parsing error (I mean comma and semicolon).

**Comment by TrySound** [comment]
@pauleustice @oleersoy If you like such syntax, you can write own plugin and use it.

**Comment by MoOx** [comment]
It's kind of stupid to create a plugin that will redo what postcss-import does.
That said, it can be an idea to write a plugin that transform

```scss
@import
  'module1.pcss',
  'module2.pcss';
```

to 

```css
@import "module1.css";
@import "module2.css";
```

so postcss-import can be run after.

**Comment by TrySound** [comment]
@MoOx Yes, you are right.

**Comment by oleersoy** [comment]
@TrySound I like to keep it simple and for me:

``` css
@import "module1.css";
@import "module2.css";
```
Is simple.  I also agree that it is best to defer to other plugins for the functionality requested such that `postcss-import

**Comment by mstade** [comment]
@pauleustice I most certainly can, and don't consider it flawed at all. I don't recall seeing the spec dictating transfer order, but happy to stand corrected if you can point me to such a section.
