### ISSUE TITLE
osX asks for sudo to install

### ISSUE THREAD

**Issue by fraincs** [postcss/postcss-import#70]
whenever I try to install through npm I get this error while all other postcss plugins does not asks for sudo

error: EACCES, mkdir '/Users/francis.thibault/.npm/glob/5.0.14'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/Users/francis.thibault/.npm/glob/5.0.14']...

**Comment by MoOx** [comment]
This is not a problem of this plugin. It's a problem related to your setup. 
You should clear npm cache completely and try again.
