### ISSUE TITLE
package.json should include `engines` property to note dependency on node 12

### ISSUE THREAD

**Issue by lambertsteven** [postcss/postcss-import#82]
I was currently on node 10 and trying to use the latest version, which doesn't work due to no native Promise support. The package.json should note that node 12 is a dependency via the [engines](https://docs.npmjs.com/files/package.json#engines) property so npm installs on node 10 will throw a warning.

**Comment by TrySound** [comment]
@lambertsteven You can always polyfill promises with [es6-promise](https://github.com/jakearchibald/es6-promise). I wouldn't like to get the warning everytime I install this.

**Comment by lambertsteven** [comment]
I can understand that. Could we get a note on the readme at the least that postcss-import depends on native Promises and either that requires node 12 or es6-promises?

**Comment by TrySound** [comment]
@lambertsteven It make sense for postcss readme, cause postcss-import and all postcss plugins depends on it.
But https://github.com/postcss/postcss#usage
