### ISSUE TITLE
Specification of how node_modules import works 

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss-import#86]
Hi,

Does the node_modules import work by reading the `style` attribute in package.json as specified here:
http://stackoverflow.com/questions/32037150/style-field-in-package-json

Clarification on this in the README would be very helpful.  I can submit a PR once I know the answer.  Thanks,
Ole

**Comment by MoOx** [comment]
Yes https://github.com/postcss/postcss-import/blob/062693944b992a3cf92f9c3ae3e3e6633df59f1d/index.js#L494

**Comment by oleersoy** [comment]
Super - thanks - I sent a PR with an update to the README.

**Comment by MoOx** [comment]
Closed by a4474f72659cd90f4bf21da23cfa7e5216483c77
