### ISSUE TITLE
postcss-cli --watch doesn't watch the imported sources

### ISSUE THREAD

**Issue by saiichihashimoto** [postcss/postcss-import#88]
Using ```postcss-import``` with ```postcss-cli --watch``` does not watch changes on the imported files, only the importing file. I've seen [the example provided on postcss-cli](https://github.com/code42day/postcss-cli#--watch-w) but it doesn't seem to work. I'm not sure whether this is a ```postcss-import``` problem or a ```postcss-cli``` problem.

**Comment by cameronrohani** [comment]
+1 I ran into a similar use case but didn't realize that it was happening, which lead me to here.

**Comment by MoOx** [comment]
It's probably more a postcss-cli issue since tests are ok for onImport() method.

**Comment by iam4x** [comment]
@MoOx I have the same behaviour with webpack and this postcss configuration:

```
postcss: [
      require('postcss-import')(),
      require('postcss-url')(),
      require('precss')()
],
```

**Comment by MoOx** [comment]
postcss-import already provide a way to handle that kind of use cases.

@iam4x https://github.com/postcss/postcss-loader#integration-with-postcss-import
