### ISSUE TITLE
Support for custom parsers (like postcss-scss)

### ISSUE THREAD

**Issue by danieldiekmeier** [postcss/postcss-import#96]
If I use inline comments, like

```
.u-limiter,
  width: 960px;
  // center this
  margin: {
    left: auto;
    right: auto;
  }
}
```

`postcss-import` throws an error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: postcss-import: [removed].scss:4:6: Unknown word
  width: 960px;
  // center this
     ^
  margin: {
```

I thought I could get this under control by using a plugin when calling postcss-import:

```
[gulp]
.pipe(postcss([
      require('postcss-import')({
        glob: true,
        plugins: [
          require('postcss-inline-comment')
        ]
      }),
[more gulp]
```

but I had no luck. For now, I can live without inline comments, but what would be the best way for me to get this working?

**Comment by TrySound** [comment]
@danieldiekmeier Use [postcss-scss](https://github.com/postcss/postcss-scss)

**Comment by danieldiekmeier** [comment]
Great, thank you.

**Comment by plesiecki** [comment]
@TrySound postcss-scss works fine for comments inside main css file but it doesn't work for comments inside imported files.

**Comment by danieldiekmeier** [comment]
Yes, I also have this Problem.

**Comment by TrySound** [comment]
You are right guys. Custom syntaxes wasn't added yet. I'm working on new major version and will fix this issue ASAP.

**Comment by MoOx** [comment]
see #79

**Comment by MoOx** [comment]
That should be ok in 8.x. Right @TrySound?

**Comment by TrySound** [comment]
Yep
