### ISSUE TITLE
Option to move imported content to top of file

### ISSUE THREAD

**Issue by niksy** [postcss/postcss-import#97]
Sometimes when you’re importing third-party CSS you would like to inline that content at the top of the corresponding CSS file, not at the place where it was referenced, just to avoid potential clashes with your CSS. Do you think this is valid to be included as option?

Example:

```css
@import url('library.css?postcss-import-top');
```

Content from this file will be moved at the top of output CSS.

Alternatively, you can provide list of imports you would like to move to the top inside plugin initialization:

```js
var postcss = require("postcss")
var atImport = require("postcss-import")

var css = postcss()
  .use(atImport({
    importsAtTop: ['library.css']
  }))
  .process(cssString)
  .css
```

**Comment by TrySound** [comment]
@niksy Stuff for another plugin. But seems unnecessary

**Comment by jakelazaroff** [comment]
+1 to this request. I'm importing a reset and base global styles and it would be great to have that first in the generated stylesheet, because of the cascade.

**Comment by TrySound** [comment]
Why not just move import rule at the top?

**Comment by niksy** [comment]
Yeah, you could (and should), but maybe sometimes you don’t want to rely on `@import` placement and just want to declare it and let postcss-import deal with it accordingly (with proper option for plugin).

**Comment by oleersoy** [comment]
@niksy and @jakelazaroff do you have a simple example that clearly shows why additional code and documentation should be created to support this?

**Comment by jakelazaroff** [comment]
Actually, in writing out my example I realized that my issue is either with webpack's css-loader or style.loader. Sorry about that!

**Comment by niksy** [comment]
@oleersoy sorry, I don’t, so this issue is kind of pointless? :(

But I’m looking at this from the perspective of CommonJS - you don’t rely on order of files, just their statements. Since we know that CSS works in cascade, if the imported file is not specific enough (like Normalize.css) it’s statements could be overwritten or not applied correctly, as opposed to placing it at the top of resulting file.

What most of us do today is to always remember to place those kind of files at the top. With this option this could be avoided and then you can let postcss-import place specific files in specific order.

Is this descriptive enough?

**Comment by oleersoy** [comment]
@niksy when we write CommonJS modules we rely on Node to construct the dependency graph for us.  Node is very good at this, and Browserify / Webpack as well, for the browser side.  Dependency graphs and file ordering are two different things.

CSS on the other hand should start with the foundation classes first, and the author should know this and put them first.  For example in my framework I explicity state this:
[superfly-css](https://github.com/superfly-css/superfly-css/#foundation).

Having designers stick to the practice of placing resorts first is the simplest thing we can do.

**Comment by niksy** [comment]
@oleersoy yeah, this makes sense. It’s the way which all developers are familiar with and trying to script it in any way will probably bring more problems than solutions.

**Comment by oleersoy** [comment]
@niksy I think you are right.  Feel free to close the issue, unless there is anything else you wanted us to consider.
