### ISSUE TITLE
Ignore already imported files in other CSS files

### ISSUE THREAD

**Issue by niksy** [postcss/postcss-import#98]
This is similar to the option Browserify provides with using `b.require` and `b.external` (or, for CLI usage, [multiple bundles](https://github.com/substack/node-browserify#multiple-bundles).

You would import CSS in one file (e.g. `global.css`) and when you reference that same file inside other CSS file (e.g. `about-page.css`), it will be ignored since it was already imported inside `global.css`.

Is this a valid proposal?

**Comment by TrySound** [comment]
Read docs before ask https://github.com/postcss/postcss-import#skipduplicates

**Comment by niksy** [comment]
Hm, I don’t think this (entirely) does what I mentioned in issue description. This will skip duplicates in currently processed file; what I’m looking is skipping specific duplicates across the entire stream of files.

Let’s say you have `global.css` and `about-page.css`.
About page will reference `global.css` (for caching purposes) and `about-page.css` (since it has styling for that page).
For whatever reason, both source files reference, for example, `normalize.css`.
What I’m looking for is a way to tell `about-page.css` not to import `normalize.css` since that file was already imported (or will be imported) from `global.css`.

Makes sense?

**Comment by oleersoy** [comment]
It sounds like you just need to exclude the import of `global.css` from about-page.css?

**Comment by niksy** [comment]
@oleersoy Hm, not quite. `global.css` is one output file, and `about-page.css` is another one, but both will be included on page.

For example:

```html
<link rel="stylesheet" href="global.css" />
<link rel="stylesheet" href="about-page.css" />
```

Other than the fact that both of those files are included on same page, they don’t know anything about each other, so they will import same files regardless of the fact that styles from particular import are already present on the page.

That same case is explained in [multiple bundles](https://github.com/substack/node-browserify#multiple-bundles) case for Browserify, but for JS.

**Comment by TrySound** [comment]
@niksy Okay, just make multiple bundles and process them separatly.

**Comment by oleersoy** [comment]
Indeed what @TrySound said.  You need to make the two css files mutually exlusive in terms of content.

**Comment by MoOx** [comment]
If you want complexe behavior like that, you should take a look at webpack /extract-text-plugin/code splitting and make a common chunk.
